/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_claym_0014",
  "rarity": 5,
  "weaponType": "greatsword",
  "baseAttackAtLevelNodes": [
    42,
    120,
    203,
    286,
    369,
    411
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "strength",
          "operation": "flat",
          "value": [
            16,
            28,
            41,
            54,
            67,
            80,
            92,
            105,
            124
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_claym_0014_pdi_up": {
          "stackingType": "highPriority",
          "priority": {
            "blackboardKey": "phy_dmg_up_mult"
          },
          "maxStackCount": 2,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_physical_dmg_up",
            "iconPath": "/icons/icon_battle_physical_dmg_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "duration": 0,
            "phy_dmg_up_mult": 0
          },
          "attributeModifiers": [
            {
              "attribute": "physicalDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "phy_dmg_up_mult"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "artsIntensity",
          "value": [
            8,
            14,
            20,
            27,
            33,
            40,
            46,
            52,
            62
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "artsIntensity",
          "value": [
            10,
            12,
            14,
            16,
            18,
            20,
            22,
            24,
            28
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "event": {
            "kind": "buffConsumed"
          },
          "priority": 0,
          "blackboard": {
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "phy_dmg_up_mult": [
              0.05,
              0.06,
              0.07,
              0.08,
              0.09,
              0.1,
              0.11,
              0.12,
              0.14
            ],
            "phy_spell_up": [
              10,
              12,
              14,
              16,
              18,
              20,
              22,
              24,
              28
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTags": [
                      "Skill/Character/Common/NoGuard"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "eventConsumedBuffLayerCompare",
                          "operator": "greaterOrEqual",
                          "value": {
                            "kind": "constant",
                            "value": 1
                          },
                          "outputKey": "count"
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "calculateActionValue",
                            "parameters": {
                              "key": "phy_dmg_up",
                              "operation": "multiply",
                              "left": {
                                "kind": "blackboard",
                                "key": "phy_dmg_up_mult"
                              },
                              "right": {
                                "kind": "blackboard",
                                "key": "count"
                              }
                            }
                          },
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_claym_0014_pdi_up",
                              "target": "caster",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "phy_dmg_up_mult": {
                                  "kind": "blackboard",
                                  "key": "phy_dmg_up"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_greatsword_0014",
  "iconPath": "/weapons/greatsword/wpn_greatsword_0014.webp"
} as const satisfies WeaponDefinition;

export default definition;
