/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_claym_0013",
  "rarity": 6,
  "weaponType": "greatsword",
  "baseAttackAtLevelNodes": [
    51,
    148,
    250,
    352,
    454,
    505
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "strength",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_claym_0013_combo_skill": {
          "stackingType": "refresh",
          "priority": 0,
          "maxStackCount": 0,
          "durationSeconds": {
            "blackboardKey": "duration2"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_cryst_dmg_up",
            "iconPath": "/icons/icon_battle_cryst_dmg_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "Default",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "cryst_dmg_up2": 0,
            "duration2": 0
          },
          "attributeModifiers": [
            {
              "attribute": "cryoDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "cryst_dmg_up2"
              }
            }
          ]
        },
        "buff_wpn_claym_0013_normal_skill": {
          "stackingType": "refresh",
          "priority": 0,
          "maxStackCount": 0,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_cryst_dmg_up",
            "iconPath": "/icons/icon_battle_cryst_dmg_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "Default",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "cryst_dmg_up": 0,
            "duration": 0
          },
          "attributeModifiers": [
            {
              "attribute": "cryoDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "cryst_dmg_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "attackPercent",
          "value": [
            0.05000000074505806,
            0.09000000357627869,
            0.12999999523162842,
            0.17000000178813934,
            0.20999999344348907,
            0.25,
            0.28999999165534973,
            0.33000001311302185,
            0.38999998569488525
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "battleSkill",
          "slot": "baseAddition",
          "value": [
            0.20000000298023224,
            0.23999999463558197,
            0.2800000011920929,
            0.3199999928474426,
            0.36000001430511475,
            0.4000000059604645,
            0.4399999976158142,
            0.47999998927116394,
            0.5600000023841858
          ]
        },
        {
          "kind": "damageScale",
          "target": "comboSkill",
          "slot": "baseAddition",
          "value": [
            0.20000000298023224,
            0.23999999463558197,
            0.2800000011920929,
            0.3199999928474426,
            0.36000001430511475,
            0.4000000059604645,
            0.4399999976158142,
            0.47999998927116394,
            0.5600000023841858
          ]
        },
        {
          "kind": "damageScale",
          "target": "ultimate",
          "slot": "baseAddition",
          "value": [
            0.20000000298023224,
            0.23999999463558197,
            0.2800000011920929,
            0.3199999928474426,
            0.36000001430511475,
            0.4000000059604645,
            0.4399999976158142,
            0.47999998927116394,
            0.5600000023841858
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeOutputInfliction",
          "priority": 0,
          "blackboard": {
            "cryst_dmg_up": [
              0.10000000149011612,
              0.11999999731779099,
              0.14000000059604645,
              0.1599999964237213,
              0.18000000715255737,
              0.20000000298023224,
              0.2199999988079071,
              0.23999999463558197,
              0.2800000011920929
            ],
            "cryst_dmg_up2": [
              0.20000000298023224,
              0.23999999463558197,
              0.2800000011920929,
              0.3199999928474426,
              0.36000001430511475,
              0.4000000059604645,
              0.4399999976158142,
              0.47999998927116394,
              0.5600000023841858
            ],
            "dmg_up": [
              0.20000000298023224,
              0.23999999463558197,
              0.2800000011920929,
              0.3199999928474426,
              0.36000001430511475,
              0.4000000059604645,
              0.4399999976158142,
              0.47999998927116394,
              0.5600000023841858
            ],
            "duration": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ],
            "duration2": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "originSkillTypeIn",
                    "skillTypes": [
                      "battleSkill"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "eventInflictionElementIn",
                          "elements": [
                            "cryo"
                          ]
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "conditional",
                            "parameters": {
                              "condition": {
                                "kind": "not",
                                "condition": {
                                  "kind": "timedMarkerPresent",
                                  "target": "caster",
                                  "markerId": "wpn_claym_0013_1"
                                }
                              }
                            },
                            "whenTrue": {
                              "steps": [
                                {
                                  "kind": "applyBuff",
                                  "parameters": {
                                    "buffId": "buff_wpn_claym_0013_normal_skill",
                                    "target": "caster",
                                    "inheritSourceSkillCastInfo": true,
                                    "blackboardAssignments": {
                                      "cryst_dmg_up": {
                                        "kind": "blackboard",
                                        "key": "cryst_dmg_up"
                                      },
                                      "duration": {
                                        "kind": "blackboard",
                                        "key": "duration"
                                      }
                                    }
                                  }
                                },
                                {
                                  "kind": "createTimedMarker",
                                  "parameters": {
                                    "target": "caster",
                                    "markerId": "wpn_claym_0013_1",
                                    "durationSeconds": {
                                      "kind": "constant",
                                      "value": 0.10000000149011612
                                    },
                                    "autoFinishByAction": false
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:1:sequence:0",
          "abilityEvent": "beforeOutputDamage",
          "priority": 0,
          "blackboard": {
            "cryst_dmg_up": [
              0.10000000149011612,
              0.11999999731779099,
              0.14000000059604645,
              0.1599999964237213,
              0.18000000715255737,
              0.20000000298023224,
              0.2199999988079071,
              0.23999999463558197,
              0.2800000011920929
            ],
            "cryst_dmg_up2": [
              0.20000000298023224,
              0.23999999463558197,
              0.2800000011920929,
              0.3199999928474426,
              0.36000001430511475,
              0.4000000059604645,
              0.4399999976158142,
              0.47999998927116394,
              0.5600000023841858
            ],
            "dmg_up": [
              0.20000000298023224,
              0.23999999463558197,
              0.2800000011920929,
              0.3199999928474426,
              0.36000001430511475,
              0.4000000059604645,
              0.4399999976158142,
              0.47999998927116394,
              0.5600000023841858
            ],
            "duration": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ],
            "duration2": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventDamageTagsMatch",
                    "match": "hasAll",
                    "tags": [
                      "comboSkill"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "buffStackCompare",
                          "target": "actionInputTarget",
                          "tagQueryType": "hasAny",
                          "buffTags": [
                            "Skill/Character/Common/SpellInflict/CrystInflict"
                          ],
                          "operator": "greaterOrEqual",
                          "value": {
                            "kind": "constant",
                            "value": 1
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "conditional",
                            "parameters": {
                              "condition": {
                                "kind": "not",
                                "condition": {
                                  "kind": "timedMarkerPresent",
                                  "target": "caster",
                                  "markerId": "wpn_claym_0013_2"
                                }
                              }
                            },
                            "whenTrue": {
                              "steps": [
                                {
                                  "kind": "applyBuff",
                                  "parameters": {
                                    "buffId": "buff_wpn_claym_0013_combo_skill",
                                    "target": "caster",
                                    "inheritSourceSkillCastInfo": true,
                                    "blackboardAssignments": {
                                      "cryst_dmg_up2": {
                                        "kind": "blackboard",
                                        "key": "cryst_dmg_up2"
                                      },
                                      "duration2": {
                                        "kind": "blackboard",
                                        "key": "duration2"
                                      }
                                    }
                                  }
                                },
                                {
                                  "kind": "createTimedMarker",
                                  "parameters": {
                                    "target": "caster",
                                    "markerId": "wpn_claym_0013_2",
                                    "durationSeconds": {
                                      "kind": "constant",
                                      "value": 0.10000000149011612
                                    },
                                    "autoFinishByAction": false
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_greatsword_0013",
  "iconPath": "/weapons/greatsword/wpn_greatsword_0013.webp"
} as const satisfies WeaponDefinition;

export default definition;
