/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_claym_0015",
  "rarity": 5,
  "weaponType": "greatsword",
  "baseAttackAtLevelNodes": [
    42,
    120,
    203,
    286,
    369,
    411
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "strength",
          "operation": "flat",
          "value": [
            16,
            28,
            41,
            54,
            67,
            80,
            92,
            105,
            124
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_claym_0015": {
          "stackingType": "refresh",
          "priority": 0,
          "maxStackCount": {
            "blackboardKey": "max_stack"
          },
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_def_up",
            "iconPath": "/icons/icon_battle_buff_def_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTagIds": [],
          "extendTagIds": [],
          "blackboard": {
            "def_up": 0,
            "duration": 0
          },
          "attributeModifiers": [
            {
              "attribute": "Def",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "def_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "healthPercent",
          "value": [
            0.08,
            0.144,
            0.208,
            0.272,
            0.336,
            0.4,
            0.464,
            0.528,
            0.624
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "secondary",
          "operation": "percent",
          "value": [
            0.05,
            0.06,
            0.07,
            0.08,
            0.09,
            0.1,
            0.11,
            0.12,
            0.14
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeOutputBuff",
          "priority": 0,
          "blackboard": {
            "cd": [
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1
            ],
            "def_up": [
              0.18,
              0.216,
              0.252,
              0.288,
              0.324,
              0.36,
              0.396,
              0.432,
              0.504
            ],
            "duration": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ],
            "second_attr_up": [
              0.05,
              0.06,
              0.07,
              0.08,
              0.09,
              0.1,
              0.11,
              0.12,
              0.14
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTagIds": [
                      2029588776
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "not",
                          "condition": {
                            "kind": "timedMarkerPresent",
                            "target": "caster",
                            "markerId": "wpn_claym_0015"
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "createTimedMarker",
                            "parameters": {
                              "target": "caster",
                              "markerId": "wpn_claym_0015",
                              "durationSeconds": {
                                "kind": "blackboard",
                                "key": "cd"
                              },
                              "autoFinishByAction": false
                            }
                          },
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_claym_0015",
                              "target": "eventSource",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "def_up": {
                                  "kind": "blackboard",
                                  "key": "def_up"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:1:sequence:0",
          "abilityEvent": "beforeOutputPhysicalInfliction",
          "priority": 0,
          "blackboard": {
            "cd": [
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1
            ],
            "def_up": [
              0.18,
              0.216,
              0.252,
              0.288,
              0.324,
              0.36,
              0.396,
              0.432,
              0.504
            ],
            "duration": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ],
            "second_attr_up": [
              0.05,
              0.06,
              0.07,
              0.08,
              0.09,
              0.1,
              0.11,
              0.12,
              0.14
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventPhysicalInflictionTypeIn",
                    "types": [
                      "knockDown"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "not",
                          "condition": {
                            "kind": "timedMarkerPresent",
                            "target": "caster",
                            "markerId": "wpn_claym_0015"
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "createTimedMarker",
                            "parameters": {
                              "target": "caster",
                              "markerId": "wpn_claym_0015",
                              "durationSeconds": {
                                "kind": "blackboard",
                                "key": "cd"
                              },
                              "autoFinishByAction": false
                            }
                          },
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_claym_0015",
                              "target": "eventSource",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "def_up": {
                                  "kind": "blackboard",
                                  "key": "def_up"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_greatsword_0015",
  "iconPath": "/weapons/greatsword/wpn_greatsword_0015.webp"
} as const satisfies WeaponDefinition;

export default definition;
