/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_claym_0012",
  "rarity": 5,
  "weaponType": "greatsword",
  "baseAttackAtLevelNodes": [
    42,
    120,
    203,
    286,
    369,
    411
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "strength",
          "operation": "flat",
          "value": [
            16,
            28,
            41,
            54,
            67,
            80,
            92,
            105,
            124
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_claym_0012_up": {
          "stackingType": "unique",
          "priority": 0,
          "maxStackCount": 0,
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "buff_wpn_sword_0019",
            "iconPath": "/icons/buff_wpn_sword_0019.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": false,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "Default",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "heal_up": 0
          },
          "attributeModifiers": [],
          "healModifiers": [
            {
              "enabledSide": "healer",
              "condition": {
                "kind": "healTagsMatch",
                "match": "hasAny",
                "tags": [
                  "Skill/Character/Common/Heal/ComboSkillHeal"
                ]
              },
              "processors": [
                {
                  "kind": "modifyHealingIncrease",
                  "timing": "beforeCalculation",
                  "side": "healer",
                  "addition": {
                    "blackboardKey": "heal_up"
                  }
                }
              ]
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "healthPercent",
          "value": [
            0.07999999821186066,
            0.14399999380111694,
            0.20800000429153442,
            0.2720000147819519,
            0.335999995470047,
            0.4000000059604645,
            0.46399998664855957,
            0.527999997138977,
            0.6240000128746033
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "secondary",
          "operation": "percent",
          "value": [
            0.05000000074505806,
            0.05999999865889549,
            0.07000000029802322,
            0.07999999821186066,
            0.09000000357627869,
            0.10000000149011612,
            0.10999999940395355,
            0.11999999731779099,
            0.14000000059604645
          ]
        }
      ],
      "initializationBlackboard": {
        "install_0_heal_up": [
          0.20000000298023224,
          0.23999999463558197,
          0.2800000011920929,
          0.3199999928474426,
          0.36000001430511475,
          0.4000000059604645,
          0.4399999976158142,
          0.47999998927116394,
          0.5600000023841858
        ]
      },
      "initializationSequence": {
        "steps": [
          {
            "kind": "applyBuff",
            "parameters": {
              "buffId": "buff_wpn_claym_0012_up",
              "target": "caster",
              "blackboardAssignments": {
                "heal_up": {
                  "kind": "blackboard",
                  "key": "install_0_heal_up"
                }
              }
            }
          }
        ]
      }
    }
  ],
  "assetSlug": "wpn_greatsword_0012",
  "iconPath": "/weapons/greatsword/wpn_greatsword_0012.webp"
} as const satisfies WeaponDefinition;

export default definition;
