/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_claym_0016",
  "rarity": 6,
  "weaponType": "greatsword",
  "baseAttackAtLevelNodes": [
    50,
    144,
    243,
    342,
    441,
    490
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "strength",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_claym_0016_dmgup": {
          "stackingType": "stack",
          "priority": 0,
          "maxStackCount": 0,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": {
            "blackboardKey": "duration"
          },
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_physical_dmg_up",
            "iconPath": "/icons/icon_battle_physical_dmg_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "duration": 10,
            "max_stack": 0,
            "phy_dmg_up": 0
          },
          "attributeModifiers": [
            {
              "attribute": "physicalDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "phy_dmg_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "artsIntensity",
          "value": [
            10,
            18,
            26,
            34,
            42,
            50,
            58,
            66,
            78
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "physical",
          "slot": "baseAddition",
          "value": [
            0.07000000029802322,
            0.08399999886751175,
            0.09799999743700027,
            0.1120000034570694,
            0.12600000202655792,
            0.14000000059604645,
            0.15399999916553497,
            0.1679999977350235,
            0.19599999487400055
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeCastSkill",
          "priority": 0,
          "blackboard": {
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "max_stack": [
              3,
              3,
              3,
              3,
              3,
              3,
              3,
              3,
              3
            ],
            "phy_dmg_up": [
              0.07000000029802322,
              0.08399999886751175,
              0.09799999743700027,
              0.1120000034570694,
              0.12600000202655792,
              0.14000000059604645,
              0.15399999916553497,
              0.1679999977350235,
              0.19599999487400055
            ],
            "phy_dmg_up2": [
              0.054999999701976776,
              0.06599999964237213,
              0.07699999958276749,
              0.08799999952316284,
              0.0989999994635582,
              0.10999999940395355,
              0.12099999934434891,
              0.13199999928474426,
              0.15399999916553497
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventSkillTypeIn",
                    "skillTypes": [
                      "battleSkill",
                      "comboSkill"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "not",
                          "condition": {
                            "kind": "timedMarkerPresent",
                            "target": "caster",
                            "markerId": "sk_wpn_claym_0016"
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_claym_0016_dmgup",
                              "target": "caster",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                },
                                "phy_dmg_up": {
                                  "kind": "blackboard",
                                  "key": "phy_dmg_up2"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          },
                          {
                            "kind": "createTimedMarker",
                            "parameters": {
                              "target": "caster",
                              "markerId": "sk_wpn_claym_0016",
                              "durationSeconds": {
                                "kind": "constant",
                                "value": 0.10000000149011612
                              },
                              "autoFinishByAction": false
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_greatsword_0016",
  "iconPath": "/weapons/greatsword/wpn_greatsword_0016.webp"
} as const satisfies WeaponDefinition;

export default definition;
