/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_claym_0006",
  "rarity": 6,
  "weaponType": "greatsword",
  "baseAttackAtLevelNodes": [
    50,
    145,
    245,
    345,
    445,
    495
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "will",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_claym_0006_cd": {
          "stackingType": "unique",
          "priority": 0,
          "maxStackCount": 0,
          "durationSeconds": {
            "blackboardKey": "cd"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "cd": 0
          },
          "attributeModifiers": [],
          "lifecycleSequences": {
            "finish": {
              "steps": [
                {
                  "kind": "applyBuff",
                  "parameters": {
                    "buffId": "buff_wpn_claym_0006_icon",
                    "target": "caster",
                    "inheritSourceSkillCastInfo": true
                  }
                }
              ]
            }
          }
        },
        "buff_wpn_claym_0006_icon": {
          "stackingType": "unique",
          "priority": 0,
          "maxStackCount": 0,
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_weapon_heal_skill_ready",
            "iconPath": "/icons/icon_battle_weapon_heal_skill_ready.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "heal_up": 0
          },
          "attributeModifiers": [
            {
              "attribute": "healOutputIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "heal_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "healthPercent",
          "value": [
            0.10000000149011612,
            0.18000000715255737,
            0.25999999046325684,
            0.3400000035762787,
            0.41999998688697815,
            0.5,
            0.5799999833106995,
            0.6600000262260437,
            0.7799999713897705
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "staticHealingIncrease",
          "target": "output",
          "value": [
            0.10000000149011612,
            0.11999999731779099,
            0.14000000059604645,
            0.1599999964237213,
            0.18000000715255737,
            0.20000000298023224,
            0.2199999988079071,
            0.23999999463558197,
            0.2800000011920929
          ]
        }
      ],
      "initializationSequence": {
        "steps": [
          {
            "kind": "applyBuff",
            "parameters": {
              "buffId": "buff_wpn_claym_0006_icon",
              "target": "caster"
            }
          }
        ]
      }
    }
  ],
  "assetSlug": "wpn_greatsword_0006",
  "iconPath": "/weapons/greatsword/wpn_greatsword_0006.webp"
} as const satisfies WeaponDefinition;

export default definition;
