/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_pistol_0010',
  rarity: 6,
  weaponType: 'pistol',
  baseAttackAtLevelNodes: [51, 148, 250, 352, 454, 505],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'intellect',
          operation: 'flat',
          value: [20, 36, 52, 68, 84, 100, 116, 132, 156],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_wisd_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'criticalRate',
          value: [0.025, 0.045, 0.065, 0.085, 0.105, 0.125, 0.145, 0.165, 0.195],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_crirate_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'cryo',
          slot: 'baseAddition',
          value: [0.16, 0.192, 0.224, 0.256, 0.288, 0.32, 0.352, 0.384, 0.448],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_pistol_0010_valid',
                      copiedBlackboardAssignments: {
                        cryst_dmg_up_valid: 'cryst_dmg_up2',
                        duration: 'duration',
                        max_stack: 'max_stack',
                      },
                    },
                  ],
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: null,
            },
            createTimedMarker_2: {
              action: {
                kind: 'createTimedMarker',
                parameters: {
                  target: 'caster',
                  markerId: 'wpn_pistol_0010',
                  durationSeconds: { kind: 'constant', value: 0.1 },
                  autoFinishByAction: false,
                },
              },
              next: 'applyBuff_1',
            },
            conditional_3: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_2' } },
                whenTrue: { $sequence: 'createTimedMarker_2' },
              },
              next: null,
            },
            conditional_4: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
                whenTrue: { $sequence: 'conditional_3' },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: {
                kind: 'timedMarkerPresent',
                target: 'caster',
                markerId: 'wpn_pistol_0010',
              },
            },
            data_2: {
              type: 'boolean',
              expression: { kind: 'not', condition: { kind: 'conditionNode', nodeId: 'data_1' } },
            },
            data_3: {
              type: 'boolean',
              expression: {
                kind: 'eventDamageTagsMatch',
                match: 'hasAny',
                tags: ['normalSkill', 'comboSkill'],
              },
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_pistol_0010',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'outputCriticalDamage',
          priority: 0,
          sequence: { $sequence: 'conditional_4' },
        },
      ],
      blackboard: {
        cryst_dmg_up2: [0.14, 0.168, 0.196, 0.224, 0.252, 0.28, 0.308, 0.336, 0.392],
        duration: [30, 30, 30, 30, 30, 30, 30, 30, 30],
        max_stack: [3, 3, 3, 3, 3, 3, 3, 3, 3],
      },
    },
  ],
  assetSlug: 'wpn_pistol_0010',
  icon: 'endaxis:weapons/pistol/wpn_pistol_0010',
  buffDefinitions: {
    buff_wpn_pistol_0010_valid: {
      stackingType: 'stack',
      priority: 0,
      maxStackCount: { blackboardKey: 'max_stack' },
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_cryst_dmg_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { cryst_dmg_up_valid: 0, duration: 0, max_stack: 0 },
      attributeModifiers: [
        {
          attribute: 'cryoDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'cryst_dmg_up_valid' },
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
