/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_pistol_0001',
  rarity: 3,
  weaponType: 'pistol',
  baseAttackAtLevelNodes: [29, 83, 140, 197, 254, 283],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'main',
          operation: 'flat',
          value: [10, 18, 26, 34, 42, 51, 59, 67, 79],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_main_low',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'attackFlat',
          value: [12, 14.4, 16.8, 19.2, 21.6, 24, 26.4, 28.8, 33.6],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'sk_wpn_pistol_0001',
    },
  ],
  assetSlug: 'wpn_pistol_0001',
  icon: 'endaxis:weapons/pistol/wpn_pistol_0001',
} as const satisfies WeaponDefinition;
export default definition;
