/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_pistol_0009',
  rarity: 6,
  weaponType: 'pistol',
  baseAttackAtLevelNodes: [50, 144, 243, 342, 441, 490],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'main',
          operation: 'flat',
          value: [17, 30, 44, 57, 71, 85, 98, 112, 132],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_main_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'cryo',
          slot: 'baseAddition',
          value: [
            0.055555556, 0.1, 0.14444445, 0.18888889, 0.23333333, 0.2777778, 0.32222223, 0.36666667,
            0.43333334,
          ],
        },
        {
          kind: 'damageScale',
          target: 'heat',
          slot: 'baseAddition',
          value: [
            0.055555556, 0.1, 0.14444445, 0.18888889, 0.23333333, 0.2777778, 0.32222223, 0.36666667,
            0.43333334,
          ],
        },
        {
          kind: 'damageScale',
          target: 'electric',
          slot: 'baseAddition',
          value: [
            0.055555556, 0.1, 0.14444445, 0.18888889, 0.23333333, 0.2777778, 0.32222223, 0.36666667,
            0.43333334,
          ],
        },
        {
          kind: 'damageScale',
          target: 'nature',
          slot: 'baseAddition',
          value: [
            0.055555556, 0.1, 0.14444445, 0.18888889, 0.23333333, 0.2777778, 0.32222223, 0.36666667,
            0.43333334,
          ],
        },
        {
          kind: 'damageScale',
          target: 'ether',
          slot: 'baseAddition',
          value: [
            0.055555556, 0.1, 0.14444445, 0.18888889, 0.23333333, 0.2777778, 0.32222223, 0.36666667,
            0.43333334,
          ],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_magicdam_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'heat',
          slot: 'baseAddition',
          value: [0.12, 0.144, 0.168, 0.192, 0.216, 0.24, 0.264, 0.288, 0.336],
        },
        {
          kind: 'damageScale',
          target: 'electric',
          slot: 'baseAddition',
          value: [0.12, 0.144, 0.168, 0.192, 0.216, 0.24, 0.264, 0.288, 0.336],
        },
        {
          kind: 'damageScale',
          target: 'cryo',
          slot: 'baseAddition',
          value: [0.12, 0.144, 0.168, 0.192, 0.216, 0.24, 0.264, 0.288, 0.336],
        },
        {
          kind: 'damageScale',
          target: 'nature',
          slot: 'baseAddition',
          value: [0.12, 0.144, 0.168, 0.192, 0.216, 0.24, 0.264, 0.288, 0.336],
        },
      ],
      skillId: 'sk_wpn_pistol_0009',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'buffConsumed',
          priority: 0,
          sequence: { $sequence: 'conditional_5' },
        },
        {
          key: 'skill3:event:1:sequence:0',
          abilityEvent: 'buffConsumed',
          priority: 0,
          sequence: { $sequence: 'conditional_10' },
        },
        {
          key: 'skill3:event:2:sequence:0',
          abilityEvent: 'buffConsumed',
          priority: 0,
          sequence: { $sequence: 'conditional_15' },
        },
        {
          key: 'skill3:event:3:sequence:0',
          abilityEvent: 'buffConsumed',
          priority: 0,
          sequence: { $sequence: 'conditional_20' },
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            setGlobalCooldown_1: {
              action: {
                kind: 'setGlobalCooldown',
                parameters: {
                  target: 'caster',
                  markerId: 'buff_wpn_pistol_0009_cd',
                  durationSeconds: { kind: 'valueNode', nodeId: 'data_1' },
                },
              },
              next: null,
            },
            applyBuff_2: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_pistol_0009_dmg_taken_up_f',
                      copiedBlackboardAssignments: {
                        damage_taken_up_fire: 'dmg_taken_up',
                        duration: 'duration',
                        lv: 'lv',
                      },
                    },
                  ],
                  target: 'eventTarget',
                  inheritSourceSkillCastInfo: true,
                },
              },
              next: 'setGlobalCooldown_1',
            },
            applyBuff_3: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_pistol_0009_cd',
                      copiedBlackboardAssignments: { cd: 'cd' },
                    },
                  ],
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                },
              },
              next: 'applyBuff_2',
            },
            conditional_4: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
                whenTrue: { $sequence: 'applyBuff_3' },
              },
              next: null,
            },
            conditional_5: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_4' } },
                whenTrue: { $sequence: 'conditional_4' },
              },
              next: null,
            },
            applyBuff_7: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_pistol_0009_dmg_taken_up_p',
                      copiedBlackboardAssignments: {
                        damage_taken_up_pulse: 'dmg_taken_up',
                        duration: 'duration',
                        lv: 'lv',
                      },
                    },
                  ],
                  target: 'eventTarget',
                  inheritSourceSkillCastInfo: true,
                },
              },
              next: 'setGlobalCooldown_1',
            },
            applyBuff_8: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_pistol_0009_cd',
                      copiedBlackboardAssignments: { cd: 'cd' },
                    },
                  ],
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                },
              },
              next: 'applyBuff_7',
            },
            conditional_9: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_6' } },
                whenTrue: { $sequence: 'applyBuff_8' },
              },
              next: null,
            },
            conditional_10: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_7' } },
                whenTrue: { $sequence: 'conditional_9' },
              },
              next: null,
            },
            applyBuff_12: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_pistol_0009_dmg_taken_up_c',
                      copiedBlackboardAssignments: {
                        damage_taken_up_cryst: 'dmg_taken_up',
                        duration: 'duration',
                        lv: 'lv',
                      },
                    },
                  ],
                  target: 'eventTarget',
                  inheritSourceSkillCastInfo: true,
                },
              },
              next: 'setGlobalCooldown_1',
            },
            applyBuff_13: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_pistol_0009_cd',
                      copiedBlackboardAssignments: { cd: 'cd' },
                    },
                  ],
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                },
              },
              next: 'applyBuff_12',
            },
            conditional_14: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_9' } },
                whenTrue: { $sequence: 'applyBuff_13' },
              },
              next: null,
            },
            conditional_15: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_10' } },
                whenTrue: { $sequence: 'conditional_14' },
              },
              next: null,
            },
            applyBuff_17: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_pistol_0009_dmg_taken_up_n',
                      copiedBlackboardAssignments: {
                        damage_taken_up_natural: 'dmg_taken_up',
                        duration: 'duration',
                        lv: 'lv',
                      },
                    },
                  ],
                  target: 'eventTarget',
                  inheritSourceSkillCastInfo: true,
                },
              },
              next: 'setGlobalCooldown_1',
            },
            applyBuff_18: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_pistol_0009_cd',
                      copiedBlackboardAssignments: { cd: 'cd' },
                    },
                  ],
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                },
              },
              next: 'applyBuff_17',
            },
            conditional_19: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_12' } },
                whenTrue: { $sequence: 'applyBuff_18' },
              },
              next: null,
            },
            conditional_20: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_13' } },
                whenTrue: { $sequence: 'conditional_19' },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: { type: 'number', expression: { kind: 'blackboard', key: 'cd' } },
            data_2: {
              type: 'boolean',
              expression: {
                kind: 'globalCooldownPresent',
                target: 'caster',
                markerId: 'buff_wpn_pistol_0009_cd',
              },
            },
            data_3: {
              type: 'boolean',
              expression: { kind: 'not', condition: { kind: 'conditionNode', nodeId: 'data_2' } },
            },
            data_4: {
              type: 'boolean',
              expression: {
                kind: 'eventBuffTagsMatch',
                match: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellStatus/Burning'],
              },
            },
            data_5: {
              type: 'boolean',
              expression: {
                kind: 'globalCooldownPresent',
                target: 'caster',
                markerId: 'buff_wpn_pistol_0009_cd',
              },
            },
            data_6: {
              type: 'boolean',
              expression: { kind: 'not', condition: { kind: 'conditionNode', nodeId: 'data_5' } },
            },
            data_7: {
              type: 'boolean',
              expression: {
                kind: 'eventBuffTagsMatch',
                match: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellStatus/Conduct'],
              },
            },
            data_8: {
              type: 'boolean',
              expression: {
                kind: 'globalCooldownPresent',
                target: 'caster',
                markerId: 'buff_wpn_pistol_0009_cd',
              },
            },
            data_9: {
              type: 'boolean',
              expression: { kind: 'not', condition: { kind: 'conditionNode', nodeId: 'data_8' } },
            },
            data_10: {
              type: 'boolean',
              expression: {
                kind: 'eventBuffTagsMatch',
                match: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellStatus/Frozen'],
              },
            },
            data_11: {
              type: 'boolean',
              expression: {
                kind: 'globalCooldownPresent',
                target: 'caster',
                markerId: 'buff_wpn_pistol_0009_cd',
              },
            },
            data_12: {
              type: 'boolean',
              expression: { kind: 'not', condition: { kind: 'conditionNode', nodeId: 'data_11' } },
            },
            data_13: {
              type: 'boolean',
              expression: {
                kind: 'eventBuffTagsMatch',
                match: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellStatus/Corrupt'],
              },
            },
          },
        },
        macros: {},
      },
      blackboard: {
        cd: [25, 25, 25, 25, 25, 25, 25, 25, 25],
        dmg_taken_up: [0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.24, 0.28],
        duration: [15, 15, 15, 15, 15, 15, 15, 15, 15],
        lv: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      },
    },
  ],
  assetSlug: 'wpn_pistol_0009',
  icon: 'endaxis:weapons/pistol/wpn_pistol_0009',
  buffDefinitions: {
    buff_wpn_pistol_0009_cd: {
      stackingType: 'unique',
      priority: 0,
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'cd' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: { cd: 0 },
      attributeModifiers: [],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
    buff_wpn_pistol_0009_dmg_taken_up_c: {
      stackingType: 'highPriority',
      priority: { blackboardKey: 'lv' },
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_cryst_taken_up',
        showInHeadBarCommon: true,
        showInHeadBarAttached: false,
        showInSquadIcon: false,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { damage_taken_up_cryst: 0, duration: 0, lv: 0 },
      attributeModifiers: [],
      damageModifiers: [
        {
          enabledSide: 'defender',
          condition: { $sequence: 'conditional_1' },
          processors: [
            {
              kind: 'damageScale',
              side: 'defender',
              zone: 'normal',
              addition: { blackboardKey: 'damage_taken_up_cryst' },
            },
          ],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            conditional_1: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
                whenTrue: { $sequence: null },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: { kind: 'eventDamageTypeIn', damageTypes: ['cryo'] },
            },
          },
        },
        macros: {},
      },
    },
    buff_wpn_pistol_0009_dmg_taken_up_f: {
      stackingType: 'highPriority',
      priority: { blackboardKey: 'lv' },
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_fire_taken_up',
        showInHeadBarCommon: true,
        showInHeadBarAttached: false,
        showInSquadIcon: false,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { damage_taken_up_fire: 0, duration: 0, lv: 0 },
      attributeModifiers: [],
      damageModifiers: [
        {
          enabledSide: 'defender',
          condition: { $sequence: 'conditional_1' },
          processors: [
            {
              kind: 'damageScale',
              side: 'defender',
              zone: 'normal',
              addition: { blackboardKey: 'damage_taken_up_fire' },
            },
          ],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            conditional_1: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
                whenTrue: { $sequence: null },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: { kind: 'eventDamageTypeIn', damageTypes: ['heat'] },
            },
          },
        },
        macros: {},
      },
    },
    buff_wpn_pistol_0009_dmg_taken_up_n: {
      stackingType: 'highPriority',
      priority: { blackboardKey: 'lv' },
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_nature_taken_up',
        showInHeadBarCommon: true,
        showInHeadBarAttached: false,
        showInSquadIcon: false,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { damage_taken_up_natural: 0, duration: 0, lv: 0 },
      attributeModifiers: [],
      damageModifiers: [
        {
          enabledSide: 'defender',
          condition: { $sequence: 'conditional_1' },
          processors: [
            {
              kind: 'damageScale',
              side: 'defender',
              zone: 'normal',
              addition: { blackboardKey: 'damage_taken_up_natural' },
            },
          ],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            conditional_1: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
                whenTrue: { $sequence: null },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: { kind: 'eventDamageTypeIn', damageTypes: ['nature'] },
            },
          },
        },
        macros: {},
      },
    },
    buff_wpn_pistol_0009_dmg_taken_up_p: {
      stackingType: 'highPriority',
      priority: { blackboardKey: 'lv' },
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_pulse_taken_up',
        showInHeadBarCommon: true,
        showInHeadBarAttached: false,
        showInSquadIcon: false,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { damage_taken_up_pulse: 0, duration: 0, lv: 0 },
      attributeModifiers: [],
      damageModifiers: [
        {
          enabledSide: 'defender',
          condition: { $sequence: 'conditional_1' },
          processors: [
            {
              kind: 'damageScale',
              side: 'defender',
              zone: 'normal',
              addition: { blackboardKey: 'damage_taken_up_pulse' },
            },
          ],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            conditional_1: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
                whenTrue: { $sequence: null },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: { kind: 'eventDamageTypeIn', damageTypes: ['electric'] },
            },
          },
        },
        macros: {},
      },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
