import type { CompiledEquipmentSuitRuntimeBatchSource } from './suitRuntimeDefinition.ts';

export interface RenderedEquipmentSuitDefinitionFileSource {
  readonly relativePath: string;
  readonly content: string;
}

const SAFE_IDENTITY = /^[A-Za-z0-9_-]+$/;

/** 把已经闭合的套装运行时定义稳定渲染为 Next GearSetDefinition 模块。 */
export function renderEquipmentSuitDefinitionFiles(
  batch: CompiledEquipmentSuitRuntimeBatchSource,
): readonly RenderedEquipmentSuitDefinitionFileSource[] {
  const blocked = batch.diagnostics.filter(item => item.status === 'blocked');
  if (blocked.length > 0) {
    throw new Error(
      `cannot render equipment suit definitions with ${blocked.length} blocked diagnostics`,
    );
  }
  const definitions = [...batch.definitions].sort((left, right) =>
    left.slug.localeCompare(right.slug),
  );
  const seen = new Set<string>();
  const files: RenderedEquipmentSuitDefinitionFileSource[] = [];
  const imports: string[] = [];
  for (const [index, definition] of definitions.entries()) {
    if (!SAFE_IDENTITY.test(definition.slug))
      throw new Error(
        `gear set '${definition.slug}'.slug: expected a filesystem-safe stable identity`,
      );
    if (seen.has(definition.slug))
      throw new Error(`duplicate rendered gear set definition ${JSON.stringify(definition.slug)}`);
    seen.add(definition.slug);
    imports.push(`import generatedGearSet${index} from './${definition.slug}.generated';`);
    files.push({
      relativePath: `${definition.slug}.generated.ts`,
      content: `/** Generated by the Endaxis game-data compiler. Do not edit. */\nimport type { GearSetDefinition } from '../../../core/game-data/equipmentDefinition';\n\nconst definition = ${JSON.stringify(definition, null, 2)} as const satisfies GearSetDefinition;\n\nexport default definition;\n`,
    });
  }
  files.push({
    relativePath: 'index.generated.ts',
    content: `${imports.join('\n')}\n\nimport type { GearSetDefinition } from '../../../core/game-data/equipmentDefinition';\n\nexport const generatedGearSetDefinitions = [\n${definitions.map((_, index) => `  generatedGearSet${index},`).join('\n')}\n] as const satisfies readonly GearSetDefinition[];\n`,
  });
  files.push({
    relativePath: 'gear-set-definitions.audit.json',
    content: `${JSON.stringify(
      {
        format: 'EndaxisGeneratedGearSetAudit',
        version: 1,
        definitionCount: definitions.length,
        buffDefinitionCount: definitions.reduce(
          (total, item) => total + Object.keys(item.buffDefinitions ?? {}).length,
          0,
        ),
        diagnostics: batch.diagnostics,
      },
      null,
      2,
    )}\n`,
  });
  return files.sort((left, right) => left.relativePath.localeCompare(right.relativePath));
}
