import type {
  CompiledEquipmentDefinitionBatchSource,
  CompiledGearDefinitionSource,
} from './formalDefinition.ts';

export interface RenderedEquipmentDefinitionFileSource {
  readonly relativePath: string;
  readonly content: string;
}

const SAFE_PATH_SEGMENT = /^[A-Za-z0-9_-]+$/;

/**
 * 只负责稳定渲染已经完成语义编译的定义，不重新解释装备规则。
 * 输出按原生套装身份分目录；无套装装备进入显式 `_standalone` 目录。
 */
export function renderEquipmentDefinitionFiles(
  batch: CompiledEquipmentDefinitionBatchSource,
): readonly RenderedEquipmentDefinitionFileSource[] {
  const blocked = batch.diagnostics.filter(diagnostic => diagnostic.status === 'blocked');
  if (blocked.length > 0) {
    throw new Error(
      `cannot render equipment definitions with ${blocked.length} blocked diagnostics`,
    );
  }

  const definitions = [...batch.definitions].sort((left, right) =>
    left.slug.localeCompare(right.slug),
  );
  const seen = new Set<string>();
  const files: RenderedEquipmentDefinitionFileSource[] = [];
  const imports: string[] = [];
  for (const [index, definition] of definitions.entries()) {
    requireSafeSegment(definition.slug, `gear definition '${definition.slug}'.slug`);
    if (seen.has(definition.slug)) {
      throw new Error(`duplicate rendered gear definition ${JSON.stringify(definition.slug)}`);
    }
    seen.add(definition.slug);
    const directory = definition.gearSetSlug ?? '_standalone';
    requireSafeSegment(directory, `gear definition '${definition.slug}'.gearSetSlug`);
    const exportName = `generatedGear${index}`;
    const modulePath = `./${directory}/${definition.slug}.generated`;
    imports.push(`import ${exportName} from '${modulePath}';`);
    files.push({
      relativePath: `${directory}/${definition.slug}.generated.ts`,
      content: renderDefinition(definition),
    });
  }

  files.push({
    relativePath: 'index.generated.ts',
    content: `${imports.join('\n')}\n\nimport type { GearDefinition } from '../../../core/game-data/equipmentDefinition';\n\nexport const generatedGearDefinitions = [\n${definitions
      .map((_, index) => `  generatedGear${index},`)
      .join('\n')}\n] as const satisfies readonly GearDefinition[];\n`,
  });
  return files.sort((left, right) => left.relativePath.localeCompare(right.relativePath));
}

function renderDefinition(definition: CompiledGearDefinitionSource): string {
  return `/** Generated by the Endaxis game-data compiler. Do not edit. */\nimport type { GearDefinition } from '../../../../core/game-data/equipmentDefinition';\n\nconst definition = ${JSON.stringify(
    definition,
    null,
    2,
  )} as const satisfies GearDefinition;\n\nexport default definition;\n`;
}

function requireSafeSegment(value: string, path: string): void {
  if (!SAFE_PATH_SEGMENT.test(value)) {
    throw new Error(`${path}: expected a filesystem-safe stable identity`);
  }
}
