/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { GearSetDefinition } from '../../../core/game-data/equipmentDefinition';

const definition = {
  slug: 'suit_heal01',
  modifiers: [
    {
      kind: 'staticHealingIncrease',
      target: 'output',
      value: [0.2],
    },
  ],
  buffDefinitions: {
    buff_common_dmgtk_down_equip_1: {
      stackingType: 'highPriority',
      priority: {
        blackboardKey: 'priority',
      },
      maxStackCount: 1,
      durationSeconds: {
        blackboardKey: 'duration',
      },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 0,
      presentation: {
        visible: true,
        iconId: 'icon_battle_buff_def_up',
        iconPath: '/icons/icon_battle_buff_def_up.webp',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: {
          useDirectoryValue: false,
          value: 0,
          category: 'CommonCharBuff',
        },
      },
      applyTagIds: [],
      extendTagIds: [],
      blackboard: {
        duration: 0,
        priority: 0,
        value: 0,
      },
      attributeModifiers: [
        {
          attribute: 'PhysicalDamageTakenScalar',
          slot: 'baseFinalMultiplier',
          value: {
            blackboardKey: 'value',
          },
        },
        {
          attribute: 'FireDamageTakenScalar',
          slot: 'baseFinalMultiplier',
          value: {
            blackboardKey: 'value',
          },
        },
        {
          attribute: 'PulseDamageTakenScalar',
          slot: 'baseFinalMultiplier',
          value: {
            blackboardKey: 'value',
          },
        },
        {
          attribute: 'CrystDamageTakenScalar',
          slot: 'baseFinalMultiplier',
          value: {
            blackboardKey: 'value',
          },
        },
        {
          attribute: 'EtherDamageTakenScalar',
          slot: 'baseFinalMultiplier',
          value: {
            blackboardKey: 'value',
          },
        },
        {
          attribute: 'NaturalDamageTakenScalar',
          slot: 'baseFinalMultiplier',
          value: {
            blackboardKey: 'value',
          },
        },
      ],
    },
    buff_equipsuit_healup_01: {
      stackingType: 'unlimited',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTagIds: [],
      extendTagIds: [],
      blackboard: {
        dmg_taken_down: -0.2,
        dmg_taken_down2: -0.4,
        duration: 0,
      },
      attributeModifiers: [],
      abilityEventResponses: [
        {
          event: 'outputHeal',
          priority: 0,
          sequence: {
            steps: [
              {
                kind: 'conditional',
                parameters: {
                  condition: {
                    kind: 'eventOverheal',
                  },
                },
                whenTrue: {
                  steps: [
                    {
                      kind: 'applyBuff',
                      parameters: {
                        buffId: 'buff_common_dmgtk_down_equip_1',
                        target: 'eventTarget',
                        inheritSourceSkillCastInfo: true,
                        blackboardAssignments: {
                          value: {
                            kind: 'blackboard',
                            key: 'dmg_taken_down2',
                          },
                          duration: {
                            kind: 'blackboard',
                            key: 'duration',
                          },
                          priority: {
                            kind: 'constant',
                            value: 1,
                          },
                        },
                      },
                    },
                  ],
                },
              },
              {
                kind: 'conditional',
                parameters: {
                  condition: {
                    kind: 'not',
                    condition: {
                      kind: 'eventOverheal',
                    },
                  },
                },
                whenTrue: {
                  steps: [
                    {
                      kind: 'applyBuff',
                      parameters: {
                        buffId: 'buff_common_dmgtk_down_equip_1',
                        target: 'eventTarget',
                        inheritSourceSkillCastInfo: true,
                        blackboardAssignments: {
                          value: {
                            kind: 'blackboard',
                            key: 'dmg_taken_down',
                          },
                          duration: {
                            kind: 'blackboard',
                            key: 'duration',
                          },
                          priority: {
                            kind: 'constant',
                            value: 0,
                          },
                        },
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
    },
  },
  initializationSequence: {
    steps: [
      {
        kind: 'applyBuff',
        parameters: {
          buffId: 'buff_equipsuit_healup_01',
          target: 'caster',
          blackboardAssignments: {
            dmg_taken_down: {
              kind: 'constant',
              value: 0.85,
            },
            dmg_taken_down2: {
              kind: 'constant',
              value: 0.7,
            },
            duration: {
              kind: 'constant',
              value: 10,
            },
          },
        },
      },
    ],
  },
} as const satisfies GearSetDefinition;

export default definition;
