/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { GearSetDefinition } from '../../../core/game-data/equipmentDefinition';

const definition = {
  slug: 'suit_generaltype',
  modifiers: [
    {
      kind: 'panelStat',
      stat: 'ultimateEnergyGainEfficiency',
      value: [0.1],
    },
    {
      kind: 'damageScale',
      target: 'physical',
      value: [0.2],
    },
    {
      kind: 'damageScale',
      target: 'electric',
      value: [0.2],
    },
    {
      kind: 'damageScale',
      target: 'nature',
      value: [0.2],
    },
    {
      kind: 'damageScale',
      target: 'cryo',
      value: [0.2],
    },
    {
      kind: 'damageScale',
      target: 'heat',
      value: [0.2],
    },
    {
      kind: 'damageScale',
      target: 'ether',
      value: [0.2],
    },
  ],
} as const satisfies GearSetDefinition;

export default definition;
