/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { GearSetDefinition } from '../../../core/game-data/equipmentDefinition';

const definition = {
  slug: 'suit_atb01',
  modifiers: [
    {
      kind: 'skillCooldownMultiplier',
      skillTypes: 'comboSkill',
      value: 0.8500000238418579,
    },
  ],
  buffDefinitions: {
    buff_equipsuit_combosuit_01: {
      stackingType: 'unique',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: {
        cd: 30,
        comboskill_cooldown: 0.1,
        dmg_up: 0.2,
        duration: 12,
      },
      attributeModifiers: [],
      abilityEventResponses: [
        {
          event: 'skillSpGained',
          priority: 0,
          sequence: {
            steps: [
              {
                kind: 'conditional',
                parameters: {
                  condition: {
                    kind: 'eventSpGainMatch',
                    sources: ['skill'],
                    gainKinds: ['gain'],
                  },
                },
                whenTrue: {
                  steps: [
                    {
                      kind: 'applyBuff',
                      parameters: {
                        buffId: 'buff_equipsuit_combosuit_01_adddamage',
                        target: 'party',
                        source: 'buffOwner',
                        inheritSourceSkillCastInfo: true,
                        asChildBuff: true,
                        blackboardAssignments: {
                          dmg_up: {
                            kind: 'blackboard',
                            key: 'dmg_up',
                          },
                          duration: {
                            kind: 'blackboard',
                            key: 'duration',
                          },
                        },
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
    },
    buff_equipsuit_combosuit_01_adddamage: {
      stackingType: 'stack',
      priority: 0,
      maxStackCount: 1,
      durationSeconds: {
        blackboardKey: 'duration',
      },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        iconId: 'icon_battle_buff_atk_up',
        iconPath: '/icons/icon_battle_buff_atk_up.webp',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showDirectlyInHeadBuff: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: {
          useDirectoryValue: false,
          value: 0,
          category: 'CommonCharBuff',
        },
      },
      applyTags: [],
      extendTags: [],
      blackboard: {
        cd: 30,
        dmg_up: 0.2,
        duration: 12,
      },
      attributeModifiers: [],
      damageModifiers: [
        {
          enabledSide: 'attacker',
          processors: [
            {
              kind: 'damageScale',
              side: 'attacker',
              zone: 'normal',
              addition: {
                blackboardKey: 'dmg_up',
              },
            },
          ],
        },
      ],
    },
  },
  initializationSequence: {
    steps: [
      {
        kind: 'applyBuff',
        parameters: {
          buffId: 'buff_equipsuit_combosuit_01',
          target: 'caster',
          blackboardAssignments: {
            dmg_up: {
              kind: 'constant',
              value: 0.1599999964237213,
            },
            duration: {
              kind: 'constant',
              value: 15,
            },
            cd: {
              kind: 'constant',
              value: 0,
            },
            comboskill_cooldown: {
              kind: 'constant',
              value: 0.8500000238418579,
            },
          },
        },
      },
    ],
  },
} as const satisfies GearSetDefinition;

export default definition;
