import { format } from 'prettier';
import { readdir, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { imageRefFromPath } from '../src/compiler/publication/imageResources.ts';
import { fileURLToPath } from 'node:url';

export async function generateImageCatalog(
  projectRoot = fileURLToPath(new URL('../../../', import.meta.url)),
  publicRoot = path.join(projectRoot, 'public'),
) {
  const entries: { ref: ReturnType<typeof imageRefFromPath>; path: string; category: string }[] =
    [];
  async function scan(directory: string) {
    const children = await readdir(path.join(publicRoot, directory), {
      withFileTypes: true,
    }).catch((error: NodeJS.ErrnoException) => {
      if (error.code === 'ENOENT') return [];
      throw error;
    });
    for (const entry of children) {
      const relative = `${directory}/${entry.name}`;
      if (entry.isDirectory()) await scan(relative);
      else if (entry.name.endsWith('.webp')) {
        const publicPath = `/${relative}`;
        entries.push({
          ref: imageRefFromPath(publicPath),
          path: publicPath,
          category: directory.split('/')[0]!,
        });
      }
    }
  }
  for (const directory of [
    'operators',
    'icons',
    'weapons',
    'equipment',
    'enemies',
    'consumables',
    'contingency_contract',
  ])
    await scan(directory);
  entries.sort((a, b) => a.path.localeCompare(b.path, 'en'));
  const ids = new Set<string>();
  for (const entry of entries) {
    if (ids.has(entry.ref)) throw new Error(`Duplicate image ID: ${entry.ref}`);
    ids.add(entry.ref);
  }
  const text = `/** Generated by generateImageCatalog.ts. Do not edit. */\nimport type { ImageRef } from '../packages/game-data-contract/src/images';\nexport const imageCatalog: readonly { readonly ref: ImageRef; readonly path: string; readonly category: string }[] = ${JSON.stringify(entries, null, 2)};\n`;
  await mkdir(path.join(projectRoot, 'src'), { recursive: true });
  await writeFile(
    path.join(projectRoot, 'src/imageCatalog.generated.ts'),
    await format(text, { parser: 'typescript', singleQuote: true }),
  );
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  await generateImageCatalog();
