import type { AbilityEvent } from '../../../../../packages/game-data-contract/src/abilityEvents';

/** Display terminology only; availability and event targets remain runtime responsibilities. */
export const abilityEventLabelsZh = {
  enterFight: '进入战斗',
  ownerSwitchToCenter: '持有者切入主控',
  ownerSwitchToGuard: '持有者切为支援',
  ownerHpZero: '持有者生命归零',
  abilityEntitySpawned: '能力实体生成',
  abilityEntityFinished: '能力实体结束',
  projectileLaunched: '投射物发射',
  beforeTakeDamage: '受到伤害前',
  beforeCalculateDamage: '伤害计算前',
  beforeDamageAction: '伤害动作前',
  beforeOutputDamage: '造成伤害前',
  beforeTakePhysicalInfliction: '受到物理异常前',
  afterTakePhysicalInfliction: '受到物理异常后',
  beforeOutputPhysicalInfliction: '施加物理异常前',
  afterOutputPhysicalInfliction: '施加物理异常后',
  beforeOutputKnockDown: '造成倒地前',
  afterOutputKnockDown: '造成倒地后',
  outputKnockDown: '造成倒地',
  beforeOutputInfliction: '施加异常前',
  afterOutputInfliction: '施加异常后',
  beforeOutputSpellBurst: '造成法术爆发前',
  beforeTakeSpellInfliction: '受到法术异常前',
  beforeTakeInfliction: '受到异常前',
  afterTakeInfliction: '受到异常后',
  takeDamage: '受到伤害',
  takeCriticalDamage: '受到暴击伤害',
  outputDamage: '造成伤害',
  outputCriticalDamage: '造成暴击伤害',
  outputHeal: '施加治疗',
  receiveHeal: '接受治疗',
  afterAddedShield: '获得护盾后',
  poiseZero: '进入失衡（原生韧性归零）',
  poiseKnotBreak: '失衡节点突破',
  beforeCastSkill: '释放技能前',
  afterSkillApplyCost: '技能扣费后',
  skillEnd: '技能结束',
  beforeOutputBuff: '施加 Buff 前',
  beforeAddedBuff: '获得 Buff 前',
  outputBuff: '施加 Buff',
  addedBuff: '获得 Buff',
  finishedBuff: 'Buff 结束',
  buffEndsEarly: 'Buff 提前结束',
  buffEnhanceChanged: 'Buff 强化状态变化',
  afterOutputWeaknessTriggered: '触发弱点后',
  weaknessSet: '设置弱点',
  customAbilityEvent: '自定义能力事件',
  afterKillEntity: '击杀实体后',
  buffConsumed: 'Buff 被消耗',
  buffAbsorbed: 'Buff 被吸收',
  skillSpGained: '技能 SP 增加',
} satisfies Record<AbilityEvent, string>;

export function abilityEventDisplayLabel(event: string, locale: string): string {
  if (!locale.toLowerCase().startsWith('zh') || !Object.hasOwn(abilityEventLabelsZh, event))
    return event;
  return `${abilityEventLabelsZh[event as AbilityEvent]} · ${event}`;
}
