/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_sword_0016',
  rarity: 6,
  weaponType: 'sword',
  baseAttackAtLevelNodes: [51, 146, 247, 348, 449, 500],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'will',
          operation: 'flat',
          value: [20, 36, 52, 68, 84, 100, 116, 132, 156],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_will_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'attackPercent',
          value: [0.05, 0.09, 0.13, 0.17, 0.21, 0.25, 0.29, 0.33, 0.39],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_atk_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'physical',
          slot: 'baseAddition',
          value: [0.16, 0.192, 0.224, 0.256, 0.288, 0.32, 0.352, 0.384, 0.448],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_sword_0016_valid',
                      copiedBlackboardAssignments: {
                        pd_up: 'phy_dmg_up3',
                        duration: 'duration',
                        max_stack: 'max_stack',
                      },
                    },
                  ],
                  target: 'currentTarget',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: null,
            },
            createTimedMarker_2: {
              action: {
                kind: 'createTimedMarker',
                parameters: {
                  target: 'caster',
                  markerId: 'wpn_sword_0016',
                  durationSeconds: { kind: 'valueNode', nodeId: 'data_1' },
                  autoFinishByAction: false,
                },
              },
              next: null,
            },
            forEachContextTarget_3: {
              action: {
                kind: 'forEachContextTarget',
                parameters: { targets: { kind: 'characterTeam', excludeOwner: true } },
                body: { $sequence: 'applyBuff_1' },
              },
              next: 'createTimedMarker_2',
            },
            applyBuff_4: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_sword_0016_valid',
                      copiedBlackboardAssignments: {
                        pd_up: 'phy_dmg_up2',
                        duration: 'duration',
                        max_stack: 'max_stack',
                      },
                    },
                  ],
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: 'forEachContextTarget_3',
            },
            checkCondition_5: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
              },
              next: 'applyBuff_4',
            },
            checkCondition_6: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_4' } },
              },
              next: 'checkCondition_5',
            },
            applyBuff_7: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_sword_0016',
                      blackboardAssignments: {
                        phy_dmg_up: { kind: 'valueNode', nodeId: 'data_5' },
                      },
                    },
                  ],
                  target: 'caster',
                },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: { type: 'number', expression: { kind: 'blackboard', key: 'cd' } },
            data_2: {
              type: 'boolean',
              expression: {
                kind: 'timedMarkerPresent',
                target: 'caster',
                markerId: 'wpn_sword_0016',
              },
            },
            data_3: {
              type: 'boolean',
              expression: { kind: 'not', condition: { kind: 'conditionNode', nodeId: 'data_2' } },
            },
            data_4: {
              type: 'boolean',
              expression: { kind: 'eventSpGainMatch', sources: ['skill'], gainKinds: ['gain'] },
            },
            data_5: {
              type: 'number',
              expression: { kind: 'blackboard', key: 'install_0_phy_dmg_up' },
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_sword_0016',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'skillSpGained',
          priority: 0,
          sequence: { $sequence: 'checkCondition_6' },
        },
      ],
      enableSequence: { $sequence: 'applyBuff_7' },
      blackboard: {
        cd: 0.1,
        duration: [30, 30, 30, 30, 30, 30, 30, 30, 30],
        max_stack: [5, 5, 5, 5, 5, 5, 5, 5, 5],
        phy_dmg_up2: [0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.14],
        phy_dmg_up3: [0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055, 0.06, 0.07],
        install_0_phy_dmg_up: [0.16, 0.192, 0.224, 0.256, 0.288, 0.32, 0.352, 0.384, 0.448],
      },
    },
  ],
  assetSlug: 'wpn_sword_0016',
  icon: 'endaxis:weapons/sword/wpn_sword_0016',
  buffDefinitions: {
    buff_wpn_sword_0016: {
      stackingType: 'unique',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: { phy_dmg_up: 0.1 },
      attributeModifiers: [],
      lifecycleSequences: { start: { $sequence: 'finishBuffsById_1' } },
      actionGraph: {
        main: {
          nodes: {
            finishBuffsById_1: {
              action: {
                kind: 'finishBuffsById',
                parameters: {
                  target: 'buffOwner',
                  buffIds: ['buff_wpn_sword_0016_team'],
                  reason: 'other',
                },
              },
              next: null,
            },
          },
        },
        macros: {},
      },
    },
    buff_wpn_sword_0016_valid: {
      stackingType: 'highPriorityWithMaxStack',
      priority: { blackboardKey: 'pd_up' },
      maxStackCount: { blackboardKey: 'max_stack' },
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_physical_dmg_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 0, max_stack: 0, pd_up: 0.1 },
      attributeModifiers: [
        {
          attribute: 'physicalDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'pd_up' },
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
