/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_sword_0011',
  rarity: 6,
  weaponType: 'sword',
  baseAttackAtLevelNodes: [50, 145, 245, 345, 445, 495],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'main',
          operation: 'flat',
          value: [17, 30, 44, 57, 71, 85, 98, 112, 132],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_main_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'criticalRate',
          value: [0.025, 0.045, 0.065, 0.085, 0.105, 0.125, 0.145, 0.165, 0.195],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_crirate_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_wpn_sword_0011',
                  target: 'caster',
                  blackboardAssignments: {
                    dmg_up: { kind: 'valueNode', nodeId: 'data_1' },
                    phy_dmg_up: { kind: 'valueNode', nodeId: 'data_2' },
                  },
                },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: { type: 'number', expression: { kind: 'blackboard', key: 'install_0_dmg_up' } },
            data_2: {
              type: 'number',
              expression: { kind: 'blackboard', key: 'install_0_phy_dmg_up' },
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_sword_0011',
      enableSequence: { $sequence: 'applyBuff_1' },
      blackboard: {
        install_0_dmg_up: [0.35, 0.42, 0.49, 0.56, 0.63, 0.7, 0.77, 0.84, 0.98],
        install_0_phy_dmg_up: [0.15, 0.18, 0.21, 0.24, 0.27, 0.3, 0.33, 0.36, 0.42],
      },
    },
  ],
  assetSlug: 'wpn_sword_0011',
  icon: 'endaxis:weapons/sword/wpn_sword_0011',
  buffDefinitions: {
    buff_wpn_sword_0011: {
      stackingType: 'unique',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_buff_atk_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: false,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { dmg_up: 0, phy_dmg_up: 0 },
      attributeModifiers: [],
      damageModifiers: [
        {
          enabledSide: 'attacker',
          condition: { $sequence: 'conditional_2' },
          processors: [
            {
              kind: 'damageScale',
              side: 'attacker',
              zone: 'normal',
              addition: { blackboardKey: 'phy_dmg_up' },
            },
          ],
        },
        {
          enabledSide: 'attacker',
          condition: { $sequence: 'conditional_3' },
          processors: [
            {
              kind: 'damageScale',
              side: 'attacker',
              zone: 'normal',
              addition: { blackboardKey: 'dmg_up' },
            },
          ],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            conditional_1: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
                whenTrue: { $sequence: null },
              },
              next: null,
            },
            conditional_2: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_2' } },
                whenTrue: { $sequence: 'conditional_1' },
              },
              next: null,
            },
            conditional_3: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
                whenTrue: { $sequence: null },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: { kind: 'eventDamageTypeIn', damageTypes: ['physical'] },
            },
            data_2: {
              type: 'boolean',
              expression: {
                kind: 'eventDamageTagsMatch',
                match: 'hasAny',
                tags: ['normalSkill', 'ultimateSkill'],
              },
            },
            data_3: {
              type: 'boolean',
              expression: {
                kind: 'poiseCompare',
                target: 'currentTarget',
                returnValueIfMissing: false,
                operator: 'lessOrEqual',
                value: { kind: 'constant', value: 0 },
              },
            },
          },
        },
        macros: {},
      },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
