/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_sword_0018',
  rarity: 5,
  weaponType: 'sword',
  baseAttackAtLevelNodes: [42, 120, 203, 286, 369, 411],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'agility',
          operation: 'flat',
          value: [16, 28, 41, 54, 67, 80, 92, 105, 124],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_agi_mid',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'attackPercent',
          value: [0.04, 0.072, 0.104, 0.136, 0.168, 0.2, 0.232, 0.264, 0.312],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_atk_mid',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'secondary',
          operation: 'percent',
          value: [0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.14],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_sword_0018_atk_up',
                      copiedBlackboardAssignments: {
                        atk_up: 'atk_up',
                        duration: 'duration',
                        max_stack: 'max_stack',
                      },
                    },
                  ],
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: null,
            },
            conditional_2: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
                whenTrue: { $sequence: 'applyBuff_1' },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: {
                kind: 'eventBuffTagsMatch',
                match: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellStatus'],
              },
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_sword_0018',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'buffConsumed',
          priority: 0,
          sequence: { $sequence: 'conditional_2' },
        },
      ],
      blackboard: {
        atk_up: [0.075, 0.09, 0.105, 0.12, 0.135, 0.15, 0.165, 0.18, 0.21],
        duration: [20, 20, 20, 20, 20, 20, 20, 20, 20],
        max_stack: [2, 2, 2, 2, 2, 2, 2, 2, 2],
      },
    },
  ],
  assetSlug: 'wpn_sword_0018',
  icon: 'endaxis:weapons/sword/wpn_sword_0018',
  buffDefinitions: {
    buff_wpn_sword_0018_atk_up: {
      stackingType: 'stack',
      priority: 0,
      maxStackCount: { blackboardKey: 'max_stack' },
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_buff_atk_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { atk_up: 0, duration: 0, max_stack: 0 },
      attributeModifiers: [
        { attribute: 'Atk', slot: 'baseMultiplier', value: { blackboardKey: 'atk_up' } },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
