/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_sword_0026',
  rarity: 6,
  weaponType: 'sword',
  baseAttackAtLevelNodes: [51, 146, 247, 348, 449, 500],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'main',
          operation: 'flat',
          value: [17, 30, 44, 57, 71, 85, 98, 112, 132],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_main_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        { kind: 'panelStat', stat: 'artsIntensity', value: [10, 18, 26, 34, 42, 50, 58, 66, 78] },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_phy_spell_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_wpn_sword_0026_celebration',
                  target: 'party',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                  copiedBlackboardAssignments: {
                    dmg_up: 'dmg_up',
                    phy_spell_up: 'phy_spell_up',
                    def_up: 'def_up',
                    duration: 'duration',
                    hp_up: 'hp_up_c',
                  },
                },
              },
              next: null,
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_sword_0026',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'enterFight',
          priority: 0,
          sequence: { $sequence: 'applyBuff_1' },
        },
      ],
      blackboard: {
        def_up: [0.03, 0.036, 0.042, 0.048, 0.054, 0.06, 0.066, 0.072, 0.084],
        dmg_up: [0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.14],
        duration: [20, 20, 20, 20, 20, 20, 20, 20, 20],
        hp_up_c: [122, 122, 122, 122, 122, 122, 122, 122, 122],
        phy_spell_up: [10, 12, 14, 16, 18, 20, 22, 24, 28],
      },
    },
  ],
  assetSlug: 'wpn_sword_0026',
  icon: 'endaxis:weapons/sword/wpn_sword_0026',
  buffDefinitions: {
    buff_wpn_sword_0026_celebration: {
      stackingType: 'highPriority',
      priority: { blackboardKey: 'dmg_up' },
      maxStackCount: 1,
      durationSeconds: { blackboardKey: 'duration' },
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_buff_wpn_sword_0026',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { def_up: 0, dmg_up: 0, duration: 0, hp_up: 0, phy_spell_up: 0 },
      attributeModifiers: [
        {
          attribute: 'physicalDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'dmg_up' },
        },
        {
          attribute: 'heatDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'dmg_up' },
        },
        {
          attribute: 'electricDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'dmg_up' },
        },
        {
          attribute: 'cryoDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'dmg_up' },
        },
        {
          attribute: 'natureDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'dmg_up' },
        },
        {
          attribute: 'PhysicalAndSpellInflictionEnhance',
          slot: 'baseAddition',
          value: { blackboardKey: 'phy_spell_up' },
        },
        { attribute: 'Def', slot: 'baseMultiplier', value: { blackboardKey: 'def_up' } },
      ],
      lifecycleSequences: { finish: { $sequence: 'conditional_3' } },
      actionGraph: {
        main: {
          nodes: {
            createTimedMarker_1: {
              action: {
                kind: 'createTimedMarker',
                parameters: {
                  target: 'buffOwner',
                  markerId: 'wpn_sword_0026_heal',
                  durationSeconds: { kind: 'constant', value: 0.1 },
                  autoFinishByAction: false,
                },
              },
              next: null,
            },
            heal_2: {
              action: {
                kind: 'heal',
                parameters: {
                  target: 'buffOwner',
                  alwaysNext: true,
                  tags: [],
                  amount: { kind: 'valueNode', nodeId: 'data_1' },
                },
              },
              next: 'createTimedMarker_1',
            },
            conditional_3: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
                whenTrue: { $sequence: 'heal_2' },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: { type: 'number', expression: { kind: 'blackboard', key: 'hp_up' } },
            data_2: {
              type: 'boolean',
              expression: {
                kind: 'timedMarkerPresent',
                target: 'buffOwner',
                markerId: 'wpn_sword_0026_heal',
              },
            },
            data_3: {
              type: 'boolean',
              expression: { kind: 'not', condition: { kind: 'conditionNode', nodeId: 'data_2' } },
            },
          },
        },
        macros: {},
      },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
