/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_pistol_0006",
  "rarity": 5,
  "weaponType": "handcannon",
  "baseAttackAtLevelNodes": [
    42,
    120,
    203,
    286,
    369,
    411
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "agility",
          "operation": "flat",
          "value": [
            16,
            28,
            41,
            54,
            67,
            80,
            92,
            105,
            124
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_pistol_0006_atk_up_up": {
          "stackingType": "stack",
          "priority": 0,
          "maxStackCount": 2,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_atk_up",
            "iconPath": "/icons/icon_battle_buff_atk_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "atk_up": 0,
            "duration": 0,
            "max_stack": 0
          },
          "attributeModifiers": [
            {
              "attribute": "Atk",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "atk_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "cryo",
          "slot": "baseAddition",
          "value": [
            0.04444444552063942,
            0.07999999821186066,
            0.11555555462837219,
            0.15111111104488373,
            0.18666666746139526,
            0.2222222238779068,
            0.25777778029441833,
            0.2933333218097687,
            0.3466666638851166
          ]
        },
        {
          "kind": "damageScale",
          "target": "heat",
          "slot": "baseAddition",
          "value": [
            0.04444444552063942,
            0.07999999821186066,
            0.11555555462837219,
            0.15111111104488373,
            0.18666666746139526,
            0.2222222238779068,
            0.25777778029441833,
            0.2933333218097687,
            0.3466666638851166
          ]
        },
        {
          "kind": "damageScale",
          "target": "electric",
          "slot": "baseAddition",
          "value": [
            0.04444444552063942,
            0.07999999821186066,
            0.11555555462837219,
            0.15111111104488373,
            0.18666666746139526,
            0.2222222238779068,
            0.25777778029441833,
            0.2933333218097687,
            0.3466666638851166
          ]
        },
        {
          "kind": "damageScale",
          "target": "nature",
          "slot": "baseAddition",
          "value": [
            0.04444444552063942,
            0.07999999821186066,
            0.11555555462837219,
            0.15111111104488373,
            0.18666666746139526,
            0.2222222238779068,
            0.25777778029441833,
            0.2933333218097687,
            0.3466666638851166
          ]
        },
        {
          "kind": "damageScale",
          "target": "ether",
          "slot": "baseAddition",
          "value": [
            0.04444444552063942,
            0.07999999821186066,
            0.11555555462837219,
            0.15111111104488373,
            0.18666666746139526,
            0.2222222238779068,
            0.25777778029441833,
            0.2933333218097687,
            0.3466666638851166
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "criticalRate",
          "value": [
            0.029999999329447746,
            0.035999998450279236,
            0.041999999433755875,
            0.04800000041723251,
            0.05400000140070915,
            0.05999999865889549,
            0.06599999964237213,
            0.07199999690055847,
            0.08399999886751175
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeOutputBuff",
          "priority": 0,
          "blackboard": {
            "atk_up": [
              0.07500000298023224,
              0.09000000357627869,
              0.10499999672174454,
              0.11999999731779099,
              0.13500000536441803,
              0.15000000596046448,
              0.16500000655651093,
              0.18000000715255737,
              0.20999999344348907
            ],
            "cd": [
              0.10000000149011612,
              0.10000000149011612,
              0.10000000149011612,
              0.10000000149011612,
              0.10000000149011612,
              0.10000000149011612,
              0.10000000149011612,
              0.10000000149011612,
              0.10000000149011612
            ],
            "crit_up": [
              0.029999999329447746,
              0.035999998450279236,
              0.041999999433755875,
              0.04800000041723251,
              0.05400000140070915,
              0.05999999865889549,
              0.06599999964237213,
              0.07199999690055847,
              0.08399999886751175
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "max_stack": [
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTags": [
                      "Skill/Character/Common/SpellStatus"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "not",
                          "condition": {
                            "kind": "timedMarkerPresent",
                            "target": "caster",
                            "markerId": "sk_wpn_pistol_0006"
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_pistol_0006_atk_up_up",
                              "target": "caster",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "atk_up": {
                                  "kind": "blackboard",
                                  "key": "atk_up"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                }
                              }
                            }
                          },
                          {
                            "kind": "createTimedMarker",
                            "parameters": {
                              "target": "caster",
                              "markerId": "sk_wpn_pistol_0006",
                              "durationSeconds": {
                                "kind": "blackboard",
                                "key": "cd"
                              },
                              "autoFinishByAction": false
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_handcannon_0006",
  "iconPath": "/weapons/handcannon/wpn_handcannon_0006.webp"
} as const satisfies WeaponDefinition;

export default definition;
