/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_pistol_0007",
  "rarity": 6,
  "weaponType": "handcannon",
  "baseAttackAtLevelNodes": [
    50,
    144,
    243,
    342,
    441,
    490
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "agility",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_pistol_0007_valid": {
          "stackingType": "stack",
          "priority": 1,
          "maxStackCount": 1,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_atk_up",
            "iconPath": "/icons/icon_battle_buff_atk_up.webp",
            "showInHeadBarCommon": true,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "dmg_up": 0,
            "duration": 0,
            "max_stack": 1
          },
          "attributeModifiers": [],
          "damageModifiers": [
            {
              "enabledSide": "attacker",
              "condition": {
                "kind": "all",
                "conditions": [
                  {
                    "kind": "eventDamageTypesMatch",
                    "damageTypes": [
                      "cryo",
                      "nature"
                    ]
                  },
                  {
                    "kind": "eventDamageTagsMatch",
                    "match": "hasAny",
                    "tags": [
                      "normalSkill"
                    ]
                  }
                ]
              },
              "processors": [
                {
                  "kind": "damageScale",
                  "side": "attacker",
                  "zone": "normal",
                  "addition": {
                    "blackboardKey": "dmg_up"
                  }
                }
              ]
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "cryo",
          "slot": "baseAddition",
          "value": [
            0.0555555559694767,
            0.10000000149011612,
            0.14444445073604584,
            0.18888889253139496,
            0.23333333432674408,
            0.2777777910232544,
            0.3222222328186035,
            0.36666667461395264,
            0.4333333373069763
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "attackPercent",
          "value": [
            0.07000000029802322,
            0.08399999886751175,
            0.09799999743700027,
            0.1120000034570694,
            0.12600000202655792,
            0.14000000059604645,
            0.15399999916553497,
            0.1679999977350235,
            0.19599999487400055
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeCastSkill",
          "priority": 0,
          "blackboard": {
            "atk_up": [
              0.07000000029802322,
              0.08399999886751175,
              0.09799999743700027,
              0.1120000034570694,
              0.12600000202655792,
              0.14000000059604645,
              0.15399999916553497,
              0.1679999977350235,
              0.19599999487400055
            ],
            "dmg_up": [
              0.07999999821186066,
              0.09600000083446503,
              0.1120000034570694,
              0.12800000607967377,
              0.14399999380111694,
              0.1599999964237213,
              0.17599999904632568,
              0.19200000166893005,
              0.2240000069141388
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "max_stack": [
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventSkillTypeIn",
                    "skillTypes": [
                      "comboSkill"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_pistol_0007_valid",
                        "target": "caster",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "dmg_up": {
                            "kind": "blackboard",
                            "key": "dmg_up"
                          },
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          },
                          "max_stack": {
                            "kind": "blackboard",
                            "key": "max_stack"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_handcannon_0007",
  "iconPath": "/weapons/handcannon/wpn_handcannon_0007.webp"
} as const satisfies WeaponDefinition;

export default definition;
