/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_pistol_0006",
  "rarity": 5,
  "weaponType": "handcannon",
  "baseAttackAtLevelNodes": [
    42,
    120,
    203,
    286,
    369,
    411
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "agility",
          "operation": "flat",
          "value": [
            16,
            28,
            41,
            54,
            67,
            80,
            92,
            105,
            124
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_pistol_0006_atk_up_up": {
          "stackingType": "stack",
          "priority": 0,
          "maxStackCount": {
            "blackboardKey": "max_stack"
          },
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_atk_up",
            "iconPath": "/icons/icon_battle_buff_atk_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTagIds": [],
          "extendTagIds": [],
          "blackboard": {
            "atk_up": 0,
            "duration": 0,
            "max_stack": 0
          },
          "attributeModifiers": [
            {
              "attribute": "Atk",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "atk_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "cryo",
          "slot": "baseAddition",
          "value": [
            0.044444446,
            0.08,
            0.115555555,
            0.15111111,
            0.18666667,
            0.22222222,
            0.25777778,
            0.29333332,
            0.34666666
          ]
        },
        {
          "kind": "damageScale",
          "target": "heat",
          "slot": "baseAddition",
          "value": [
            0.044444446,
            0.08,
            0.115555555,
            0.15111111,
            0.18666667,
            0.22222222,
            0.25777778,
            0.29333332,
            0.34666666
          ]
        },
        {
          "kind": "damageScale",
          "target": "electric",
          "slot": "baseAddition",
          "value": [
            0.044444446,
            0.08,
            0.115555555,
            0.15111111,
            0.18666667,
            0.22222222,
            0.25777778,
            0.29333332,
            0.34666666
          ]
        },
        {
          "kind": "damageScale",
          "target": "nature",
          "slot": "baseAddition",
          "value": [
            0.044444446,
            0.08,
            0.115555555,
            0.15111111,
            0.18666667,
            0.22222222,
            0.25777778,
            0.29333332,
            0.34666666
          ]
        },
        {
          "kind": "damageScale",
          "target": "ether",
          "slot": "baseAddition",
          "value": [
            0.044444446,
            0.08,
            0.115555555,
            0.15111111,
            0.18666667,
            0.22222222,
            0.25777778,
            0.29333332,
            0.34666666
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "criticalRate",
          "value": [
            0.03,
            0.036,
            0.042,
            0.048,
            0.054,
            0.06,
            0.066,
            0.072,
            0.084
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeOutputBuff",
          "priority": 0,
          "blackboard": {
            "atk_up": [
              0.075,
              0.09,
              0.105,
              0.12,
              0.135,
              0.15,
              0.165,
              0.18,
              0.21
            ],
            "cd": [
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1,
              0.1
            ],
            "crit_up": [
              0.03,
              0.036,
              0.042,
              0.048,
              0.054,
              0.06,
              0.066,
              0.072,
              0.084
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "max_stack": [
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTagIds": [
                      1474064594
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "not",
                          "condition": {
                            "kind": "timedMarkerPresent",
                            "target": "caster",
                            "markerId": "sk_wpn_pistol_0006"
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_pistol_0006_atk_up_up",
                              "target": "caster",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "atk_up": {
                                  "kind": "blackboard",
                                  "key": "atk_up"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                }
                              }
                            }
                          },
                          {
                            "kind": "createTimedMarker",
                            "parameters": {
                              "target": "caster",
                              "markerId": "sk_wpn_pistol_0006",
                              "durationSeconds": {
                                "kind": "blackboard",
                                "key": "cd"
                              },
                              "autoFinishByAction": false
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_handcannon_0006",
  "iconPath": "/weapons/handcannon/wpn_handcannon_0006.webp"
} as const satisfies WeaponDefinition;

export default definition;
