/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_pistol_0010",
  "rarity": 6,
  "weaponType": "handcannon",
  "baseAttackAtLevelNodes": [
    51,
    148,
    250,
    352,
    454,
    505
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "intellect",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_pistol_0010_valid": {
          "stackingType": "stack",
          "priority": 0,
          "maxStackCount": 0,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_cryst_dmg_up",
            "iconPath": "/icons/icon_battle_cryst_dmg_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "cryst_dmg_up_valid": 0,
            "duration": 0,
            "max_stack": 0
          },
          "attributeModifiers": [
            {
              "attribute": "cryoDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "cryst_dmg_up_valid"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "criticalRate",
          "value": [
            0.02500000037252903,
            0.04500000178813934,
            0.06499999761581421,
            0.08500000089406967,
            0.10499999672174454,
            0.125,
            0.14499999582767487,
            0.16500000655651093,
            0.19499999284744263
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "cryo",
          "slot": "baseAddition",
          "value": [
            0.1599999964237213,
            0.19200000166893005,
            0.2240000069141388,
            0.25600001215934753,
            0.2879999876022339,
            0.3199999928474426,
            0.35199999809265137,
            0.3840000033378601,
            0.4480000138282776
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "outputCriticalDamage",
          "priority": 0,
          "blackboard": {
            "cryst_dmg_up": [
              0.1599999964237213,
              0.19200000166893005,
              0.2240000069141388,
              0.25600001215934753,
              0.2879999876022339,
              0.3199999928474426,
              0.35199999809265137,
              0.3840000033378601,
              0.4480000138282776
            ],
            "cryst_dmg_up2": [
              0.14000000059604645,
              0.1679999977350235,
              0.19599999487400055,
              0.2240000069141388,
              0.25200000405311584,
              0.2800000011920929,
              0.30799999833106995,
              0.335999995470047,
              0.3919999897480011
            ],
            "duration": [
              30,
              30,
              30,
              30,
              30,
              30,
              30,
              30,
              30
            ],
            "max_stack": [
              3,
              3,
              3,
              3,
              3,
              3,
              3,
              3,
              3
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventDamageTagsMatch",
                    "match": "hasAny",
                    "tags": [
                      "normalSkill",
                      "comboSkill"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "not",
                          "condition": {
                            "kind": "timedMarkerPresent",
                            "target": "caster",
                            "markerId": "wpn_pistol_0010"
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "createTimedMarker",
                            "parameters": {
                              "target": "caster",
                              "markerId": "wpn_pistol_0010",
                              "durationSeconds": {
                                "kind": "constant",
                                "value": 0.10000000149011612
                              },
                              "autoFinishByAction": false
                            }
                          },
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_pistol_0010_valid",
                              "target": "caster",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "cryst_dmg_up_valid": {
                                  "kind": "blackboard",
                                  "key": "cryst_dmg_up2"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_handcannon_0010",
  "iconPath": "/weapons/handcannon/wpn_handcannon_0010.webp"
} as const satisfies WeaponDefinition;

export default definition;
