/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { GearSetDefinition } from '../../../core/game-data/equipmentDefinition';

const definition = {
  slug: 'suit_atk01',
  icon: 'endaxis:equipment/atk01/item_equip_t3_suit_atk01_edc_04',
  modifiers: [
    { kind: 'damageScale', target: 'battleSkill', slot: 'baseAddition', value: 0.24 },
    { kind: 'damageScale', target: 'comboSkill', slot: 'baseAddition', value: 0.24 },
    { kind: 'damageScale', target: 'ultimate', slot: 'baseAddition', value: 0.24 },
  ],
  actionGraph: {
    main: {
      nodes: {
        applyBuff_1: {
          action: {
            kind: 'applyBuff',
            parameters: {
              buffs: [
                {
                  buffId: 'buff_equipsuit_atk_01',
                  blackboardAssignments: {
                    dmg_up: { kind: 'constant', value: 0.24 },
                    atk_up: { kind: 'constant', value: 0.05 },
                    duration: { kind: 'constant', value: 15 },
                  },
                },
              ],
              target: 'caster',
            },
          },
          next: null,
        },
      },
    },
    macros: {},
  },
  skillId: 'passive_equipsuit_atk_01',
  buffDefinitions: {
    buff_equipsuit_atk_01: {
      stackingType: 'unique',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: { atk_up: 0.05, dmg_up: 0.2, duration: 15 },
      attributeModifiers: [],
      abilityEventResponses: [
        { event: 'beforeCastSkill', priority: 0, sequence: { $sequence: 'conditional_2' } },
        { event: 'beforeCastSkill', priority: 0, sequence: { $sequence: 'conditional_4' } },
        { event: 'beforeCastSkill', priority: 0, sequence: { $sequence: 'conditional_6' } },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_equipsuit_atk_01_normalskill',
                      copiedBlackboardAssignments: { atk_up: 'atk_up', duration: 'duration' },
                    },
                  ],
                  target: 'buffOwner',
                  source: 'buffOwner',
                  inheritSourceSkillCastInfo: true,
                },
              },
              next: null,
            },
            conditional_2: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
                whenTrue: { $sequence: 'applyBuff_1' },
              },
              next: null,
            },
            applyBuff_3: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_equipsuit_atk_01_comboskill',
                      copiedBlackboardAssignments: { atk_up: 'atk_up', duration: 'duration' },
                    },
                  ],
                  target: 'buffOwner',
                  source: 'buffOwner',
                  inheritSourceSkillCastInfo: true,
                },
              },
              next: null,
            },
            conditional_4: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_2' } },
                whenTrue: { $sequence: 'applyBuff_3' },
              },
              next: null,
            },
            applyBuff_5: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_equipsuit_atk_01_ultimateskill',
                      copiedBlackboardAssignments: { atk_up: 'atk_up', duration: 'duration' },
                    },
                  ],
                  target: 'buffOwner',
                  source: 'buffOwner',
                  inheritSourceSkillCastInfo: true,
                },
              },
              next: null,
            },
            conditional_6: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
                whenTrue: { $sequence: 'applyBuff_5' },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: { kind: 'eventSkillTypeIn', skillTypes: ['battleSkill'] },
            },
            data_2: {
              type: 'boolean',
              expression: { kind: 'eventSkillTypeIn', skillTypes: ['comboSkill'] },
            },
            data_3: {
              type: 'boolean',
              expression: { kind: 'eventSkillTypeIn', skillTypes: ['ultimate'] },
            },
          },
        },
        macros: {},
      },
    },
    buff_equipsuit_atk_01_comboskill: {
      stackingType: 'refresh',
      priority: 0,
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_buff_atk_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { atk_up: 0, duration: 0 },
      attributeModifiers: [
        { attribute: 'Atk', slot: 'baseMultiplier', value: { blackboardKey: 'atk_up' } },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
    buff_equipsuit_atk_01_normalskill: {
      stackingType: 'refresh',
      priority: 0,
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_buff_atk_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { atk_up: 0, duration: 0 },
      attributeModifiers: [
        { attribute: 'Atk', slot: 'baseMultiplier', value: { blackboardKey: 'atk_up' } },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
    buff_equipsuit_atk_01_ultimateskill: {
      stackingType: 'refresh',
      priority: 0,
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_buff_atk_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { atk_up: 0, duration: 0 },
      attributeModifiers: [
        { attribute: 'Atk', slot: 'baseMultiplier', value: { blackboardKey: 'atk_up' } },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
  },
  enableSequence: { $sequence: 'applyBuff_1' },
} as const satisfies GearSetDefinition;

export default definition;
