/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { GearSetDefinition } from '../../../core/game-data/equipmentDefinition';

const definition = {
  slug: 'suit_usp01',
  icon: 'endaxis:equipment/usp01/item_equip_t3_suit_usp01_edc_02',
  modifiers: [{ kind: 'panelStat', stat: 'ultimateEnergyGainEfficiency', value: 0.2 }],
  actionGraph: {
    main: {
      nodes: {
        applyBuff_1: {
          action: {
            kind: 'applyBuff',
            parameters: {
              buffs: [
                {
                  buffId: 'buff_equipsuit_usp_01',
                  blackboardAssignments: {
                    ultimate_gain_up: { kind: 'constant', value: 0.2 },
                    atb_recover: { kind: 'constant', value: 50 },
                  },
                },
              ],
              target: 'caster',
            },
          },
          next: null,
        },
      },
    },
    macros: {},
  },
  skillId: 'passive_equipsuit_usp_01',
  buffDefinitions: {
    buff_equipsuit_usp_01: {
      stackingType: 'unlimited',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: { atb_recover: 50, has_gain_atb: 0, ultimate_gain_up: 0.2 },
      attributeModifiers: [],
      abilityEventResponses: [
        { event: 'enterFight', priority: 0, sequence: { $sequence: 'modifyActionValue_1' } },
        { event: 'beforeCastSkill', priority: 0, sequence: { $sequence: 'checkCondition_5' } },
      ],
      actionGraph: {
        main: {
          nodes: {
            modifyActionValue_1: {
              action: {
                kind: 'modifyActionValue',
                parameters: {
                  key: 'has_gain_atb',
                  operation: 'assign',
                  value: { kind: 'constant', value: 0 },
                },
              },
              next: null,
            },
            changeResource_2: {
              action: {
                kind: 'changeResource',
                parameters: {
                  resource: 'sp',
                  amount: { kind: 'valueNode', nodeId: 'data_1' },
                  coefficient: { kind: 'constant', value: 1 },
                  source: { kind: 'owner' },
                  targets: { kind: 'owner' },
                  spGainKind: 'refund',
                  spGainSource: 'default',
                },
              },
              next: null,
            },
            modifyActionValue_3: {
              action: {
                kind: 'modifyActionValue',
                parameters: {
                  key: 'has_gain_atb',
                  operation: 'assign',
                  value: { kind: 'constant', value: 1 },
                },
              },
              next: 'changeResource_2',
            },
            checkCondition_4: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
              },
              next: 'modifyActionValue_3',
            },
            checkCondition_5: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_4' } },
              },
              next: 'checkCondition_4',
            },
          },
          dataNodes: {
            data_1: { type: 'number', expression: { kind: 'blackboard', key: 'atb_recover' } },
            data_2: {
              type: 'number',
              expression: { kind: 'blackboard', key: 'has_gain_atb', fallback: 0 },
            },
            data_3: {
              type: 'boolean',
              expression: {
                kind: 'actionValueCompare',
                left: { kind: 'valueNode', nodeId: 'data_2' },
                operator: 'equal',
                right: { kind: 'constant', value: 0 },
              },
            },
            data_4: {
              type: 'boolean',
              expression: { kind: 'eventSkillTypeIn', skillTypes: ['battleSkill'] },
            },
          },
        },
        macros: {},
      },
    },
  },
  initializationSequence: { $sequence: 'applyBuff_1' },
} as const satisfies GearSetDefinition;

export default definition;
