/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { GearSetDefinition } from '../../../core/game-data/equipmentDefinition';

const definition = {
  slug: 'suit_will01',
  icon: 'endaxis:equipment/will01/item_equip_t3_suit_will01_edc_01',
  modifiers: [{ kind: 'attribute', attribute: 'will', operation: 'flat', value: 50 }],
  skillId: 'passive_equipsuit_will_01',
} as const satisfies GearSetDefinition;

export default definition;
