/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { GearSetDefinition } from '../../../core/game-data/equipmentDefinition';

const definition = {
  slug: 'suit_burst01',
  icon: 'endaxis:equipment/burst01/item_equip_t4_suit_burst01_edc_01',
  modifiers: [
    { kind: 'damageScale', target: 'comboSkill', slot: 'baseAddition', value: 0.2 },
    { kind: 'damageScale', target: 'battleSkill', slot: 'baseAddition', value: 0.2 },
    { kind: 'damageScale', target: 'ultimate', slot: 'baseAddition', value: 0.2 },
  ],
  skillId: 'passive_equipsuit_burst_01',
  buffDefinitions: {
    buff_equipsuit_burst_01: {
      stackingType: 'unlimited',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: { buffid: '#', duration: 10, skill_dmg_up: 0.2, spell_dmg_up: 0, stack_cond: 2 },
      attributeModifiers: [],
      abilityEventResponses: [
        { event: 'outputBuff', priority: 0, sequence: { $sequence: 'conditional_3' } },
        { event: 'outputBuff', priority: 0, sequence: { $sequence: 'conditional_6' } },
        { event: 'outputBuff', priority: 0, sequence: { $sequence: 'conditional_9' } },
        { event: 'outputBuff', priority: 0, sequence: { $sequence: 'conditional_12' } },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_equipsuit_burst_01_spelldmgup',
                      copiedBlackboardAssignments: {
                        spell_dmg_up: 'spell_dmg_up',
                        duration: 'duration',
                      },
                    },
                  ],
                  target: 'buffOwner',
                  source: 'buffOwner',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: null,
            },
            conditional_2: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_2' } },
                whenTrue: { $sequence: 'applyBuff_1' },
              },
              next: null,
            },
            conditional_3: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
                whenTrue: { $sequence: 'conditional_2' },
              },
              next: null,
            },
            conditional_5: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_5' } },
                whenTrue: { $sequence: 'applyBuff_1' },
              },
              next: null,
            },
            conditional_6: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_6' } },
                whenTrue: { $sequence: 'conditional_5' },
              },
              next: null,
            },
            conditional_8: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_8' } },
                whenTrue: { $sequence: 'applyBuff_1' },
              },
              next: null,
            },
            conditional_9: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_9' } },
                whenTrue: { $sequence: 'conditional_8' },
              },
              next: null,
            },
            conditional_11: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_11' } },
                whenTrue: { $sequence: 'applyBuff_1' },
              },
              next: null,
            },
            conditional_12: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_12' } },
                whenTrue: { $sequence: 'conditional_11' },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: { type: 'number', expression: { kind: 'blackboard', key: 'stack_cond' } },
            data_2: {
              type: 'boolean',
              expression: {
                kind: 'buffStackCompare',
                target: 'actionInputTarget',
                tagQueryType: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellInflict/FireInflict'],
                operator: 'greaterOrEqual',
                value: { kind: 'valueNode', nodeId: 'data_1' },
              },
            },
            data_3: {
              type: 'boolean',
              expression: {
                kind: 'eventBuffTagsMatch',
                match: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellInflict/FireInflict'],
              },
            },
            data_4: { type: 'number', expression: { kind: 'blackboard', key: 'stack_cond' } },
            data_5: {
              type: 'boolean',
              expression: {
                kind: 'buffStackCompare',
                target: 'actionInputTarget',
                tagQueryType: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellInflict/NaturalInflict'],
                operator: 'greaterOrEqual',
                value: { kind: 'valueNode', nodeId: 'data_4' },
              },
            },
            data_6: {
              type: 'boolean',
              expression: {
                kind: 'eventBuffTagsMatch',
                match: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellInflict/NaturalInflict'],
              },
            },
            data_7: { type: 'number', expression: { kind: 'blackboard', key: 'stack_cond' } },
            data_8: {
              type: 'boolean',
              expression: {
                kind: 'buffStackCompare',
                target: 'actionInputTarget',
                tagQueryType: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellInflict/CrystInflict'],
                operator: 'greaterOrEqual',
                value: { kind: 'valueNode', nodeId: 'data_7' },
              },
            },
            data_9: {
              type: 'boolean',
              expression: {
                kind: 'eventBuffTagsMatch',
                match: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellInflict/CrystInflict'],
              },
            },
            data_10: { type: 'number', expression: { kind: 'blackboard', key: 'stack_cond' } },
            data_11: {
              type: 'boolean',
              expression: {
                kind: 'buffStackCompare',
                target: 'actionInputTarget',
                tagQueryType: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellInflict/PulseInflict'],
                operator: 'greaterOrEqual',
                value: { kind: 'valueNode', nodeId: 'data_10' },
              },
            },
            data_12: {
              type: 'boolean',
              expression: {
                kind: 'eventBuffTagsMatch',
                match: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellInflict/PulseInflict'],
              },
            },
          },
        },
        macros: {},
      },
    },
    buff_equipsuit_burst_01_spelldmgup: {
      stackingType: 'stack',
      priority: 0,
      maxStackCount: 1,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_spell_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 10, skill_dmg_up: 0.2, spell_dmg_up: 0, stack_cond: 2 },
      attributeModifiers: [
        {
          attribute: 'heatDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'electricDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'cryoDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'natureDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
  },
  initializationSequence: { $sequence: 'applyBuff_1' },
  actionGraph: {
    main: {
      nodes: {
        applyBuff_1: {
          action: {
            kind: 'applyBuff',
            parameters: {
              buffs: [
                {
                  buffId: 'buff_equipsuit_burst_01',
                  blackboardAssignments: {
                    stack_cond: { kind: 'constant', value: 2 },
                    spell_dmg_up: { kind: 'constant', value: 0.35 },
                    duration: { kind: 'constant', value: 15 },
                  },
                },
              ],
              target: 'caster',
            },
          },
          next: null,
        },
      },
    },
    macros: {},
  },
} as const satisfies GearSetDefinition;

export default definition;
