/** UI 读取本地化游戏内容的统一出口。 */
export {
  getGameAttributeName,
  getGameClassName,
  getGameElementName,
  getGameQualityName,
  getGameSlotTypeName,
  getGameWeaponTypeName,
  getEnemyGameName,
  getGearPieceGameName,
  getGearSetGameDescription,
  getGearSetGameName,
  getOperatorCombatSkillDescription,
  getOperatorCombatSkillFormKeys,
  getOperatorCombatSkillName,
  getOperatorFormName,
  getOperatorGameName,
  getOperatorPotentialDescription,
  getOperatorPotentialName,
  getOperatorTalentDescription,
  getOperatorTalentName,
  getOperatorUiLabel,
  getWeaponGameName,
  getWeaponSkillDescription,
  getWeaponSkillName,
  getWeaponUiLabel,
} from '@/data/gameText';
