/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_lance_0013',
  rarity: 5,
  weaponType: 'lance',
  baseAttackAtLevelNodes: [42, 120, 203, 286, 369, 411],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'will',
          operation: 'flat',
          value: [16, 28, 41, 54, 67, 80, 92, 105, 124],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_will_mid',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'physical',
          slot: 'baseAddition',
          value: [
            0.044444446, 0.08, 0.115555555, 0.15111111, 0.18666667, 0.22222222, 0.25777778,
            0.29333332, 0.34666666,
          ],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_phydam_mid',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_lance_0013_atk_up',
                      copiedBlackboardAssignments: { atk_up: 'atk_up', duration: 'duration' },
                    },
                  ],
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: null,
            },
            checkCondition_2: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
              },
              next: 'applyBuff_1',
            },
            checkCondition_3: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_2' } },
              },
              next: 'checkCondition_2',
            },
            applyBuff_4: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_lance_0013_damage01',
                      blackboardAssignments: { dmg_up: { kind: 'valueNode', nodeId: 'data_3' } },
                    },
                  ],
                  target: 'caster',
                },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: {
                kind: 'eventConsumedBuffLayerCompare',
                operator: 'greaterOrEqual',
                value: { kind: 'constant', value: 1 },
              },
            },
            data_2: {
              type: 'boolean',
              expression: {
                kind: 'eventBuffTagsMatch',
                match: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellStatus/Frozen'],
              },
            },
            data_3: { type: 'number', expression: { kind: 'blackboard', key: 'install_0_dmg_up' } },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_lance_0013',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'buffConsumed',
          priority: 0,
          sequence: { $sequence: 'checkCondition_3' },
        },
      ],
      enableSequence: { $sequence: 'applyBuff_4' },
      blackboard: {
        atk_up: [0.12, 0.144, 0.168, 0.192, 0.216, 0.24, 0.264, 0.288, 0.336],
        duration: [15, 15, 15, 15, 15, 15, 15, 15, 15],
        install_0_dmg_up: [0.08, 0.096, 0.112, 0.128, 0.144, 0.16, 0.176, 0.192, 0.224],
      },
    },
  ],
  assetSlug: 'wpn_lance_0013',
  icon: 'endaxis:weapons/lance/wpn_lance_0013',
  buffDefinitions: {
    buff_wpn_lance_0013_atk_up: {
      stackingType: 'stack',
      priority: 0,
      maxStackCount: 1,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_buff_atk_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { atk_up: 0, duration: 0 },
      attributeModifiers: [
        { attribute: 'Atk', slot: 'baseMultiplier', value: { blackboardKey: 'atk_up' } },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
    buff_wpn_lance_0013_damage01: {
      stackingType: 'unique',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: { dmg_up: 0 },
      attributeModifiers: [],
      damageModifiers: [
        {
          enabledSide: 'attacker',
          condition: { $sequence: 'checkCondition_1' },
          processors: [
            {
              kind: 'damageScale',
              side: 'attacker',
              zone: 'normal',
              addition: { blackboardKey: 'dmg_up' },
            },
          ],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            checkCondition_1: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: {
                kind: 'entityTagMatch',
                target: 'actionInputTarget',
                tagQueryType: 'hasAny',
                tags: [
                  'Skill/Character/Common/SpellInflict/CrystInflict',
                  'Skill/Character/Common/SpellStatus/Frozen',
                ],
              },
            },
          },
        },
        macros: {},
      },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
