/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_lance_0016',
  rarity: 6,
  weaponType: 'lance',
  baseAttackAtLevelNodes: [49, 142, 240, 338, 436, 485],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'will',
          operation: 'flat',
          value: [20, 36, 52, 68, 84, 100, 116, 132, 156],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_will_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'staticHealingIncrease',
          target: 'output',
          value: [
            0.05952381, 0.10714286, 0.15476191, 0.20238096, 0.25, 0.29761904, 0.3452381, 0.39285713,
            0.4642857,
          ],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_heal_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'electric',
          slot: 'baseAddition',
          value: [0.06, 0.072, 0.084, 0.096, 0.108, 0.12, 0.132, 0.144, 0.168],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_lance_0016_heal',
                      copiedBlackboardAssignments: { heal_up: 'heal_up', duration: 'duration' },
                    },
                  ],
                  targets: { kind: 'source' },
                  source: { kind: 'source' },
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: null,
            },
            checkCondition_2: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
              },
              next: 'applyBuff_1',
            },
            applyBuff_3: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_lance_0016_dmgup',
                      copiedBlackboardAssignments: {
                        spell_dmg_up: 'spell_dmg_up',
                        duration2: 'duration2',
                      },
                    },
                  ],
                  targets: { kind: 'characterTeam', excludeOwner: false },
                  source: { kind: 'source' },
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: null,
            },
            checkCondition_4: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_2' } },
              },
              next: 'applyBuff_3',
            },
            invertNextResult_5: {
              action: { kind: 'invertNextResult', parameters: {} },
              next: 'checkCondition_4',
            },
            checkCondition_6: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
              },
              next: 'invertNextResult_5',
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: { kind: 'originSkillTypeIn', skillTypes: ['comboSkill'] },
            },
            data_2: {
              type: 'boolean',
              expression: {
                kind: 'actionInputTargetIdentityMatch',
                other: 'actionOwner',
                operator: 'equal',
              },
            },
            data_3: {
              type: 'boolean',
              expression: {
                kind: 'eventHealTagsMatch',
                match: 'hasAny',
                tags: ['Skill/Character/Common/Heal/ComboSkillHeal'],
              },
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_lance_0016',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'beforeOutputDamage',
          priority: 0,
          sequence: { $sequence: 'checkCondition_2' },
        },
        {
          key: 'skill3:event:1:sequence:0',
          abilityEvent: 'outputHeal',
          priority: 0,
          sequence: { $sequence: 'checkCondition_6' },
        },
      ],
      blackboard: {
        duration: [15, 15, 15, 15, 15, 15, 15, 15, 15],
        duration2: [20, 20, 20, 20, 20, 20, 20, 20, 20],
        heal_up: [0.04, 0.048, 0.056, 0.064, 0.072, 0.08, 0.088, 0.096, 0.112],
        spell_dmg_up: [0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.14],
      },
    },
  ],
  assetSlug: 'wpn_lance_0016',
  icon: 'endaxis:weapons/lance/wpn_lance_0016',
  buffDefinitions: {
    buff_wpn_lance_0016_dmgup: {
      stackingType: 'highPriority',
      priority: { blackboardKey: 'spell_dmg_up' },
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration2' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_spell_up',
        showInHeadBarCommon: true,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration2: 15, spell_dmg_up: 0.04 },
      attributeModifiers: [
        {
          attribute: 'heatDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'electricDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'cryoDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'natureDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
    buff_wpn_lance_0016_heal: {
      stackingType: 'refresh',
      priority: 0,
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_buff_heal',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 15, heal_up: 0.04 },
      attributeModifiers: [
        {
          attribute: 'healOutputIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'heal_up' },
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
