/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_funnel_0018",
  "rarity": 6,
  "weaponType": "arts-unit",
  "baseAttackAtLevelNodes": [
    50,
    144,
    243,
    342,
    441,
    490
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "intellect",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_funnel_0018_layer": {
          "stackingType": "highPriorityWithMaxStack",
          "priority": {
            "blackboardKey": "atk_up"
          },
          "maxStackCount": {
            "blackboardKey": "max_stack"
          },
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_atk_up",
            "iconPath": "/icons/icon_battle_buff_atk_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "iconStyleInSquad": "Default",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "atk_up": 0,
            "duration": 0,
            "max_stack": 0
          },
          "attributeModifiers": [
            {
              "attribute": "Atk",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "atk_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "ultimateEnergyGainEfficiency",
          "value": [
            0.05952381,
            0.10714286,
            0.15476191,
            0.20238096,
            0.25,
            0.29761904,
            0.3452381,
            0.39285713,
            0.4642857
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "nature",
          "slot": "baseAddition",
          "value": [
            0.07,
            0.084,
            0.098,
            0.112,
            0.126,
            0.14,
            0.154,
            0.168,
            0.196
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeOutputBuff",
          "priority": 0,
          "blackboard": {
            "atk_up": [
              0.06,
              0.072,
              0.084,
              0.096,
              0.108,
              0.12,
              0.132,
              0.144,
              0.168
            ],
            "atk_up2": [
              0.015,
              0.018,
              0.021,
              0.024,
              0.027,
              0.03,
              0.033,
              0.036,
              0.042
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "max_stack": [
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2
            ],
            "nature_dmg_up": [
              0.07,
              0.084,
              0.098,
              0.112,
              0.126,
              0.14,
              0.154,
              0.168,
              0.196
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTags": [
                      "Skill/Character/Common/Affixes/Vulnerable/VulnerableFire"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "originSkillTypeIn",
                          "skillTypes": [
                            "comboSkill"
                          ]
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_funnel_0018_layer",
                              "target": "eventSource",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "atk_up": {
                                  "kind": "blackboard",
                                  "key": "atk_up"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          },
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_funnel_0018_layer",
                              "target": "partyExceptCaster",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "atk_up": {
                                  "kind": "blackboard",
                                  "key": "atk_up2"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:1:sequence:0",
          "abilityEvent": "beforeOutputBuff",
          "priority": 0,
          "blackboard": {
            "atk_up": [
              0.06,
              0.072,
              0.084,
              0.096,
              0.108,
              0.12,
              0.132,
              0.144,
              0.168
            ],
            "atk_up2": [
              0.015,
              0.018,
              0.021,
              0.024,
              0.027,
              0.03,
              0.033,
              0.036,
              0.042
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "max_stack": [
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2
            ],
            "nature_dmg_up": [
              0.07,
              0.084,
              0.098,
              0.112,
              0.126,
              0.14,
              0.154,
              0.168,
              0.196
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTags": [
                      "Skill/Character/Common/Affixes/Vulnerable/VulnerableCryst"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "originSkillTypeIn",
                          "skillTypes": [
                            "comboSkill"
                          ]
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_funnel_0018_layer",
                              "target": "eventSource",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "atk_up": {
                                  "kind": "blackboard",
                                  "key": "atk_up"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          },
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_funnel_0018_layer",
                              "target": "partyExceptCaster",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "atk_up": {
                                  "kind": "blackboard",
                                  "key": "atk_up2"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:2:sequence:0",
          "abilityEvent": "beforeOutputBuff",
          "priority": 0,
          "blackboard": {
            "atk_up": [
              0.06,
              0.072,
              0.084,
              0.096,
              0.108,
              0.12,
              0.132,
              0.144,
              0.168
            ],
            "atk_up2": [
              0.015,
              0.018,
              0.021,
              0.024,
              0.027,
              0.03,
              0.033,
              0.036,
              0.042
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "max_stack": [
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2
            ],
            "nature_dmg_up": [
              0.07,
              0.084,
              0.098,
              0.112,
              0.126,
              0.14,
              0.154,
              0.168,
              0.196
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTags": [
                      "Skill/Character/Common/Affixes/Vulnerable/VulnerablePulse"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "originSkillTypeIn",
                          "skillTypes": [
                            "comboSkill"
                          ]
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_funnel_0018_layer",
                              "target": "eventSource",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "atk_up": {
                                  "kind": "blackboard",
                                  "key": "atk_up"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          },
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_funnel_0018_layer",
                              "target": "partyExceptCaster",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "atk_up": {
                                  "kind": "blackboard",
                                  "key": "atk_up2"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:3:sequence:0",
          "abilityEvent": "beforeOutputBuff",
          "priority": 0,
          "blackboard": {
            "atk_up": [
              0.06,
              0.072,
              0.084,
              0.096,
              0.108,
              0.12,
              0.132,
              0.144,
              0.168
            ],
            "atk_up2": [
              0.015,
              0.018,
              0.021,
              0.024,
              0.027,
              0.03,
              0.033,
              0.036,
              0.042
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "max_stack": [
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2
            ],
            "nature_dmg_up": [
              0.07,
              0.084,
              0.098,
              0.112,
              0.126,
              0.14,
              0.154,
              0.168,
              0.196
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTags": [
                      "Skill/Character/Common/Affixes/Vulnerable/VulnerableNatural"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "originSkillTypeIn",
                          "skillTypes": [
                            "comboSkill"
                          ]
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_funnel_0018_layer",
                              "target": "eventSource",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "atk_up": {
                                  "kind": "blackboard",
                                  "key": "atk_up"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          },
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_funnel_0018_layer",
                              "target": "partyExceptCaster",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "atk_up": {
                                  "kind": "blackboard",
                                  "key": "atk_up2"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:4:sequence:0",
          "abilityEvent": "beforeOutputInfliction",
          "priority": 0,
          "blackboard": {
            "atk_up": [
              0.06,
              0.072,
              0.084,
              0.096,
              0.108,
              0.12,
              0.132,
              0.144,
              0.168
            ],
            "atk_up2": [
              0.015,
              0.018,
              0.021,
              0.024,
              0.027,
              0.03,
              0.033,
              0.036,
              0.042
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "max_stack": [
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2
            ],
            "nature_dmg_up": [
              0.07,
              0.084,
              0.098,
              0.112,
              0.126,
              0.14,
              0.154,
              0.168,
              0.196
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "originSkillTypeIn",
                    "skillTypes": [
                      "comboSkill"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_funnel_0018_layer",
                        "target": "eventSource",
                        "source": "eventSource",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "atk_up": {
                            "kind": "blackboard",
                            "key": "atk_up"
                          },
                          "max_stack": {
                            "kind": "blackboard",
                            "key": "max_stack"
                          },
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          }
                        }
                      }
                    },
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_funnel_0018_layer",
                        "target": "partyExceptCaster",
                        "source": "eventSource",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "atk_up": {
                            "kind": "blackboard",
                            "key": "atk_up2"
                          },
                          "max_stack": {
                            "kind": "blackboard",
                            "key": "max_stack"
                          },
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_artsunit_0018",
  "iconPath": "/weapons/arts-unit/wpn_artsunit_0018.webp"
} as const satisfies WeaponDefinition;

export default definition;
