/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_funnel_0013",
  "rarity": 6,
  "weaponType": "arts-unit",
  "baseAttackAtLevelNodes": [
    50,
    145,
    245,
    345,
    445,
    495
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "intellect",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_funnel_0013_valid": {
          "stackingType": "highPriority",
          "priority": {
            "blackboardKey": "lv"
          },
          "maxStackCount": 0,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_spell_taken_up",
            "iconPath": "/icons/icon_battle_spell_taken_up.webp",
            "showInHeadBarCommon": true,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": false,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "duration": 25,
            "lv": 0,
            "spell_taken_up": 0.2
          },
          "attributeModifiers": [],
          "damageModifiers": [
            {
              "enabledSide": "defender",
              "condition": {
                "kind": "eventDamageTypesMatch",
                "damageTypes": [
                  "heat",
                  "electric",
                  "cryo",
                  "nature"
                ]
              },
              "processors": [
                {
                  "kind": "damageScale",
                  "side": "defender",
                  "zone": "normal",
                  "addition": {
                    "blackboardKey": "spell_taken_up"
                  }
                }
              ]
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "staticHealingIncrease",
          "target": "output",
          "value": [
            0.0595238097012043,
            0.1071428582072258,
            0.1547619104385376,
            0.2023809552192688,
            0.25,
            0.2976190447807312,
            0.3452380895614624,
            0.3928571343421936,
            0.4642857015132904
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "secondary",
          "operation": "percent",
          "value": [
            0.1599999964237213,
            0.19200000166893005,
            0.2240000069141388,
            0.25600001215934753,
            0.2879999876022339,
            0.3199999928474426,
            0.35199999809265137,
            0.3840000033378601,
            0.4480000138282776
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "event": {
            "kind": "buffConsumed"
          },
          "priority": 0,
          "blackboard": {
            "duration": [
              25,
              25,
              25,
              25,
              25,
              25,
              25,
              25,
              25
            ],
            "lv": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9
            ],
            "second_attr_up": [
              0.1599999964237213,
              0.19200000166893005,
              0.2240000069141388,
              0.25600001215934753,
              0.2879999876022339,
              0.3199999928474426,
              0.35199999809265137,
              0.3840000033378601,
              0.4480000138282776
            ],
            "spell_dmg_taken_up": [
              0.10000000149011612,
              0.11999999731779099,
              0.14000000059604645,
              0.1599999964237213,
              0.18000000715255737,
              0.20000000298023224,
              0.2199999988079071,
              0.23999999463558197,
              0.2800000011920929
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTags": [
                      "Skill/Character/Common/SpellStatus/Corrupt"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "eventConsumedBuffLayerCompare",
                          "operator": "greaterOrEqual",
                          "value": {
                            "kind": "constant",
                            "value": 1
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_funnel_0013_valid",
                              "target": "eventTarget",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "spell_taken_up": {
                                  "kind": "blackboard",
                                  "key": "spell_dmg_taken_up"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                },
                                "lv": {
                                  "kind": "blackboard",
                                  "key": "lv"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_artsunit_0013",
  "iconPath": "/weapons/arts-unit/wpn_artsunit_0013.webp"
} as const satisfies WeaponDefinition;

export default definition;
