/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_funnel_0014",
  "rarity": 5,
  "weaponType": "arts-unit",
  "baseAttackAtLevelNodes": [
    42,
    120,
    203,
    286,
    369,
    411
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "intellect",
          "operation": "flat",
          "value": [
            16,
            28,
            41,
            54,
            67,
            80,
            92,
            105,
            124
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_funnel_0014_up": {
          "stackingType": "highPriorityWithMaxStack",
          "priority": {
            "blackboardKey": "lv"
          },
          "maxStackCount": 1,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_atk_up",
            "iconPath": "/icons/icon_battle_buff_atk_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "dmg_up": 0,
            "duration": 0,
            "lv": 0
          },
          "attributeModifiers": [
            {
              "attribute": "heatDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "dmg_up"
              }
            },
            {
              "attribute": "electricDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "dmg_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "artsIntensity",
          "value": [
            8,
            14,
            20,
            27,
            33,
            40,
            46,
            52,
            62
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "healthPercent",
          "value": [
            0.1,
            0.12,
            0.14,
            0.16,
            0.18,
            0.2,
            0.22,
            0.24,
            0.28
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeOutputSpellBurst",
          "priority": 0,
          "blackboard": {
            "dmg_up": [
              0.08,
              0.096,
              0.112,
              0.128,
              0.144,
              0.16,
              0.176,
              0.192,
              0.224
            ],
            "duration": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ],
            "hp_up": [
              0.1,
              0.12,
              0.14,
              0.16,
              0.18,
              0.2,
              0.22,
              0.24,
              0.28
            ],
            "lv": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "originSkillTypeIn",
                    "skillTypes": [
                      "comboSkill"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_funnel_0014_up",
                        "target": "party",
                        "source": "eventSource",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "dmg_up": {
                            "kind": "blackboard",
                            "key": "dmg_up"
                          },
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          },
                          "lv": {
                            "kind": "blackboard",
                            "key": "lv"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:1:sequence:0",
          "abilityEvent": "beforeOutputPhysicalInfliction",
          "priority": 0,
          "blackboard": {
            "dmg_up": [
              0.08,
              0.096,
              0.112,
              0.128,
              0.144,
              0.16,
              0.176,
              0.192,
              0.224
            ],
            "duration": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ],
            "hp_up": [
              0.1,
              0.12,
              0.14,
              0.16,
              0.18,
              0.2,
              0.22,
              0.24,
              0.28
            ],
            "lv": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "originSkillTypeIn",
                    "skillTypes": [
                      "comboSkill"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_funnel_0014_up",
                        "target": "party",
                        "source": "eventSource",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "dmg_up": {
                            "kind": "blackboard",
                            "key": "dmg_up"
                          },
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          },
                          "lv": {
                            "kind": "blackboard",
                            "key": "lv"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_artsunit_0014",
  "iconPath": "/weapons/arts-unit/wpn_artsunit_0014.webp"
} as const satisfies WeaponDefinition;

export default definition;
