/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_funnel_0008",
  "rarity": 6,
  "weaponType": "arts-unit",
  "baseAttackAtLevelNodes": [
    50,
    144,
    243,
    342,
    441,
    490
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "main",
          "operation": "flat",
          "value": [
            17,
            30,
            44,
            57,
            71,
            85,
            98,
            112,
            132
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_funnel_0008_magic_damage_taken_up": {
          "stackingType": "highPriority",
          "priority": {
            "blackboardKey": "lv"
          },
          "maxStackCount": 0,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_spell_taken_up",
            "iconPath": "/icons/icon_battle_spell_taken_up.webp",
            "showInHeadBarCommon": true,
            "showInHeadBarAttached": false,
            "showInSquadIcon": false,
            "onlyShowForMainCharacter": false,
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTagIds": [],
          "extendTagIds": [],
          "blackboard": {
            "duration": 0,
            "lv": 0,
            "spell_damage_taken_up": 0
          },
          "attributeModifiers": [],
          "damageModifiers": [
            {
              "enabledSide": "defender",
              "condition": {
                "kind": "eventDamageTypesMatch",
                "damageTypes": [
                  "heat",
                  "electric",
                  "cryo",
                  "nature"
                ]
              },
              "processors": [
                {
                  "kind": "damageScale",
                  "side": "defender",
                  "zone": "normal",
                  "addition": {
                    "blackboardKey": "spell_damage_taken_up"
                  }
                }
              ]
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "artsIntensity",
          "value": [
            10,
            18,
            26,
            34,
            42,
            50,
            58,
            66,
            78
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "secondary",
          "operation": "percent",
          "value": [
            0.1,
            0.12,
            0.14,
            0.16,
            0.18,
            0.2,
            0.22,
            0.24,
            0.28
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeOutputSpellBurst",
          "priority": 0,
          "blackboard": {
            "duration": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ],
            "lv": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9
            ],
            "second_attr_up": [
              0.1,
              0.12,
              0.14,
              0.16,
              0.18,
              0.2,
              0.22,
              0.24,
              0.28
            ],
            "spell_damage_taken_up": [
              0.09,
              0.108,
              0.126,
              0.144,
              0.162,
              0.18,
              0.198,
              0.216,
              0.252
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "applyBuff",
                "parameters": {
                  "buffId": "buff_wpn_funnel_0008_magic_damage_taken_up",
                  "target": "eventTarget",
                  "source": "eventSource",
                  "inheritSourceSkillCastInfo": true,
                  "blackboardAssignments": {
                    "spell_damage_taken_up": {
                      "kind": "blackboard",
                      "key": "spell_damage_taken_up"
                    },
                    "duration": {
                      "kind": "blackboard",
                      "key": "duration"
                    },
                    "lv": {
                      "kind": "blackboard",
                      "key": "lv"
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_artsunit_0010",
  "iconPath": "/weapons/arts-unit/wpn_artsunit_0010.webp"
} as const satisfies WeaponDefinition;

export default definition;
