/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_funnel_0014",
  "rarity": 5,
  "weaponType": "arts-unit",
  "baseAttackAtLevelNodes": [
    42,
    120,
    203,
    286,
    369,
    411
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "intellect",
          "operation": "flat",
          "value": [
            16,
            28,
            41,
            54,
            67,
            80,
            92,
            105,
            124
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_funnel_0014_up": {
          "stackingType": "highPriorityWithMaxStack",
          "priority": 1,
          "maxStackCount": 1,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_atk_up",
            "iconPath": "/icons/icon_battle_buff_atk_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "dmg_up": 0,
            "duration": 0,
            "lv": 0
          },
          "attributeModifiers": [
            {
              "attribute": "heatDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "dmg_up"
              }
            },
            {
              "attribute": "electricDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "dmg_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "artsIntensity",
          "value": [
            8,
            14,
            20,
            27,
            33,
            40,
            46,
            52,
            62
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "healthPercent",
          "value": [
            0.10000000149011612,
            0.11999999731779099,
            0.14000000059604645,
            0.1599999964237213,
            0.18000000715255737,
            0.20000000298023224,
            0.2199999988079071,
            0.23999999463558197,
            0.2800000011920929
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeOutputSpellBurst",
          "priority": 0,
          "blackboard": {
            "dmg_up": [
              0.07999999821186066,
              0.09600000083446503,
              0.1120000034570694,
              0.12800000607967377,
              0.14399999380111694,
              0.1599999964237213,
              0.17599999904632568,
              0.19200000166893005,
              0.2240000069141388
            ],
            "duration": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ],
            "hp_up": [
              0.10000000149011612,
              0.11999999731779099,
              0.14000000059604645,
              0.1599999964237213,
              0.18000000715255737,
              0.20000000298023224,
              0.2199999988079071,
              0.23999999463558197,
              0.2800000011920929
            ],
            "lv": 1
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "originSkillTypeIn",
                    "skillTypes": [
                      "comboSkill"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_funnel_0014_up",
                        "target": "party",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "dmg_up": {
                            "kind": "blackboard",
                            "key": "dmg_up"
                          },
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          },
                          "lv": {
                            "kind": "blackboard",
                            "key": "lv"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:1:sequence:0",
          "abilityEvent": "beforeOutputPhysicalInfliction",
          "priority": 0,
          "blackboard": {
            "dmg_up": [
              0.07999999821186066,
              0.09600000083446503,
              0.1120000034570694,
              0.12800000607967377,
              0.14399999380111694,
              0.1599999964237213,
              0.17599999904632568,
              0.19200000166893005,
              0.2240000069141388
            ],
            "duration": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ],
            "hp_up": [
              0.10000000149011612,
              0.11999999731779099,
              0.14000000059604645,
              0.1599999964237213,
              0.18000000715255737,
              0.20000000298023224,
              0.2199999988079071,
              0.23999999463558197,
              0.2800000011920929
            ],
            "lv": 1
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "originSkillTypeIn",
                    "skillTypes": [
                      "comboSkill"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_funnel_0014_up",
                        "target": "party",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "dmg_up": {
                            "kind": "blackboard",
                            "key": "dmg_up"
                          },
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          },
                          "lv": {
                            "kind": "blackboard",
                            "key": "lv"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_artsunit_0014",
  "iconPath": "/weapons/arts-unit/wpn_artsunit_0014.webp"
} as const satisfies WeaponDefinition;

export default definition;
