/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_lance_0012",
  "rarity": 6,
  "weaponType": "polearm",
  "baseAttackAtLevelNodes": [
    51,
    146,
    247,
    348,
    449,
    500
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "agility",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_lance_0012_attribute": {
          "stackingType": "refresh",
          "priority": 0,
          "maxStackCount": {
            "blackboardKey": "max_stack"
          },
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_primary_attribute_all_up",
            "iconPath": "/icons/icon_battle_primary_attribute_all_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "all_attr_up": 0,
            "duration": 0
          },
          "attributeModifiers": [
            {
              "attribute": "intellect",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "all_attr_up"
              }
            },
            {
              "attribute": "will",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "all_attr_up"
              }
            },
            {
              "attribute": "agility",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "all_attr_up"
              }
            },
            {
              "attribute": "strength",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "all_attr_up"
              }
            }
          ]
        },
        "buff_wpn_lance_0012_attribute2": {
          "stackingType": "refresh",
          "priority": 0,
          "maxStackCount": {
            "blackboardKey": "max_stack"
          },
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_primary_attribute_all_up",
            "iconPath": "/icons/icon_battle_primary_attribute_all_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "all_attr_up2": 0,
            "duration": 0
          },
          "attributeModifiers": [
            {
              "attribute": "intellect",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "all_attr_up2"
              }
            },
            {
              "attribute": "will",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "all_attr_up2"
              }
            },
            {
              "attribute": "agility",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "all_attr_up2"
              }
            },
            {
              "attribute": "strength",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "all_attr_up2"
              }
            }
          ]
        },
        "buff_wpn_lance_0012_noguard": {
          "stackingType": "unique",
          "priority": 0,
          "maxStackCount": 0,
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "dmg_up": 0
          },
          "attributeModifiers": [],
          "damageModifiers": [
            {
              "enabledSide": "attacker",
              "condition": {
                "kind": "buffIdCountCompare",
                "target": "enemy",
                "buffIds": [
                  "buff_physical_no_guard"
                ],
                "operator": "greaterOrEqual",
                "value": 1
              },
              "processors": [
                {
                  "kind": "damageScale",
                  "side": "attacker",
                  "zone": "normal",
                  "addition": {
                    "blackboardKey": "dmg_up"
                  }
                }
              ]
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "physical",
          "slot": "baseAddition",
          "value": [
            0.055555556,
            0.1,
            0.14444445,
            0.18888889,
            0.23333333,
            0.2777778,
            0.32222223,
            0.36666667,
            0.43333334
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeOutputBuff",
          "priority": 0,
          "blackboard": {
            "all_attr_up": [
              0.08,
              0.096,
              0.112,
              0.128,
              0.144,
              0.16,
              0.176,
              0.192,
              0.224
            ],
            "all_attr_up2": [
              0.08,
              0.096,
              0.112,
              0.128,
              0.144,
              0.16,
              0.176,
              0.192,
              0.224
            ],
            "cd": 0.1,
            "dmg_up": [
              0.2,
              0.24,
              0.28,
              0.32,
              0.36,
              0.4,
              0.44,
              0.48,
              0.56
            ],
            "duration": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTags": [
                      "Skill/Character/Common/Affixes/Vulnerable/VulnerablePhysic"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "originSkillTypeIn",
                          "skillTypes": [
                            "battleSkill"
                          ]
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "conditional",
                            "parameters": {
                              "condition": {
                                "kind": "not",
                                "condition": {
                                  "kind": "timedMarkerPresent",
                                  "target": "caster",
                                  "markerId": "wpn_lance_0012_2"
                                }
                              }
                            },
                            "whenTrue": {
                              "steps": [
                                {
                                  "kind": "applyBuff",
                                  "parameters": {
                                    "buffId": "buff_wpn_lance_0012_attribute2",
                                    "target": "eventSource",
                                    "source": "eventSource",
                                    "inheritSourceSkillCastInfo": true,
                                    "asChildBuff": true,
                                    "blackboardAssignments": {
                                      "all_attr_up2": {
                                        "kind": "blackboard",
                                        "key": "all_attr_up2"
                                      },
                                      "duration": {
                                        "kind": "blackboard",
                                        "key": "duration"
                                      }
                                    }
                                  }
                                },
                                {
                                  "kind": "createTimedMarker",
                                  "parameters": {
                                    "target": "caster",
                                    "markerId": "wpn_lance_0012_2",
                                    "durationSeconds": {
                                      "kind": "blackboard",
                                      "key": "cd"
                                    },
                                    "autoFinishByAction": false
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:0:sequence:1",
          "abilityEvent": "beforeOutputBuff",
          "priority": 0,
          "blackboard": {
            "all_attr_up": [
              0.08,
              0.096,
              0.112,
              0.128,
              0.144,
              0.16,
              0.176,
              0.192,
              0.224
            ],
            "all_attr_up2": [
              0.08,
              0.096,
              0.112,
              0.128,
              0.144,
              0.16,
              0.176,
              0.192,
              0.224
            ],
            "cd": 0.1,
            "dmg_up": [
              0.2,
              0.24,
              0.28,
              0.32,
              0.36,
              0.4,
              0.44,
              0.48,
              0.56
            ],
            "duration": [
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTags": [
                      "Skill/Character/Common/NoGuard"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "originSkillTypeIn",
                          "skillTypes": [
                            "battleSkill"
                          ]
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "conditional",
                            "parameters": {
                              "condition": {
                                "kind": "not",
                                "condition": {
                                  "kind": "timedMarkerPresent",
                                  "target": "caster",
                                  "markerId": "wpn_lance_0012"
                                }
                              }
                            },
                            "whenTrue": {
                              "steps": [
                                {
                                  "kind": "applyBuff",
                                  "parameters": {
                                    "buffId": "buff_wpn_lance_0012_attribute",
                                    "target": "eventSource",
                                    "source": "eventSource",
                                    "inheritSourceSkillCastInfo": true,
                                    "asChildBuff": true,
                                    "blackboardAssignments": {
                                      "all_attr_up": {
                                        "kind": "blackboard",
                                        "key": "all_attr_up"
                                      },
                                      "duration": {
                                        "kind": "blackboard",
                                        "key": "duration"
                                      }
                                    }
                                  }
                                },
                                {
                                  "kind": "createTimedMarker",
                                  "parameters": {
                                    "target": "caster",
                                    "markerId": "wpn_lance_0012",
                                    "durationSeconds": {
                                      "kind": "blackboard",
                                      "key": "cd"
                                    },
                                    "autoFinishByAction": false
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ],
      "initializationBlackboard": {
        "install_0_dmg_up": [
          0.2,
          0.24,
          0.28,
          0.32,
          0.36,
          0.4,
          0.44,
          0.48,
          0.56
        ]
      },
      "initializationSequence": {
        "steps": [
          {
            "kind": "applyBuff",
            "parameters": {
              "buffId": "buff_wpn_lance_0012_noguard",
              "target": "caster",
              "blackboardAssignments": {
                "dmg_up": {
                  "kind": "blackboard",
                  "key": "install_0_dmg_up"
                }
              }
            }
          }
        ]
      }
    }
  ],
  "assetSlug": "wpn_polearm_0012",
  "iconPath": "/weapons/polearm/wpn_polearm_0012.webp"
} as const satisfies WeaponDefinition;

export default definition;
