/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_lance_0015",
  "rarity": 6,
  "weaponType": "polearm",
  "baseAttackAtLevelNodes": [
    51,
    146,
    247,
    348,
    449,
    500
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "agility",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_lance_0015_atkup": {
          "stackingType": "refresh",
          "priority": {
            "blackboardKey": "pd_up"
          },
          "maxStackCount": {
            "blackboardKey": "max_stack"
          },
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_atk_up",
            "iconPath": "/icons/icon_battle_buff_atk_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTagIds": [],
          "extendTagIds": [],
          "blackboard": {
            "atk_up": 0.1,
            "duration": 0
          },
          "attributeModifiers": [
            {
              "attribute": "Atk",
              "slot": "baseMultiplier",
              "value": {
                "blackboardKey": "atk_up"
              }
            }
          ]
        },
        "buff_wpn_lance_0015_dmgup": {
          "stackingType": "refresh",
          "priority": {
            "blackboardKey": "pd_up"
          },
          "maxStackCount": {
            "blackboardKey": "max_stack"
          },
          "durationSeconds": {
            "blackboardKey": "duration2"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_atk_up",
            "iconPath": "/icons/icon_battle_buff_atk_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTagIds": [],
          "extendTagIds": [],
          "blackboard": {
            "dmg_up": 0.1,
            "duration2": 0
          },
          "attributeModifiers": [
            {
              "attribute": "heatDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "dmg_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "heat",
          "slot": "baseAddition",
          "value": [
            0.055555556,
            0.1,
            0.14444445,
            0.18888889,
            0.23333333,
            0.2777778,
            0.32222223,
            0.36666667,
            0.43333334
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "ultimateEnergyGainEfficiency",
          "value": [
            0.18,
            0.216,
            0.252,
            0.288,
            0.324,
            0.36,
            0.396,
            0.432,
            0.504
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "event": {
            "kind": "spGained"
          },
          "priority": 0,
          "blackboard": {
            "atk_up": [
              0.06,
              0.072,
              0.084,
              0.096,
              0.108,
              0.12,
              0.132,
              0.144,
              0.168
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "duration2": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "fire_dmg_up": [
              0.06,
              0.072,
              0.084,
              0.096,
              0.108,
              0.12,
              0.132,
              0.144,
              0.168
            ],
            "ultimate_gain_up": [
              0.18,
              0.216,
              0.252,
              0.288,
              0.324,
              0.36,
              0.396,
              0.432,
              0.504
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventSpGainMatch",
                    "sources": [
                      "skill"
                    ],
                    "gainKinds": [
                      "gain"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_lance_0015_atkup",
                        "target": "party",
                        "source": "eventSource",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "atk_up": {
                            "kind": "blackboard",
                            "key": "atk_up"
                          },
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:1:sequence:0",
          "abilityEvent": "beforeOutputInfliction",
          "priority": 0,
          "blackboard": {
            "atk_up": [
              0.06,
              0.072,
              0.084,
              0.096,
              0.108,
              0.12,
              0.132,
              0.144,
              0.168
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "duration2": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "fire_dmg_up": [
              0.06,
              0.072,
              0.084,
              0.096,
              0.108,
              0.12,
              0.132,
              0.144,
              0.168
            ],
            "ultimate_gain_up": [
              0.18,
              0.216,
              0.252,
              0.288,
              0.324,
              0.36,
              0.396,
              0.432,
              0.504
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "originSkillTypeIn",
                    "skillTypes": [
                      "battleSkill",
                      "comboSkill",
                      "ultimate"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "eventInflictionElementIn",
                          "elements": [
                            "heat"
                          ]
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_lance_0015_dmgup",
                              "target": "party",
                              "source": "eventSource",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "dmg_up": {
                                  "kind": "blackboard",
                                  "key": "fire_dmg_up"
                                },
                                "duration2": {
                                  "kind": "blackboard",
                                  "key": "duration2"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_polearm_0015",
  "iconPath": "/weapons/polearm/wpn_polearm_0015.webp"
} as const satisfies WeaponDefinition;

export default definition;
