/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_sword_0019",
  "rarity": 5,
  "weaponType": "sword",
  "baseAttackAtLevelNodes": [
    42,
    120,
    203,
    286,
    369,
    411
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "agility",
          "operation": "flat",
          "value": [
            16,
            28,
            41,
            54,
            67,
            80,
            92,
            105,
            124
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_sword_0019_up": {
          "stackingType": "highPriorityWithMaxStack",
          "priority": 1,
          "maxStackCount": {
            "blackboardKey": "max_stack"
          },
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_atk_up",
            "iconPath": "/icons/icon_battle_buff_atk_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "dmg_up": 0,
            "duration": 0,
            "max_stack": 0
          },
          "attributeModifiers": [
            {
              "attribute": "heatDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "dmg_up"
              }
            },
            {
              "attribute": "electricDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "dmg_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "attackPercent",
          "value": [
            0.04,
            0.072,
            0.104,
            0.136,
            0.168,
            0.2,
            0.232,
            0.264,
            0.312
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "secondary",
          "operation": "percent",
          "value": [
            0.05,
            0.06,
            0.07,
            0.08,
            0.09,
            0.1,
            0.11,
            0.12,
            0.14
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "event": {
            "kind": "spGained"
          },
          "priority": 0,
          "blackboard": {
            "dmg_up": [
              0.03,
              0.036,
              0.042,
              0.048,
              0.054,
              0.06,
              0.066,
              0.072,
              0.084
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "max_stack": [
              3,
              3,
              3,
              3,
              3,
              3,
              3,
              3,
              3
            ],
            "second_attr_up": [
              0.05,
              0.06,
              0.07,
              0.08,
              0.09,
              0.1,
              0.11,
              0.12,
              0.14
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventSpGainMatch",
                    "sources": [
                      "skill"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_sword_0019_up",
                        "target": "party",
                        "source": "eventSource",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "dmg_up": {
                            "kind": "blackboard",
                            "key": "dmg_up"
                          },
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          },
                          "max_stack": {
                            "kind": "blackboard",
                            "key": "max_stack"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_sword_0019",
  "iconPath": "/weapons/sword/wpn_sword_0019.webp"
} as const satisfies WeaponDefinition;

export default definition;
