/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_sword_0021",
  "rarity": 6,
  "weaponType": "sword",
  "baseAttackAtLevelNodes": [
    51,
    146,
    247,
    348,
    449,
    500
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "agility",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_sword_0021_exist": {
          "stackingType": "overwriteDuration",
          "priority": 0,
          "maxStackCount": 0,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_weapon_atk_skill_ready",
            "iconPath": "/icons/icon_battle_weapon_atk_skill_ready.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "duration": 0
          },
          "attributeModifiers": []
        },
        "buff_wpn_sword_0021_valid": {
          "stackingType": "unique",
          "priority": 0,
          "maxStackCount": 0,
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "phy_dmg_up": 0
          },
          "attributeModifiers": [
            {
              "attribute": "physicalDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "phy_dmg_up"
              }
            }
          ],
          "lifecycleSequences": {
            "finish": {
              "steps": [
                {
                  "kind": "finishBuffsById",
                  "parameters": {
                    "target": "caster",
                    "buffIds": [
                      "buff_wpn_sword_0021_exist"
                    ],
                    "reason": "other"
                  }
                }
              ]
            }
          }
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "attackPercent",
          "value": [
            0.05000000074505806,
            0.09000000357627869,
            0.12999999523162842,
            0.17000000178813934,
            0.20999999344348907,
            0.25,
            0.28999999165534973,
            0.33000001311302185,
            0.38999998569488525
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "artsIntensity",
          "value": [
            30,
            36,
            42,
            48,
            54,
            60,
            66,
            72,
            84
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeOutputBuff",
          "priority": 0,
          "blackboard": {
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "phy_dmg_up": [
              0.36000001430511475,
              0.4320000112056732,
              0.5040000081062317,
              0.5759999752044678,
              0.6480000019073486,
              0.7200000286102295,
              0.7919999957084656,
              0.8640000224113464,
              1.0080000162124634
            ],
            "phy_spell_up": [
              30,
              36,
              42,
              48,
              54,
              60,
              66,
              72,
              84
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffIdMatch",
                    "buffIds": [
                      "buff_common_originum_frozen"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_sword_0021_exist",
                        "target": "caster",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:0:sequence:1",
          "abilityEvent": "beforeOutputBuff",
          "priority": 0,
          "blackboard": {
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "phy_dmg_up": [
              0.36000001430511475,
              0.4320000112056732,
              0.5040000081062317,
              0.5759999752044678,
              0.6480000019073486,
              0.7200000286102295,
              0.7919999957084656,
              0.8640000224113464,
              1.0080000162124634
            ],
            "phy_spell_up": [
              30,
              36,
              42,
              48,
              54,
              60,
              66,
              72,
              84
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventBuffTagsMatch",
                    "match": "hasAny",
                    "buffTags": [
                      "Skill/Character/Common/SpellStatus/Frozen"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_sword_0021_exist",
                        "target": "caster",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:1:sequence:0",
          "abilityEvent": "beforeCastSkill",
          "priority": 0,
          "blackboard": {
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "phy_dmg_up": [
              0.36000001430511475,
              0.4320000112056732,
              0.5040000081062317,
              0.5759999752044678,
              0.6480000019073486,
              0.7200000286102295,
              0.7919999957084656,
              0.8640000224113464,
              1.0080000162124634
            ],
            "phy_spell_up": [
              30,
              36,
              42,
              48,
              54,
              60,
              66,
              72,
              84
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventSkillTypeIn",
                    "skillTypes": [
                      "battleSkill",
                      "ultimate"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "buffIdStackCompare",
                          "target": "caster",
                          "buffIds": [
                            "buff_wpn_sword_0021_exist"
                          ],
                          "operator": "greaterOrEqual",
                          "value": {
                            "kind": "constant",
                            "value": 1
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_sword_0021_valid",
                              "target": "caster",
                              "inheritSourceSkillCastInfo": true,
                              "lifetimeOwner": "currentCastSkill",
                              "blackboardAssignments": {
                                "phy_dmg_up": {
                                  "kind": "blackboard",
                                  "key": "phy_dmg_up"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_sword_0021",
  "iconPath": "/weapons/sword/wpn_sword_0021.webp"
} as const satisfies WeaponDefinition;

export default definition;
