/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_sword_0022",
  "rarity": 6,
  "weaponType": "sword",
  "baseAttackAtLevelNodes": [
    51,
    148,
    250,
    352,
    454,
    505
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "agility",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_sword_0022_final": {
          "stackingType": "unique",
          "priority": 0,
          "maxStackCount": 2,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_wpn_sword_0022",
            "iconPath": "/icons/icon_battle_buff_wpn_sword_0022.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "Default",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "dmg_up": 0,
            "duration": 0
          },
          "attributeModifiers": [
            {
              "attribute": "physicalDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "dmg_up"
              }
            },
            {
              "attribute": "heatDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "dmg_up"
              }
            }
          ],
          "lifecycleSequences": {
            "finish": {
              "steps": [
                {
                  "kind": "finishBuffsById",
                  "parameters": {
                    "target": "buffOwner",
                    "buffIds": [
                      "buff_wpn_sword_0022_layer"
                    ],
                    "reason": "other"
                  }
                }
              ]
            }
          }
        },
        "buff_wpn_sword_0022_layer": {
          "stackingType": "stack",
          "priority": 0,
          "maxStackCount": 2,
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_buff_wpn_sword_0022",
            "iconPath": "/icons/icon_battle_buff_wpn_sword_0022.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "Default",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "dmg_up": 0,
            "max_stack": 0
          },
          "attributeModifiers": [
            {
              "attribute": "physicalDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "dmg_up"
              }
            },
            {
              "attribute": "heatDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "dmg_up"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "criticalRate",
          "value": [
            0.02500000037252903,
            0.04500000178813934,
            0.06499999761581421,
            0.08500000089406967,
            0.10499999672174454,
            0.125,
            0.14499999582767487,
            0.16500000655651093,
            0.19499999284744263
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "attackPercent",
          "value": [
            0.1599999964237213,
            0.19200000166893005,
            0.2240000069141388,
            0.25600001215934753,
            0.2879999876022339,
            0.3199999928474426,
            0.35199999809265137,
            0.3840000033378601,
            0.4480000138282776
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "outputCriticalDamage",
          "priority": 0,
          "blackboard": {
            "atk_up": [
              0.1599999964237213,
              0.19200000166893005,
              0.2240000069141388,
              0.25600001215934753,
              0.2879999876022339,
              0.3199999928474426,
              0.35199999809265137,
              0.3840000033378601,
              0.4480000138282776
            ],
            "dmg_up": [
              0.009999999776482582,
              0.012000000104308128,
              0.014000000432133675,
              0.01600000075995922,
              0.017999999225139618,
              0.019999999552965164,
              0.02199999988079071,
              0.024000000208616257,
              0.02800000086426735
            ],
            "dmg_up2": [
              0.23999999463558197,
              0.2879999876022339,
              0.335999995470047,
              0.3840000033378601,
              0.4320000112056732,
              0.47999998927116394,
              0.527999997138977,
              0.5759999752044678,
              0.671999990940094
            ],
            "duration": [
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20
            ],
            "max_stack": [
              16,
              16,
              16,
              16,
              16,
              16,
              16,
              16,
              16
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "applyBuff",
                "parameters": {
                  "buffId": "buff_wpn_sword_0022_layer",
                  "target": "caster",
                  "inheritSourceSkillCastInfo": true,
                  "asChildBuff": true,
                  "blackboardAssignments": {
                    "dmg_up": {
                      "kind": "blackboard",
                      "key": "dmg_up"
                    },
                    "max_stack": {
                      "kind": "blackboard",
                      "key": "max_stack"
                    }
                  }
                }
              },
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "buffIdStackCompare",
                    "target": "caster",
                    "buffIds": [
                      "buff_wpn_sword_0022_layer"
                    ],
                    "operator": "greaterOrEqual",
                    "value": {
                      "kind": "blackboard",
                      "key": "max_stack"
                    }
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "buffIdStackCompare",
                          "target": "caster",
                          "buffIds": [
                            "buff_wpn_sword_0022_final"
                          ],
                          "operator": "less",
                          "value": {
                            "kind": "constant",
                            "value": 1
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_sword_0022_final",
                              "target": "caster",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "dmg_up": {
                                  "kind": "blackboard",
                                  "key": "dmg_up2"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_sword_0022",
  "iconPath": "/weapons/sword/wpn_sword_0022.webp"
} as const satisfies WeaponDefinition;

export default definition;
