/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_sword_0015",
  "rarity": 5,
  "weaponType": "sword",
  "baseAttackAtLevelNodes": [
    42,
    120,
    203,
    286,
    369,
    411
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "agility",
          "operation": "flat",
          "value": [
            16,
            28,
            41,
            54,
            67,
            80,
            92,
            105,
            124
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_sword_0015_exist": {
          "stackingType": "stack",
          "priority": 1,
          "maxStackCount": 3,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_physical_dmg_up",
            "iconPath": "/icons/icon_battle_physical_dmg_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showDirectlyInHeadBuff": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "LifeTime",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "duration": 0,
            "max_stack": 0
          },
          "attributeModifiers": []
        },
        "buff_wpn_sword_0015_pdi_up": {
          "stackingType": "unique",
          "priority": 0,
          "maxStackCount": 2,
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "phy_dmg_up": 0
          },
          "attributeModifiers": [
            {
              "attribute": "physicalDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "phy_dmg_up"
              }
            }
          ],
          "lifecycleSequences": {
            "finish": {
              "steps": [
                {
                  "kind": "finishBuffsById",
                  "parameters": {
                    "target": "caster",
                    "buffIds": [
                      "buff_wpn_sword_0015_exist"
                    ],
                    "reason": "other"
                  }
                }
              ]
            }
          }
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "physical",
          "slot": "baseAddition",
          "value": [
            0.04444444552063942,
            0.07999999821186066,
            0.11555555462837219,
            0.15111111104488373,
            0.18666666746139526,
            0.2222222238779068,
            0.25777778029441833,
            0.2933333218097687,
            0.3466666638851166
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "ultimate",
          "slot": "baseAddition",
          "value": [
            0.1599999964237213,
            0.19200000166893005,
            0.2240000069141388,
            0.25600001215934753,
            0.2879999876022339,
            0.3199999928474426,
            0.35199999809265137,
            0.3840000033378601,
            0.4480000138282776
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "event": {
            "kind": "physicalInflictionApplied",
            "types": [
              "airborne",
              "knockDown",
              "fracture",
              "crush"
            ],
            "scope": "operator"
          },
          "priority": 0,
          "blackboard": {
            "dmg_up": [
              0.1599999964237213,
              0.19200000166893005,
              0.2240000069141388,
              0.25600001215934753,
              0.2879999876022339,
              0.3199999928474426,
              0.35199999809265137,
              0.3840000033378601,
              0.4480000138282776
            ],
            "duration": [
              30,
              30,
              30,
              30,
              30,
              30,
              30,
              30,
              30
            ],
            "max_stack": [
              3,
              3,
              3,
              3,
              3,
              3,
              3,
              3,
              3
            ],
            "phy_dmg_up": [
              0.11999999731779099,
              0.14399999380111694,
              0.1679999977350235,
              0.19200000166893005,
              0.2160000056028366,
              0.23999999463558197,
              0.2639999985694885,
              0.2879999876022339,
              0.335999995470047
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventPhysicalInflictionTypeIn",
                    "types": [
                      "airborne"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "not",
                          "condition": {
                            "kind": "timedMarkerPresent",
                            "target": "caster",
                            "markerId": "sk_wpn_sword_0015"
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_sword_0015_exist",
                              "target": "caster",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "lifetimeOwner": "currentCastSkill",
                              "blackboardAssignments": {
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                },
                                "max_stack": {
                                  "kind": "blackboard",
                                  "key": "max_stack"
                                }
                              }
                            }
                          },
                          {
                            "kind": "createTimedMarker",
                            "parameters": {
                              "target": "caster",
                              "markerId": "sk_wpn_sword_0015",
                              "durationSeconds": {
                                "kind": "constant",
                                "value": 0.5
                              },
                              "autoFinishByAction": false
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:1:sequence:0",
          "abilityEvent": "beforeCastSkill",
          "priority": 0,
          "blackboard": {
            "dmg_up": [
              0.1599999964237213,
              0.19200000166893005,
              0.2240000069141388,
              0.25600001215934753,
              0.2879999876022339,
              0.3199999928474426,
              0.35199999809265137,
              0.3840000033378601,
              0.4480000138282776
            ],
            "duration": [
              30,
              30,
              30,
              30,
              30,
              30,
              30,
              30,
              30
            ],
            "max_stack": [
              3,
              3,
              3,
              3,
              3,
              3,
              3,
              3,
              3
            ],
            "phy_dmg_up": [
              0.11999999731779099,
              0.14399999380111694,
              0.1679999977350235,
              0.19200000166893005,
              0.2160000056028366,
              0.23999999463558197,
              0.2639999985694885,
              0.2879999876022339,
              0.335999995470047
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "eventSkillTypeIn",
                    "skillTypes": [
                      "ultimate"
                    ]
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "readBuffStackCount",
                      "parameters": {
                        "target": "caster",
                        "outputKey": "count",
                        "query": {
                          "kind": "id",
                          "buffIds": [
                            "buff_wpn_sword_0015_exist"
                          ]
                        }
                      }
                    },
                    {
                      "kind": "calculateActionValue",
                      "parameters": {
                        "key": "phy_dmg",
                        "operation": "multiply",
                        "left": {
                          "kind": "blackboard",
                          "key": "phy_dmg_up"
                        },
                        "right": {
                          "kind": "blackboard",
                          "key": "count"
                        }
                      }
                    },
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_sword_0015_pdi_up",
                        "target": "caster",
                        "inheritSourceSkillCastInfo": true,
                        "lifetimeOwner": "currentCastSkill",
                        "blackboardAssignments": {
                          "phy_dmg_up": {
                            "kind": "blackboard",
                            "key": "phy_dmg"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_sword_0015",
  "iconPath": "/weapons/sword/wpn_sword_0015.webp"
} as const satisfies WeaponDefinition;

export default definition;
