/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_sword_0007",
  "rarity": 5,
  "weaponType": "sword",
  "baseAttackAtLevelNodes": [
    42,
    120,
    203,
    286,
    369,
    411
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "intellect",
          "operation": "flat",
          "value": [
            16,
            28,
            41,
            54,
            67,
            80,
            92,
            105,
            124
          ]
        }
      ]
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "ultimateEnergyGainEfficiency",
          "value": [
            0.0476190485060215,
            0.08571428805589676,
            0.12380952388048172,
            0.16190476715564728,
            0.20000000298023224,
            0.2380952388048172,
            0.27619048953056335,
            0.3142857253551483,
            0.37142857909202576
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "attackPercent",
          "value": [
            0.05000000074505806,
            0.05999999865889549,
            0.07000000029802322,
            0.07999999821186066,
            0.09000000357627869,
            0.10000000149011612,
            0.10999999940395355,
            0.11999999731779099,
            0.14000000059604645
          ]
        },
        {
          "kind": "panelStat",
          "stat": "artsIntensity",
          "value": [
            25,
            30,
            35,
            40,
            45,
            50,
            55,
            60,
            70
          ]
        }
      ]
    }
  ],
  "assetSlug": "wpn_sword_0007",
  "iconPath": "/weapons/sword/wpn_sword_0007.webp"
} as const satisfies WeaponDefinition;

export default definition;
