/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';

const definition = {
  "slug": "wpn_funnel_0020",
  "rarity": 6,
  "weaponType": "arts-unit",
  "baseAttackAtLevelNodes": [
    50,
    144,
    243,
    342,
    441,
    490
  ],
  "traits": [
    {
      "key": "skill1",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "attribute",
          "attribute": "agility",
          "operation": "flat",
          "value": [
            20,
            36,
            52,
            68,
            84,
            100,
            116,
            132,
            156
          ]
        }
      ],
      "buffDefinitions": {
        "buff_wpn_funnel_0020_intensityup": {
          "stackingType": "highPriorityWithMaxStack",
          "priority": 0,
          "maxStackCount": 4,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_natural_dmg_up",
            "iconPath": "/icons/icon_battle_natural_dmg_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "Default",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "duration": 25,
            "nature_dmg_up": 0.02
          },
          "attributeModifiers": [
            {
              "attribute": "natureDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "nature_dmg_up"
              }
            }
          ]
        },
        "buff_wpn_funnel_0020_maxup": {
          "stackingType": "refresh",
          "priority": 0,
          "maxStackCount": 0,
          "durationSeconds": {
            "blackboardKey": "duration"
          },
          "triggerIntervalSeconds": 0,
          "waitFirstTriggerInterval": true,
          "maxTriggerCount": 1,
          "presentation": {
            "visible": true,
            "iconId": "icon_battle_natural_dmg_up",
            "iconPath": "/icons/icon_battle_natural_dmg_up.webp",
            "showInHeadBarCommon": false,
            "showInHeadBarAttached": false,
            "showInSquadIcon": true,
            "onlyShowForMainCharacter": false,
            "blinkInMainCharHpBar": false,
            "showProgressInHpBar": false,
            "showProgressInNormalSkillButton": false,
            "useWeakProgressInNormalSkillButton": false,
            "showProgressInUltimateSkillButton": false,
            "forceRaiseIconEvent": false,
            "showWarningBackground": false,
            "playStrongInAnimation": false,
            "hasCharHpBarVfxType": false,
            "charHpBarVfxType": "Fire",
            "iconStyleInSquad": "Default",
            "abnormalColorType": "Physical",
            "orderPriority": {
              "useDirectoryValue": false,
              "value": 0,
              "category": "CommonCharBuff"
            }
          },
          "applyTags": [],
          "extendTags": [],
          "blackboard": {
            "duration": 25,
            "nature_dmg_up2": 0.06
          },
          "attributeModifiers": [
            {
              "attribute": "natureDamageIncrease",
              "slot": "baseAddition",
              "value": {
                "blackboardKey": "nature_dmg_up2"
              }
            }
          ]
        }
      }
    },
    {
      "key": "skill2",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "damageScale",
          "target": "nature",
          "slot": "baseAddition",
          "value": [
            0.055555556,
            0.1,
            0.14444445,
            0.18888889,
            0.23333333,
            0.2777778,
            0.32222223,
            0.36666667,
            0.43333334
          ]
        }
      ]
    },
    {
      "key": "skill3",
      "levelCount": 9,
      "modifiers": [
        {
          "kind": "panelStat",
          "stat": "artsIntensity",
          "value": [
            15,
            18,
            21,
            24,
            27,
            30,
            33,
            36,
            42
          ]
        }
      ],
      "eventHandlers": [
        {
          "key": "skill3:event:0:sequence:0",
          "abilityEvent": "beforeOutputSpellBurst",
          "priority": 0,
          "blackboard": {
            "duration": [
              25,
              25,
              25,
              25,
              25,
              25,
              25,
              25,
              25
            ],
            "max_stack": [
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4
            ],
            "nature_dmg_up": [
              0.02,
              0.024,
              0.028,
              0.032,
              0.036,
              0.04,
              0.044,
              0.048,
              0.056
            ],
            "nature_dmg_up2": [
              0.06,
              0.072,
              0.084,
              0.096,
              0.108,
              0.12,
              0.132,
              0.144,
              0.168
            ],
            "phy_spell_up": [
              15,
              18,
              21,
              24,
              27,
              30,
              33,
              36,
              42
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "not",
                    "condition": {
                      "kind": "timedMarkerPresent",
                      "target": "caster",
                      "markerId": "sk_wpn_funnel_0020"
                    }
                  }
                },
                "whenTrue": {
                  "steps": [
                    {
                      "kind": "applyBuff",
                      "parameters": {
                        "buffId": "buff_wpn_funnel_0020_intensityup",
                        "target": "caster",
                        "inheritSourceSkillCastInfo": true,
                        "asChildBuff": true,
                        "blackboardAssignments": {
                          "nature_dmg_up": {
                            "kind": "blackboard",
                            "key": "nature_dmg_up"
                          },
                          "duration": {
                            "kind": "blackboard",
                            "key": "duration"
                          }
                        }
                      }
                    },
                    {
                      "kind": "createTimedMarker",
                      "parameters": {
                        "target": "caster",
                        "markerId": "sk_wpn_funnel_0020",
                        "durationSeconds": {
                          "kind": "constant",
                          "value": 0.1
                        },
                        "autoFinishByAction": false
                      }
                    },
                    {
                      "kind": "conditional",
                      "parameters": {
                        "condition": {
                          "kind": "buffIdStackCompare",
                          "target": "caster",
                          "buffIds": [
                            "buff_wpn_funnel_0020_intensityup"
                          ],
                          "operator": "greaterOrEqual",
                          "value": {
                            "kind": "constant",
                            "value": 4
                          }
                        }
                      },
                      "whenTrue": {
                        "steps": [
                          {
                            "kind": "applyBuff",
                            "parameters": {
                              "buffId": "buff_wpn_funnel_0020_maxup",
                              "target": "caster",
                              "inheritSourceSkillCastInfo": true,
                              "asChildBuff": true,
                              "blackboardAssignments": {
                                "nature_dmg_up2": {
                                  "kind": "blackboard",
                                  "key": "nature_dmg_up2"
                                },
                                "duration": {
                                  "kind": "blackboard",
                                  "key": "duration"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "skill3:event:1:sequence:0",
          "abilityEvent": "buffEnhanceChanged",
          "priority": 0,
          "blackboard": {
            "duration": [
              25,
              25,
              25,
              25,
              25,
              25,
              25,
              25,
              25
            ],
            "max_stack": [
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4
            ],
            "nature_dmg_up": [
              0.02,
              0.024,
              0.028,
              0.032,
              0.036,
              0.04,
              0.044,
              0.048,
              0.056
            ],
            "nature_dmg_up2": [
              0.06,
              0.072,
              0.084,
              0.096,
              0.108,
              0.12,
              0.132,
              0.144,
              0.168
            ],
            "phy_spell_up": [
              15,
              18,
              21,
              24,
              27,
              30,
              33,
              36,
              42
            ]
          },
          "sequence": {
            "steps": [
              {
                "kind": "conditional",
                "parameters": {
                  "condition": {
                    "kind": "buffIdStackCompare",
                    "target": "caster",
                    "buffIds": [
                      "buff_wpn_funnel_0020_intensityup"
                    ],
                    "operator": "greaterOrEqual",
                    "value": {
                      "kind": "constant",
                      "value": 4
                    }
                  },
                  "alwaysNext": true
                },
                "whenTrue": {
                  "steps": []
                },
                "whenFalse": {
                  "steps": [
                    {
                      "kind": "finishBuffsById",
                      "parameters": {
                        "target": "caster",
                        "buffIds": [
                          "buff_wpn_funnel_0020_maxup"
                        ],
                        "reason": "other"
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "assetSlug": "wpn_artsunit_0020",
  "iconPath": "/weapons/arts-unit/wpn_artsunit_0020.webp"
} as const satisfies WeaponDefinition;

export default definition;
