/** 当前公共投影已审计的游戏原生 AbilityEvent 名称。 */
export const NATIVE_ABILITY_EVENT_NAMES = [
  'OnOwnerHpZero',
  'OnOwnerDead',
  'OnOwnerSwitchToCenter',
  'OnOwnerSwitchToGuard',
  'OnCustomAbilityEvent',
  'OnEnterFight',
  'OnAddedBuff',
  'OnSkillInterrupted',
  'OnTakeDamage',
  'OnOutputDamage',
  'OnPoiseZero',
  'OnBeforeCastSkill',
  'OnSkillEnd',
  'OnExitFight',
  'OnBeforeOutputAirborne',
  'OnAfterOutputAirborne',
  'OnPartsDisable',
  'OnPartsBeHit',
  'OnTakePoiseDamage',
  'OnBeforeOutputKnockDown',
  'OnAfterOutputKnockDown',
  'OnTakeCriticalDamage',
  'OnOutputCriticalDamage',
  'OnReceiveHeal',
  'OnOutputHeal',
  'OnAfterCharacterTakeBlowOff',
  'OnBeforeTakePhysicalInfliction',
  'OnAfterTakePhysicalInfliction',
  'OnBeforeTakeDamage',
  'OnOutputBuff',
  'OnBeforeDamageAction',
  'OnEnemyBeforeTakeSpellInfliction',
  'OnCharBeforeTakeSpellInfliction',
  'OnCharBeforeOutputSpellInfliction',
  'OnCharBeforeOutputSpellBurst',
  'OnCharAfterOutputSpellInfliction',
  'OnEnemyAfterTakeSpellInfliction',
  'OnAfterOutputWeaknessTriggered',
  'OnSetWeakness',
  'OnObtainAtb',
  'OnAfterSkillApplyCost',
  'OnCollectAddedBuffBbValue',
  'OnCollectOutputBuffBbValue',
  'OnFinishedBuff',
  'OnBuffEndsEarly',
  'OnBeforeAddedBuff',
  'OnBeforeOutputBuff',
  'OnConsumeBuff',
  'OnAbsorbBuff',
  'OnBuffEnhanceChanged',
  'OnSquadTakeDamage',
  'OnCharDeckAttrChanged',
  'OnTrulyExitFight',
  'OnAfterKillEntity',
  'OnPoiseKnotBreak',
  'OnAbilityEntitySpawned',
  'OnAbilityEntityFinished',
  'OnBeforeCalculateDamage',
  'OnBeforeOutputDamage',
  'OnBeforeOutputPhysicalInfliction',
  'OnAfterOutputPhysicalInfliction',
  'OnRemoveAllPendingComboSkill',
  'OnSquadRepatriate',
  'OnBeforePartDisable',
] as const;

export type NativeAbilityEventName = (typeof NATIVE_ABILITY_EVENT_NAMES)[number];

const NATIVE_ABILITY_EVENT_IDS: Readonly<Record<number, NativeAbilityEventName>> = {
  1: 'OnOwnerHpZero',
  2: 'OnOwnerSwitchToCenter',
  3: 'OnOwnerSwitchToGuard',
  5: 'OnCustomAbilityEvent',
  6: 'OnEnterFight',
  7: 'OnExitFight',
  8: 'OnOwnerDead',
  9: 'OnAddedBuff',
  12: 'OnTakeDamage',
  13: 'OnOutputDamage',
  21: 'OnPoiseZero',
  30: 'OnBeforeCastSkill',
  31: 'OnSkillEnd',
  32: 'OnSkillInterrupted',
  40: 'OnBeforeOutputKnockDown',
  41: 'OnAfterOutputKnockDown',
  43: 'OnTakeCriticalDamage',
  44: 'OnOutputCriticalDamage',
  45: 'OnReceiveHeal',
  47: 'OnAfterCharacterTakeBlowOff',
  50: 'OnOutputHeal',
  55: 'OnBeforeOutputAirborne',
  56: 'OnAfterOutputAirborne',
  59: 'OnBeforeTakePhysicalInfliction',
  60: 'OnAfterTakePhysicalInfliction',
  64: 'OnSquadTakeDamage',
  101: 'OnBeforeTakeDamage',
  81: 'OnPartsDisable',
  82: 'OnPartsBeHit',
  102: 'OnOutputBuff',
  104: 'OnBeforeDamageAction',
  121: 'OnEnemyBeforeTakeSpellInfliction',
  122: 'OnCharBeforeTakeSpellInfliction',
  126: 'OnCharBeforeOutputSpellInfliction',
  127: 'OnCharBeforeOutputSpellBurst',
  129: 'OnCharAfterOutputSpellInfliction',
  130: 'OnEnemyAfterTakeSpellInfliction',
  141: 'OnAfterOutputWeaknessTriggered',
  142: 'OnObtainAtb',
  143: 'OnAfterSkillApplyCost',
  150: 'OnTrulyExitFight',
  151: 'OnSetWeakness',
  155: 'OnCharDeckAttrChanged',
  201: 'OnCollectAddedBuffBbValue',
  202: 'OnCollectOutputBuffBbValue',
  203: 'OnFinishedBuff',
  204: 'OnBuffEndsEarly',
  205: 'OnBeforeAddedBuff',
  206: 'OnBeforeOutputBuff',
  208: 'OnConsumeBuff',
  209: 'OnBuffEnhanceChanged',
  211: 'OnAbsorbBuff',
  222: 'OnAfterKillEntity',
  241: 'OnPoiseKnotBreak',
  243: 'OnTakePoiseDamage',
  261: 'OnAbilityEntitySpawned',
  262: 'OnAbilityEntityFinished',
  301: 'OnBeforeCalculateDamage',
  302: 'OnBeforeOutputDamage',
  401: 'OnBeforeOutputPhysicalInfliction',
  402: 'OnAfterOutputPhysicalInfliction',
  1401: 'OnRemoveAllPendingComboSkill',
  1402: 'OnSquadRepatriate',
  1403: 'OnBeforePartDisable',
};

const NATIVE_ABILITY_EVENT_NAME_SET = new Set<string>(NATIVE_ABILITY_EVENT_NAMES);

/** 在来源边界统一 VFS 整数与历史 JSON 枚举名。 */
export function parseNativeAbilityEventName(
  event: unknown,
  sourcePath: string,
): NativeAbilityEventName {
  const name =
    typeof event === 'number' && Number.isInteger(event)
      ? NATIVE_ABILITY_EVENT_IDS[event]
      : typeof event === 'string'
        ? event
        : undefined;
  if (name === undefined || !NATIVE_ABILITY_EVENT_NAME_SET.has(name)) {
    throw new Error(`${sourcePath}: unsupported ability event ${JSON.stringify(event)}`);
  }
  return name as NativeAbilityEventName;
}
