import type {
  CompiledWeaponRuntimeDefinitionBatchSource,
  CompiledWeaponRuntimeDefinitionSource,
} from './runtimeDefinition.ts';

export interface RenderedWeaponDefinitionFileSource {
  readonly relativePath: string;
  readonly content: string;
}

const SAFE_PATH_SEGMENT = /^[A-Za-z0-9_-]+$/;

/** 按武器类型和稳定 ID 输出单文件；渲染层不重新解释任何游戏语义。 */
export function renderWeaponDefinitionFiles(
  batch: CompiledWeaponRuntimeDefinitionBatchSource,
): readonly RenderedWeaponDefinitionFileSource[] {
  const blocked = batch.diagnostics.filter(item => item.status === 'blocked');
  if (blocked.length > 0) {
    throw new Error(`cannot render weapon definitions with ${blocked.length} blocked diagnostics`);
  }
  const definitions = [...batch.definitions].sort((left, right) =>
    left.slug.localeCompare(right.slug),
  );
  const seen = new Set<string>();
  const files: RenderedWeaponDefinitionFileSource[] = [];
  const imports: string[] = [];
  for (const [index, definition] of definitions.entries()) {
    requireSafeSegment(definition.slug, `weapon definition '${definition.slug}'.slug`);
    requireSafeSegment(definition.weaponType, `weapon definition '${definition.slug}'.weaponType`);
    if (seen.has(definition.slug)) {
      throw new Error(`duplicate rendered weapon definition ${JSON.stringify(definition.slug)}`);
    }
    seen.add(definition.slug);
    const exportName = `generatedWeapon${index}`;
    imports.push(
      `import ${exportName} from './${definition.weaponType}/${definition.slug}.generated';`,
    );
    files.push({
      relativePath: `${definition.weaponType}/${definition.slug}.generated.ts`,
      content: renderDefinition(definition),
    });
  }
  files.push({
    relativePath: 'index.generated.ts',
    content: `${imports.join('\n')}\n\nimport type { WeaponDefinition } from '../../../core/game-data/equipmentDefinition';\n\nexport const generatedWeaponDefinitions = [\n${definitions
      .map((_, index) => `  generatedWeapon${index},`)
      .join('\n')}\n] as const satisfies readonly WeaponDefinition[];\n`,
  });
  files.push({
    relativePath: 'weapon-definitions.audit.json',
    content: `${JSON.stringify(createAudit(batch), null, 2)}\n`,
  });
  return files.sort((left, right) => left.relativePath.localeCompare(right.relativePath));
}

function renderDefinition(definition: CompiledWeaponRuntimeDefinitionSource): string {
  return `/** Generated by the Endaxis game-data compiler. Do not edit. */\nimport type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';\n\nconst definition = ${JSON.stringify(
    definition,
    null,
    2,
  )} as const satisfies WeaponDefinition;\n\nexport default definition;\n`;
}

function createAudit(batch: CompiledWeaponRuntimeDefinitionBatchSource) {
  return {
    format: 'EndaxisGeneratedWeaponAudit',
    version: 1,
    definitionCount: batch.definitions.length,
    traitCount: batch.definitions.reduce((total, item) => total + item.traits.length, 0),
    buffDefinitionCount: batch.definitions.reduce(
      (total, item) =>
        total +
        item.traits.reduce(
          (traitTotal, trait) => traitTotal + Object.keys(trait.buffDefinitions ?? {}).length,
          0,
        ),
      0,
    ),
    weaponTypeCounts: countBy(batch.definitions, item => item.weaponType),
    diagnostics: batch.diagnostics,
  };
}

function countBy<T>(values: readonly T[], key: (value: T) => string): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const value of values) counts[key(value)] = (counts[key(value)] ?? 0) + 1;
  return Object.fromEntries(
    Object.entries(counts).sort(([left], [right]) => left.localeCompare(right)),
  );
}

function requireSafeSegment(value: string, path: string): void {
  if (!SAFE_PATH_SEGMENT.test(value)) throw new Error(`${path}: expected a safe path segment`);
}
