// 纯数据契约由独立包唯一声明；此路径保留兼容导出。
export {
  WEAPON_RARITIES,
  type WeaponRarity,
  EQUIPMENT_PANEL_STATS,
  type EquipmentPanelStat,
  type EquipmentAttribute,
  EQUIPMENT_DAMAGE_SCALE_TARGETS,
  type EquipmentDamageScaleTarget,
  type EquipmentModifierDefinition,
  EQUIPMENT_ABILITY_EVENTS,
  type EquipmentAbilityEvent,
  type EquipmentEventHandlerDefinition,
  type EquipmentContributionDefinition,
  type WeaponTraitDefinition,
  type WeaponDefinition,
  GEAR_SLOT_TYPES,
  type GearSlotType,
  type GearTraitDefinition,
  type GearDefinition,
  type GearSetDefinition,
} from '../../../../packages/game-data-contract/src/equipment.ts';
