// 纯数据契约由独立包唯一声明；此路径保留兼容导出。
export {
  OPERATOR_ATTRIBUTES,
  type OperatorAttribute,
  type HealCalculationAttribute,
  OPERATOR_RARITIES,
  type OperatorRarity,
  OPERATOR_WEAPON_TYPES,
  type OperatorWeaponType,
  OPERATOR_ROLES,
  type OperatorRole,
  DAMAGE_ELEMENTS,
  type DamageElement,
  INFLICTION_ELEMENTS,
  type InflictionElement,
  DAMAGE_TYPES,
  type DamageType,
  ELEMENTAL_REACTIONS,
  type ElementalReaction,
  DAMAGE_TAGS,
  type DamageTag,
  DAMAGE_FEATURES,
  type DamageFeature,
  SKILL_TYPES,
  type SkillType,
  SKILL_LEVEL_SOURCES,
  type SkillLevelSource,
  OPERATOR_MISSING_CAPABILITIES,
  type OperatorMissingCapability,
  type OperatorConversionSupport,
  COMBAT_RESOURCES,
  type CombatResource,
  COMBAT_TARGETS,
  type CombatTarget,
  TIMED_MARKER_TARGETS,
  type TimedMarkerTarget,
  TIME_DILATION_IGNORE_TARGETS,
  type TimeDilationIgnoreTarget,
  TIME_DILATION_ENTITY_TARGETS,
  type TimeDilationEntityTarget,
  BUFF_SINGLE_TARGETS,
  type BuffSingleTarget,
  BUFF_APPLICATION_TARGETS,
  type BuffApplicationTarget,
  BUFF_APPLICATION_SOURCES,
  type BuffApplicationSource,
  COMPARISON_OPERATORS,
  type ComparisonOperator,
  type LevelValues,
  type ActionStringOperand,
  DAMAGE_CALCULATIONS,
  type DamageCalculation,
  RESOURCE_RECIPIENTS,
  type ResourceRecipient,
  HEAL_TARGETS,
  type HealTarget,
  SP_GAIN_KINDS,
  type SpGainKind,
  SP_GAIN_SOURCES,
  type SpGainSource,
  PHYSICAL_INFLICTION_TYPES,
  type PhysicalInflictionType,
} from '../../../../packages/game-data-contract/src/primitives.ts';
export {
  type DealDamageParameters,
  type DealFixedDamageParameters,
  type StatusModifierDefinition,
  STATUS_MODIFIER_KINDS,
  type CombatStepParameters,
  COMBAT_STEP_KINDS,
  type CombatStepKind,
  type CombatStepDefinition,
  type ActionSequenceDefinition,
  type ScheduledSequenceDefinition,
  type CombatEventResponseDefinition,
  type CombatEventTrigger,
  COMBAT_EVENT_TRIGGER_KINDS,
  type CombatEventHandlerDefinition,
} from '../../../../packages/game-data-contract/src/actions.ts';
export {
  type CombatCondition,
  COMBAT_CONDITION_KINDS,
  type CombatConditionKind,
  type ActionValueOperand,
  type TimeScaleCurveKeyDefinition,
  type TimeScaleCurveDefinition,
  ACTION_VALUE_OPERATIONS,
  type ActionValueOperation,
  ACTION_VALUE_CALCULATION_OPERATIONS,
  type ActionValueCalculationOperation,
  type BuildCondition,
} from '../../../../packages/game-data-contract/src/conditions.ts';
export {
  type AbilityEntityTargetQuery,
  type AbilityEntityChildSkillDefinition,
  type AbilityEntityDefinition,
  type AbilityEntityDefinitionNumber,
  type OperatorAbilityEntityDefinitions,
  type SkillCostDefinition,
  PLAYER_SKILL_INPUTS,
  type PlayerSkillInput,
  NATIVE_SKILL_TYPES,
  type NativeSkillType,
  type OperatorPlayerActionModeDefinition,
  type OperatorSkillSlotDefinition,
  type PlayerActionRouteDefinition,
  type OperatorPlayerActionRoutes,
  type SkillInputCommandMappingWindow,
  type SkillAllowedNextWindow,
  SKILL_TRIGGER_SCOPES,
  type SkillTriggerScope,
  COMBO_SKILL_PRIORITIES,
  type ComboSkillPriority,
  type SkillDefinition,
  type SkillGroupDefinition,
  type SkillGroupVariantDefinition,
  type RoutedSkillReplacementDefinition,
  type SkillPresentationVariantDefinition,
} from '../../../../packages/game-data-contract/src/skills.ts';
export {
  type SkillBuffPresentation,
  type SkillBuffLifecycleSequences,
  type SkillBuffAbilityEventResponse,
  type SkillBuffIgniteEventResponse,
  type SkillBuffSlotReplacement,
  type SkillBuffDefinition,
  type SkillGlobalBuffChildDefinition,
  type SkillGlobalBuffDefinition,
  type OperatorBuffDefinitions,
} from '../../../../packages/game-data-contract/src/buffs.ts';
export type { ActionBlackboardValue } from '../../../../packages/game-data-contract/src/primitives.ts';
export {
  type AttributeGrowthDefinition,
  type TrustAttributeBonusDefinition,
  DEFAULT_TRUST_ATTRIBUTE_BONUS,
  UPGRADE_BASE_PANEL_STATS,
  type UpgradeBasePanelStat,
  UPGRADE_STATIC_DAMAGE_INCREASE_TARGETS,
  type UpgradeStaticDamageIncreaseTarget,
  type UpgradeModifierDefinition,
  UPGRADE_MODIFIER_KINDS,
  type UpgradeModifierKind,
  type UpgradeEvent,
  type UpgradeEventHandlerDefinition,
  type OperatorPassiveSkillDefinition,
  type OperatorUpgradeDefinition,
  OPERATOR_EVENTS,
  type OperatorEvent,
  type OperatorEventHandlerDefinition,
  type OperatorEntityBlackboardInitializerDefinition,
  type OperatorPassiveUiDefinition,
  type ComboSkillConditionDefinition,
  type OperatorDefinition,
} from '../../../../packages/game-data-contract/src/operators.ts';
export {
  ABILITY_EVENTS,
  type AbilityEvent,
} from '../../../../packages/game-data-contract/src/abilityEvents.ts';
export {
  BUFF_ABILITY_EVENTS,
  type BuffAbilityEvent,
} from '../../../../packages/game-data-contract/src/buffs.ts';
