import type { UpgradeModifierDefinition } from '../../../../core/game-data/operatorDefinition';
export const upgradeModifierLabels: Readonly<Record<UpgradeModifierDefinition['kind'], string>> = {
  addConditionalDamage: '条件伤害加算',
  enableSkillBranch: '启用技能分支',
  multiplyEffectDuration: '效果持续时间倍率',
  multiplySkillCost: '技能消耗倍率',
  setEffectiveness: '设置效果强度',
  addStaticDamageIncrease: '常驻伤害提升',
  addStaticHealingIncrease: '常驻治疗提升',
  addSkillStat: '技能属性加成',
  patchSkillBlackboard: '修改技能初始黑板',
  patchPassiveBlackboard: '修改被动初始黑板',
  multiplySkillDamage: '技能伤害倍率',
  multiplyStepDamage: '步骤伤害倍率',
  multiplySkillCooldown: '技能冷却倍率',
  addSkillCooldownFrames: '技能冷却帧加算',
  addBuildAttribute: '构筑四维加成',
  modifyBasePanelStat: '基础面板修正',
  addReactionDuration: '反应持续时间加算',
  addReactionEffectiveness: '反应效果强度加算',
};
