/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_funnel_0005',
  rarity: 5,
  weaponType: 'funnel',
  baseAttackAtLevelNodes: [42, 120, 203, 286, 369, 411],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'intellect',
          operation: 'flat',
          value: [16, 28, 41, 54, 67, 80, 92, 105, 124],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_wisd_mid',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'attackPercent',
          value: [0.04, 0.072, 0.104, 0.136, 0.168, 0.2, 0.232, 0.264, 0.312],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_atk_mid',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'healthPercent',
          value: [0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.24, 0.28],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_funnel_0005_atk_up',
                      copiedBlackboardAssignments: {
                        duration: 'duration',
                        atk_up: 'atk_up',
                        lv: 'lv',
                      },
                    },
                  ],
                  target: 'currentTarget',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: null,
            },
            checkCondition_2: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
              },
              next: 'applyBuff_1',
            },
            invertNextResult_3: {
              action: { kind: 'invertNextResult', parameters: {} },
              next: 'checkCondition_2',
            },
            storeCharacterTypeId_4: {
              action: {
                kind: 'storeCharacterTypeId',
                parameters: { target: 'currentTarget', outputKey: 'team_char_type' },
              },
              next: 'invertNextResult_3',
            },
            forEachContextTarget_5: {
              action: {
                kind: 'forEachContextTarget',
                parameters: { targets: { kind: 'characterTeam', excludeOwner: true } },
                body: { $sequence: 'storeCharacterTypeId_4' },
              },
              next: null,
            },
            storeCharacterTypeId_6: {
              action: {
                kind: 'storeCharacterTypeId',
                parameters: { target: 'caster', outputKey: 'ower_char_type' },
              },
              next: 'forEachContextTarget_5',
            },
            checkCondition_7: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_4' } },
              },
              next: 'storeCharacterTypeId_6',
            },
          },
          dataNodes: {
            data_1: { type: 'string', expression: { blackboardKey: 'ower_char_type' } },
            data_2: { type: 'string', expression: { blackboardKey: 'team_char_type' } },
            data_3: {
              type: 'boolean',
              expression: {
                kind: 'stringEquals',
                left: { kind: 'stringNode', nodeId: 'data_1' },
                right: { kind: 'stringNode', nodeId: 'data_2' },
              },
            },
            data_4: {
              type: 'boolean',
              expression: { kind: 'eventSkillTypeIn', skillTypes: ['ultimate'] },
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_funnel_0005',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'beforeCastSkill',
          priority: 0,
          sequence: { $sequence: 'checkCondition_7' },
        },
      ],
      blackboard: {
        atk_up: [0.08, 0.096, 0.112, 0.128, 0.144, 0.16, 0.176, 0.192, 0.224],
        duration: [20, 20, 20, 20, 20, 20, 20, 20, 20],
        lv: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      },
    },
  ],
  assetSlug: 'wpn_funnel_0005',
  icon: 'endaxis:weapons/funnel/wpn_funnel_0005',
  buffDefinitions: {
    buff_wpn_funnel_0005_atk_up: {
      stackingType: 'highPriority',
      priority: { blackboardKey: 'lv' },
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_buff_atk_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { atk_up: 0, duration: 0, lv: 0 },
      attributeModifiers: [
        { attribute: 'Atk', slot: 'baseMultiplier', value: { blackboardKey: 'atk_up' } },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
