/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_funnel_0015',
  rarity: 6,
  weaponType: 'funnel',
  baseAttackAtLevelNodes: [52, 149, 252, 355, 458, 510],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'will',
          operation: 'flat',
          value: [20, 36, 52, 68, 84, 100, 116, 132, 156],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_will_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'attackPercent',
          value: [0.05, 0.09, 0.13, 0.17, 0.21, 0.25, 0.29, 0.33, 0.39],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_atk_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'electric',
          slot: 'baseAddition',
          value: [0.16, 0.192, 0.224, 0.256, 0.288, 0.32, 0.352, 0.384, 0.448],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            createTimedMarker_1: {
              action: {
                kind: 'createTimedMarker',
                parameters: {
                  targets: { kind: 'owner' },
                  markerId: 'sk_wpn_funnel_0015',
                  durationSeconds: { kind: 'valueNode', nodeId: 'data_1' },
                  autoFinishByAction: false,
                  timeDomain: 'globalScaled',
                },
              },
              next: null,
            },
            applyBuff_2: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_funnel_0015_combo',
                      copiedBlackboardAssignments: {
                        pulse_dmg_up: 'pulse_dmg_up2',
                        max_stack: 'max_stack',
                        duration: 'duration',
                      },
                    },
                  ],
                  targets: { kind: 'source' },
                  source: { kind: 'source' },
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: 'createTimedMarker_1',
            },
            checkCondition_3: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_2' } },
              },
              next: 'applyBuff_2',
            },
            checkCondition_4: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
              },
              next: 'checkCondition_3',
            },
            checkCondition_5: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_5' } },
              },
              next: 'checkCondition_4',
            },
            applyBuff_6: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_funnel_0015_ultimate',
                      copiedBlackboardAssignments: {
                        pulse_dmg_up: 'pulse_dmg_up3',
                        duration: 'duration2',
                      },
                    },
                  ],
                  targets: { kind: 'source' },
                  source: { kind: 'source' },
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: null,
            },
            checkCondition_7: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_6' } },
              },
              next: 'applyBuff_6',
            },
          },
          dataNodes: {
            data_1: { type: 'number', expression: { kind: 'blackboard', key: 'cd' } },
            data_2: {
              type: 'boolean',
              expression: {
                kind: 'eventBuffTagsMatch',
                match: 'hasAny',
                buffTags: ['Skill/Character/Common/SpellStatus'],
              },
            },
            data_3: {
              type: 'boolean',
              expression: { kind: 'originSkillTypeIn', skillTypes: ['battleSkill'] },
            },
            data_4: {
              type: 'boolean',
              expression: {
                kind: 'timedMarkerPresent',
                target: 'caster',
                markerId: 'sk_wpn_funnel_0015',
              },
            },
            data_5: {
              type: 'boolean',
              expression: { kind: 'not', condition: { kind: 'conditionNode', nodeId: 'data_4' } },
            },
            data_6: {
              type: 'boolean',
              expression: { kind: 'eventSkillTypeIn', skillTypes: ['ultimate'] },
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_funnel_0015',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'buffConsumed',
          priority: 0,
          sequence: { $sequence: 'checkCondition_5' },
        },
        {
          key: 'skill3:event:1:sequence:0',
          abilityEvent: 'beforeCastSkill',
          priority: 0,
          sequence: { $sequence: 'checkCondition_7' },
        },
      ],
      blackboard: {
        cd: 0.1,
        duration: [20, 20, 20, 20, 20, 20, 20, 20, 20],
        duration2: [25, 25, 25, 25, 25, 25, 25, 25, 25],
        max_stack: [2, 2, 2, 2, 2, 2, 2, 2, 2],
        pulse_dmg_up2: [0.2, 0.24, 0.28, 0.32, 0.36, 0.4, 0.44, 0.48, 0.56],
        pulse_dmg_up3: [0.4, 0.48, 0.56, 0.64, 0.72, 0.8, 0.88, 0.96, 1.12],
      },
    },
  ],
  assetSlug: 'wpn_funnel_0015',
  icon: 'endaxis:weapons/funnel/wpn_funnel_0015',
  buffDefinitions: {
    buff_wpn_funnel_0015_combo: {
      stackingType: 'stack',
      priority: 0,
      maxStackCount: { blackboardKey: 'max_stack' },
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_pulse_dmg_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 0, max_stack: 0, pulse_dmg_up: 0 },
      attributeModifiers: [],
      damageModifiers: [
        {
          enabledSide: 'attacker',
          condition: { $sequence: 'checkCondition_2' },
          processors: [
            {
              kind: 'damageScale',
              side: 'attacker',
              zone: 'normal',
              addition: { blackboardKey: 'pulse_dmg_up' },
            },
          ],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            checkCondition_1: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
              },
              next: null,
            },
            checkCondition_2: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_2' } },
              },
              next: 'checkCondition_1',
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: { kind: 'eventDamageTypeIn', damageTypes: ['electric'] },
            },
            data_2: {
              type: 'boolean',
              expression: { kind: 'eventDamageTagsMatch', match: 'hasAll', tags: ['normalSkill'] },
            },
          },
        },
        macros: {},
      },
    },
    buff_wpn_funnel_0015_ultimate: {
      stackingType: 'refresh',
      priority: 0,
      maxStackCount: { blackboardKey: 'max_stack' },
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_pulse_dmg_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 0, pulse_dmg_up: 0 },
      attributeModifiers: [],
      damageModifiers: [
        {
          enabledSide: 'attacker',
          condition: { $sequence: 'checkCondition_2' },
          processors: [
            {
              kind: 'damageScale',
              side: 'attacker',
              zone: 'normal',
              addition: { blackboardKey: 'pulse_dmg_up' },
            },
          ],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            checkCondition_1: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
              },
              next: null,
            },
            checkCondition_2: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_2' } },
              },
              next: 'checkCondition_1',
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: { kind: 'eventDamageTypeIn', damageTypes: ['electric'] },
            },
            data_2: {
              type: 'boolean',
              expression: { kind: 'eventDamageTagsMatch', match: 'hasAll', tags: ['normalSkill'] },
            },
          },
        },
        macros: {},
      },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
