/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_funnel_0011',
  rarity: 6,
  weaponType: 'funnel',
  baseAttackAtLevelNodes: [51, 146, 247, 348, 449, 500],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'will',
          operation: 'flat',
          value: [20, 36, 52, 68, 84, 100, 116, 132, 156],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_will_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'ultimateEnergyGainEfficiency',
          value: [
            0.05952381, 0.10714286, 0.15476191, 0.20238096, 0.25, 0.29761904, 0.3452381, 0.39285713,
            0.4642857,
          ],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_usgs_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'nature',
          slot: 'addition',
          value: [0.16, 0.192, 0.224, 0.256, 0.288, 0.32, 0.352, 0.384, 0.448],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_wpn_funnel_0011',
                  target: 'caster',
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                  copiedBlackboardAssignments: {
                    spell_dmg_up: 'spell_dmg_up',
                    spell_dmg_up2: 'spell_dmg_up2',
                    duration: 'duration',
                    max_stack: 'max_stack',
                  },
                },
              },
              next: null,
            },
            conditional_2: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
                whenTrue: { $sequence: 'applyBuff_1' },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: { kind: 'eventSkillTypeIn', skillTypes: ['comboSkill'] },
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_funnel_0011',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'beforeCastSkill',
          priority: 0,
          sequence: { $sequence: 'conditional_2' },
        },
      ],
      blackboard: {
        duration: [15, 15, 15, 15, 15, 15, 15, 15, 15],
        max_stack: [3, 3, 3, 3, 3, 3, 3, 3, 3],
        spell_dmg_up: [0.12, 0.144, 0.168, 0.192, 0.216, 0.24, 0.264, 0.288, 0.336],
        spell_dmg_up2: [0.035, 0.042, 0.049, 0.056, 0.063, 0.07, 0.077, 0.084, 0.098],
      },
    },
  ],
  assetSlug: 'wpn_funnel_0011',
  icon: 'endaxis:weapons/funnel/wpn_funnel_0011',
  buffDefinitions: {
    buff_wpn_funnel_0011: {
      stackingType: 'unlimited',
      priority: 0,
      maxStackCount: 0,
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      applyTags: [],
      extendTags: [],
      blackboard: {
        count: 0,
        duration: 15,
        max_stack: 4,
        spell_dmg_up: 0.05,
        spell_dmg_up_final: 0,
        spell_dmg_up2: 0.02,
      },
      attributeModifiers: [],
      lifecycleSequences: {
        start: { $sequence: 'mergeContextTargets_1' },
        enable: { $sequence: 'skillAffix_2' },
      },
      abilityEventResponses: [
        {
          event: 'afterOutputPhysicalInfliction',
          priority: 0,
          sequence: { $sequence: 'conditional_12' },
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            mergeContextTargets_1: {
              action: {
                kind: 'mergeContextTargets',
                parameters: { saveToContextKey: 'wpn_funnel_0011_total_tar', sources: [] },
              },
              next: null,
            },
            skillAffix_2: { action: { kind: 'skillAffix', parameters: {} }, next: null },
            applyBuff_3: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_wpn_funnel_0011_valid',
                  target: 'party',
                  inheritSourceSkillCastInfo: true,
                  copiedBlackboardAssignments: {
                    spell_dmg_up: 'spell_dmg_up_final',
                    duration: 'duration',
                  },
                },
              },
              next: null,
            },
            modifyActionValue_4: {
              action: {
                kind: 'modifyActionValue',
                parameters: {
                  key: 'spell_dmg_up_final',
                  operation: 'add',
                  value: { kind: 'valueNode', nodeId: 'data_1' },
                },
              },
              next: 'applyBuff_3',
            },
            calculateActionValue_5: {
              action: {
                kind: 'calculateActionValue',
                parameters: {
                  key: 'spell_dmg_up_final',
                  operation: 'multiply',
                  left: { kind: 'valueNode', nodeId: 'data_2' },
                  right: { kind: 'valueNode', nodeId: 'data_3' },
                },
              },
              next: 'modifyActionValue_4',
            },
            conditional_6: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_6' } },
                whenTrue: { $sequence: 'calculateActionValue_5' },
              },
              next: null,
            },
            conditional_7: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_7' } },
                whenTrue: { $sequence: 'conditional_6' },
              },
              next: null,
            },
            mergeContextTargets_8: {
              action: {
                kind: 'mergeContextTargets',
                parameters: {
                  saveToContextKey: 'wpn_funnel_0011_total_tar',
                  sources: [
                    { kind: 'target', target: 'eventTarget' },
                    { kind: 'context', contextKey: 'wpn_funnel_0011_total_tar' },
                  ],
                },
              },
              next: 'conditional_7',
            },
            conditional_9: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_9' } },
                whenTrue: { $sequence: 'mergeContextTargets_8' },
              },
              next: null,
            },
            conditional_10: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_10' } },
                whenTrue: { $sequence: 'conditional_9' },
              },
              next: null,
            },
            conditional_11: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_11' } },
                whenTrue: { $sequence: 'conditional_10' },
              },
              next: null,
            },
            conditional_12: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_12' } },
                whenTrue: { $sequence: 'conditional_11' },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: { type: 'number', expression: { kind: 'blackboard', key: 'spell_dmg_up' } },
            data_2: { type: 'number', expression: { kind: 'blackboard', key: 'count' } },
            data_3: { type: 'number', expression: { kind: 'blackboard', key: 'spell_dmg_up2' } },
            data_4: {
              type: 'number',
              expression: { kind: 'blackboard', key: 'count', fallback: 0 },
            },
            data_5: {
              type: 'number',
              expression: { kind: 'blackboard', key: 'max_stack', fallback: 0 },
            },
            data_6: {
              type: 'boolean',
              expression: {
                kind: 'actionValueCompare',
                left: { kind: 'valueNode', nodeId: 'data_4' },
                operator: 'lessOrEqual',
                right: { kind: 'valueNode', nodeId: 'data_5' },
              },
            },
            data_7: {
              type: 'boolean',
              expression: {
                kind: 'contextTargetCountCompare',
                contextKey: 'wpn_funnel_0011_total_tar',
                operator: 'greaterOrEqual',
                value: 1,
                outputKey: 'count',
              },
            },
            data_8: {
              type: 'boolean',
              expression: {
                kind: 'contextTargetContains',
                parentContextKey: 'wpn_funnel_0011_total_tar',
                child: 'eventTarget',
              },
            },
            data_9: {
              type: 'boolean',
              expression: { kind: 'not', condition: { kind: 'conditionNode', nodeId: 'data_8' } },
            },
            data_10: {
              type: 'boolean',
              expression: { kind: 'originSkillTypeIn', skillTypes: ['comboSkill'] },
            },
            data_11: {
              type: 'boolean',
              expression: { kind: 'eventPhysicalInflictionTypeIn', types: ['airborne'] },
            },
            data_12: { type: 'boolean', expression: { kind: 'eventSkillCastMatchesBuffSource' } },
          },
        },
        macros: {},
      },
    },
    buff_wpn_funnel_0011_valid: {
      stackingType: 'highPriority',
      priority: { blackboardKey: 'spell_dmg_up' },
      maxStackCount: 1,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_spell_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 15, lv: 0, spell_dmg_up: 0.05 },
      attributeModifiers: [
        {
          attribute: 'heatDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'electricDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'cryoDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
        {
          attribute: 'natureDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up' },
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
