/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_funnel_0007',
  rarity: 5,
  weaponType: 'funnel',
  baseAttackAtLevelNodes: [42, 120, 203, 286, 369, 411],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'will',
          operation: 'flat',
          value: [16, 28, 41, 54, 67, 80, 92, 105, 124],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_will_mid',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'ultimateEnergyGainEfficiency',
          value: [
            0.04761905, 0.08571429, 0.123809524, 0.16190477, 0.2, 0.23809524, 0.2761905, 0.31428573,
            0.37142858,
          ],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_usgs_mid',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'main',
          operation: 'percent',
          value: [0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.14],
        },
        { kind: 'panelStat', stat: 'artsIntensity', value: [25, 30, 35, 40, 45, 50, 55, 60, 70] },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'sk_wpn_funnel_0007',
    },
  ],
  assetSlug: 'wpn_funnel_0007',
  icon: 'endaxis:weapons/funnel/wpn_funnel_0007',
} as const satisfies WeaponDefinition;
export default definition;
