/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_funnel_0008',
  rarity: 6,
  weaponType: 'funnel',
  baseAttackAtLevelNodes: [50, 144, 243, 342, 441, 490],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'main',
          operation: 'flat',
          value: [17, 30, 44, 57, 71, 85, 98, 112, 132],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_main_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        { kind: 'panelStat', stat: 'artsIntensity', value: [10, 18, 26, 34, 42, 50, 58, 66, 78] },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_phy_spell_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'secondary',
          operation: 'percent',
          value: [0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.24, 0.28],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffId: 'buff_wpn_funnel_0008_magic_damage_taken_up',
                  target: 'eventTarget',
                  inheritSourceSkillCastInfo: true,
                  copiedBlackboardAssignments: {
                    spell_damage_taken_up: 'spell_damage_taken_up',
                    duration: 'duration',
                    lv: 'lv',
                  },
                },
              },
              next: null,
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_funnel_0008',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'beforeOutputSpellBurst',
          priority: 0,
          sequence: { $sequence: 'applyBuff_1' },
        },
      ],
      blackboard: {
        duration: [15, 15, 15, 15, 15, 15, 15, 15, 15],
        lv: [1, 2, 3, 4, 5, 6, 7, 8, 9],
        spell_damage_taken_up: [0.09, 0.108, 0.126, 0.144, 0.162, 0.18, 0.198, 0.216, 0.252],
      },
    },
  ],
  assetSlug: 'wpn_funnel_0010',
  icon: 'endaxis:weapons/funnel/wpn_funnel_0010',
  buffDefinitions: {
    buff_wpn_funnel_0008_magic_damage_taken_up: {
      stackingType: 'highPriority',
      priority: { blackboardKey: 'lv' },
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_spell_taken_up',
        showInHeadBarCommon: true,
        showInHeadBarAttached: false,
        showInSquadIcon: false,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'LifeTime',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 0, lv: 0, spell_damage_taken_up: 0 },
      attributeModifiers: [],
      damageModifiers: [
        {
          enabledSide: 'defender',
          condition: { $sequence: 'conditional_1' },
          processors: [
            {
              kind: 'damageScale',
              side: 'defender',
              zone: 'normal',
              addition: { blackboardKey: 'spell_damage_taken_up' },
            },
          ],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            conditional_1: {
              action: {
                kind: 'conditional',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_1' } },
                whenTrue: { $sequence: null },
              },
              next: null,
            },
          },
          dataNodes: {
            data_1: {
              type: 'boolean',
              expression: {
                kind: 'eventDamageTypeIn',
                damageTypes: ['heat', 'electric', 'cryo', 'nature'],
              },
            },
          },
        },
        macros: {},
      },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
