/** Generated by the Endaxis game-data compiler. Do not edit. */
import type { WeaponDefinition } from '../../../../core/game-data/equipmentDefinition';
const definition = {
  slug: 'wpn_funnel_0019',
  rarity: 6,
  weaponType: 'funnel',
  baseAttackAtLevelNodes: [51, 148, 250, 352, 454, 505],
  traits: [
    {
      key: 'skill1',
      levelCount: 9,
      modifiers: [
        {
          kind: 'attribute',
          attribute: 'agility',
          operation: 'flat',
          value: [20, 36, 52, 68, 84, 100, 116, 132, 156],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_attr_agi_high',
    },
    {
      key: 'skill2',
      levelCount: 9,
      modifiers: [
        {
          kind: 'panelStat',
          stat: 'attackPercent',
          value: [0.05, 0.09, 0.13, 0.17, 0.21, 0.25, 0.29, 0.33, 0.39],
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
      skillId: 'wpn_sp_attr_atk_high',
    },
    {
      key: 'skill3',
      levelCount: 9,
      modifiers: [
        {
          kind: 'damageScale',
          target: 'heat',
          slot: 'baseAddition',
          value: [0.16, 0.192, 0.224, 0.256, 0.288, 0.32, 0.352, 0.384, 0.448],
        },
        {
          kind: 'damageScale',
          target: 'electric',
          slot: 'baseAddition',
          value: [0.16, 0.192, 0.224, 0.256, 0.288, 0.32, 0.352, 0.384, 0.448],
        },
        {
          kind: 'damageScale',
          target: 'cryo',
          slot: 'baseAddition',
          value: [0.16, 0.192, 0.224, 0.256, 0.288, 0.32, 0.352, 0.384, 0.448],
        },
        {
          kind: 'damageScale',
          target: 'nature',
          slot: 'baseAddition',
          value: [0.16, 0.192, 0.224, 0.256, 0.288, 0.32, 0.352, 0.384, 0.448],
        },
      ],
      actionGraph: {
        main: {
          nodes: {
            applyBuff_1: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_funnel_0019_intensityup',
                      copiedBlackboardAssignments: { phy_spell_up: 'phy_spell_up' },
                    },
                  ],
                  targets: { kind: 'owner' },
                  source: { kind: 'source' },
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: null,
            },
            applyBuff_2: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [{ buffId: 'buff_wpn_funnel_0019_burstup_layer' }],
                  targets: { kind: 'owner' },
                  source: { kind: 'source' },
                  count: { kind: 'valueNode', nodeId: 'data_1' },
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: 'applyBuff_1',
            },
            checkCondition_3: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_2' } },
              },
              next: 'applyBuff_2',
            },
            createTimedMarker_4: {
              action: {
                kind: 'createTimedMarker',
                parameters: {
                  targets: { kind: 'owner' },
                  markerId: 'sk_wpn_funnel_0019',
                  durationSeconds: { kind: 'constant', value: 0.1 },
                  autoFinishByAction: false,
                  timeDomain: 'globalScaled',
                },
              },
              next: null,
            },
            applyBuff_5: {
              action: {
                kind: 'applyBuff',
                parameters: {
                  buffs: [
                    {
                      buffId: 'buff_wpn_funnel_0019_spelldmgup',
                      copiedBlackboardAssignments: { spell_dmg_up2: 'spell_dmg_up2' },
                    },
                  ],
                  targets: { kind: 'owner' },
                  source: { kind: 'source' },
                  inheritSourceSkillCastInfo: true,
                  asChildBuff: true,
                },
              },
              next: 'createTimedMarker_4',
            },
            finishBuffsById_6: {
              action: {
                kind: 'finishBuffsById',
                parameters: {
                  targets: { kind: 'owner' },
                  finishSource: { kind: 'source' },
                  buffIds: ['buff_wpn_funnel_0019_burstup_layer'],
                  reason: 'other',
                  count: { kind: 'constant', value: 1 },
                },
              },
              next: 'applyBuff_5',
            },
            checkCondition_7: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_3' } },
              },
              next: 'finishBuffsById_6',
            },
            checkCondition_8: {
              action: {
                kind: 'checkCondition',
                parameters: { condition: { kind: 'conditionNode', nodeId: 'data_5' } },
              },
              next: 'checkCondition_7',
            },
          },
          dataNodes: {
            data_1: { type: 'number', expression: { kind: 'blackboard', key: 'wind_grant' } },
            data_2: {
              type: 'boolean',
              expression: { kind: 'eventSkillTypeIn', skillTypes: ['battleSkill'] },
            },
            data_3: {
              type: 'boolean',
              expression: {
                kind: 'buffIdStackCompare',
                target: 'caster',
                buffIds: ['buff_wpn_funnel_0019_burstup_layer'],
                operator: 'greaterOrEqual',
                value: { kind: 'constant', value: 1 },
              },
            },
            data_4: {
              type: 'boolean',
              expression: {
                kind: 'timedMarkerPresent',
                target: 'caster',
                markerId: 'sk_wpn_funnel_0019',
              },
            },
            data_5: {
              type: 'boolean',
              expression: { kind: 'not', condition: { kind: 'conditionNode', nodeId: 'data_4' } },
            },
          },
        },
        macros: {},
      },
      skillId: 'sk_wpn_funnel_0019',
      eventHandlers: [
        {
          key: 'skill3:event:0:sequence:0',
          abilityEvent: 'beforeCastSkill',
          priority: 0,
          sequence: { $sequence: 'checkCondition_3' },
        },
        {
          key: 'skill3:event:1:sequence:0',
          abilityEvent: 'beforeOutputSpellBurst',
          priority: 0,
          sequence: { $sequence: 'checkCondition_8' },
        },
      ],
      blackboard: {
        phy_spell_up: [35, 42, 49, 56, 63, 70, 77, 84, 98],
        spell_dmg_up2: [0.04, 0.048, 0.056, 0.064, 0.072, 0.08, 0.088, 0.096, 0.112],
        wind_grant: [4, 4, 4, 4, 4, 4, 4, 4, 4],
      },
    },
  ],
  assetSlug: 'wpn_funnel_0019',
  icon: 'endaxis:weapons/funnel/wpn_funnel_0019',
  buffDefinitions: {
    buff_wpn_funnel_0019_burstup_layer: {
      stackingType: 'stack',
      priority: 0,
      maxStackCount: 4,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_buff_wpn_funnel_0019',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
        nameKey: 'effects.name.windform',
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 15 },
      attributeModifiers: [],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
    buff_wpn_funnel_0019_intensityup: {
      stackingType: 'refresh',
      priority: 0,
      maxStackCount: 0,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_physical_infliction_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 15, phy_spell_up: 35 },
      attributeModifiers: [
        {
          attribute: 'PhysicalAndSpellInflictionEnhance',
          slot: 'baseAddition',
          value: { blackboardKey: 'phy_spell_up' },
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
    buff_wpn_funnel_0019_spelldmgup: {
      stackingType: 'highPriorityWithMaxStack',
      priority: 0,
      maxStackCount: 4,
      durationSeconds: { blackboardKey: 'duration' },
      triggerIntervalSeconds: 0,
      waitFirstTriggerInterval: true,
      maxTriggerCount: 1,
      presentation: {
        visible: true,
        icon: 'endaxis:icons/icon_battle_spell_up',
        showInHeadBarCommon: false,
        showInHeadBarAttached: false,
        showInSquadIcon: true,
        onlyShowForMainCharacter: false,
        blinkInMainCharHpBar: false,
        showProgressInHpBar: false,
        showProgressInNormalSkillButton: false,
        useWeakProgressInNormalSkillButton: false,
        showProgressInUltimateSkillButton: false,
        forceRaiseIconEvent: false,
        showWarningBackground: false,
        playStrongInAnimation: false,
        hasCharHpBarVfxType: false,
        charHpBarVfxType: 'Fire',
        iconStyleInSquad: 'Default',
        abnormalColorType: 'Physical',
        orderPriority: { useDirectoryValue: false, value: 0, category: 'CommonCharBuff' },
      },
      applyTags: [],
      extendTags: [],
      blackboard: { duration: 30, spell_dmg_up2: 0.04 },
      attributeModifiers: [
        {
          attribute: 'heatDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up2' },
        },
        {
          attribute: 'electricDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up2' },
        },
        {
          attribute: 'cryoDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up2' },
        },
        {
          attribute: 'natureDamageIncrease',
          slot: 'baseAddition',
          value: { blackboardKey: 'spell_dmg_up2' },
        },
      ],
      actionGraph: { main: { nodes: {} }, macros: {} },
    },
  },
} as const satisfies WeaponDefinition;
export default definition;
